huggingface/optimum

README.md
=> Fix pip install in readme

README.md
Provides a description of the Optimum library as well as the ONNX Runtime and Intel Neural Compressor (INC) supported quantization approach.
=> Provide Optimum description as well as the supported quantization approach 

examples/pytorch/question-answering/run_qa.py, examples/pytorch/text-classification/run_glue.py, examples/pytorch/token-classification/run_ner.py
This  PR adds OptimizationArguments, a subset of the arguments related to optimization, used in our example scripts.
=> Add a subset of the arguments related to optimization

src/optimum/intel/neural_compressor/quantization.py
This PR removes the unnecessary warnings resulting from the loading of a quantized model.
=> Remove unnecessary warnings resulting from loading of quantized model

examples/inc/pytorch/language-modeling/README.md, examples/inc/pytorch/multiple-choice/README.md, examples/inc/pytorch/question-answering/README.md, examples/inc/pytorch/text-classification/README.md, examples/inc/pytorch/token-classification/README.md
=> Fix broken links

examples/inc/pytorch/language-modeling/run_clm.py, examples/inc/pytorch/language-modeling/run_mlm.py, examples/inc/pytorch/multiple-choice/run_swag.py, examples/inc/pytorch/question-answering/run_qa.py, examples/inc/pytorch/text-classification/run_glue.py, examples/inc/pytorch/token-classification/run_ner.py, optimum/intel/neural_compressor/__init__.py, optimum/intel/neural_compressor/config.py, optimum/intel/neural_compressor/optimizer.py, optimum/intel/neural_compressor/pruning.py, optimum/intel/neural_compressor/quantization.py, optimum/intel/neural_compressor/trainer_inc.py, optimum/intel/neural_compressor/utils.py, tests/intel/test_inc.py
Add IncOptimizer class for INC pruning and quantization combination
=> Add IncOptimizer class for INC pruning and quantization combination

optimum/configuration_utils.py, optimum/utils/__init__.py, optimum/utils/logging.py
This PR provides a base class that matches the behaviour of `transformers.PretrainedConfig` while providing the ability to specify a custom `CONFIG_NAME`, allowing to push and download any kind of configuration from the hub.
=> Configuration base class

optimum/onnxruntime/optimization.py, tests/onnxruntime/ort_config.json, tests/onnxruntime/test_onnxruntime.py
Decrease accepted absolute tolerance onnxruntime test
=> Decrease accepted absolute tolerance onnxruntime test

examples/inc/pytorch/language-modeling/run_clm.py, examples/inc/pytorch/language-modeling/run_mlm.py, examples/inc/pytorch/multiple-choice/run_swag.py, examples/inc/pytorch/question-answering/run_qa.py, examples/inc/pytorch/text-classification/run_glue.py, examples/inc/pytorch/token-classification/run_ner.py, optimum/intel/neural_compressor/quantization.py, optimum/intel/neural_compressor/utils.py, setup.py, tests/intel/test_inc.py
Support Intel Neural Compressor 1.9 version.
=> Support INC1.9

optimum/onnxruntime/optimization.py, optimum/onnxruntime/quantization.py, tests/onnxruntime/test_onnxruntime.py
This PR adds the possibility to optimize and quantize an existing onnx model, without the need to first export the model
=> Add possibility to optimize and quantize existing onnx model

README.md
This PR adds a quickstart for the ONNX Runtime features of the library. Although the docstrings are great, I think this will help people get started quickly :)
I also took the liberty of tidying up the installation section & included the `graphcore` install.
=> Add quickstart

README.md
Fixes some minor typos etc in the quickstart
=> Fix typos / grammar in quickstart

notebook/README.md
In this PR, we add a notebook that shows how to apply different quantization approaches such as static and dynamic quantization using ONNX Runtime for text classification tasks.
=> Add ONNX Runtime quantization for text classification notebook

.github/workflows/check_code_quality.yml, .github/workflows/test_optimum_common.yml, setup.py
This PR adds a `dev` install that includes the core dependencies needed to run `make style` and `make test`. 
We also need this because the `doc-builder` library relies on `black` to build the documentation and the simplest way to do this is by adding a dev install to the library. 
I also took the liberty of updating the GitHub Actions with the new optional installs.
=> Add dev install for tests and quality

setup.py
In this PR we remove three `console_scripts` entry points pointing to functions which do no longer exist
=> Remove entry points 

.github/workflows/test_onnxruntime_train.yml, tests/onnxruntime/test_onnxruntime_train.py
-  This PR fixes the path error due to a change of the example folder.
=> Fix workflow path

optimum/onnxruntime/configuration.py, optimum/onnxruntime/optimization.py, optimum/onnxruntime/quantization.py, optimum/onnxruntime/utils.py
In this PR we verify the models supported and compatible with ONNX Runtime before applying an optimization or quantization step
=> Add verification model type supported by ONNX Runtime

.github/workflows/build_documentation.yml
This PR continues debugging the docs build to accomodate INC. This time we upgrade `pip` and `apt` as an added test.
=> Update pip in docs build env

examples/onnxruntime/training/question-answering/run_qa.py, examples/onnxruntime/training/test_examples.py, examples/onnxruntime/training/text-classification/README.md, examples/onnxruntime/training/text-classification/run_glue.py, examples/onnxruntime/training/token-classification/README.md, examples/onnxruntime/training/token-classification/run_ner.py, examples/onnxruntime/training/translation/README.md, examples/onnxruntime/training/translation/requirements.txt, examples/onnxruntime/training/translation/run_translation.py, optimum/onnxruntime/__init__.py, optimum/onnxruntime/trainer.py, optimum/onnxruntime/trainer_seq2seq.py, tests/onnxruntime/test_onnxruntime_train.py
* Add seq2seq trainer for ONNX Runtime training.
* Add a translation example.
* Add some benchmark results in Readmes.
=> Add Seq2SeqORTTrainer and translation example

docs/source/onnxruntime/trainer.mdx, examples/onnxruntime/training/translation/run_translation.py, optimum/onnxruntime/__init__.py, optimum/onnxruntime/trainer.py, optimum/onnxruntime/trainer_seq2seq.py, tests/onnxruntime/test_onnxruntime_train.py
* Precise execution provider for `InferenceSession`
* Change `Seq2SeqORTTrainer` to `ORTSeq2SeqTrainer` (*trainer_seq2seq.py* and *test_onnxruntime_train.py*)
=> Patch release 1.1.0

README.md, docs/source/index.mdx, setup.py
- Explain how to install `optimum-habana` with `pip install optimum[habana]`
- Update the README/doc with optimum-habana
=> Add optimum-habana to setup.py and README/doc

examples/onnxruntime/optimization/question-answering/run_qa.py, examples/onnxruntime/optimization/text-classification/run_glue.py, examples/onnxruntime/optimization/token-classification/run_ner.py, examples/onnxruntime/quantization/question-answering/run_qa.py, examples/onnxruntime/quantization/text-classification/run_glue.py, examples/onnxruntime/quantization/token-classification/run_ner.py, optimum/onnxruntime/configuration.py, tests/onnxruntime/test_onnxruntime.py
In this PR, we fix the ` ORTConfig.from_pretrained` method and add the corresponding test
=> Fix ort config

tests/onnxruntime/ds_configs/ds_config_zero_stage_1.json, tests/onnxruntime/ds_configs/ds_config_zero_stage_inifinity.json
Add deepspeed configuration for upcoming tests:
* Stage 1
* NVMe supports
=> Add deepspeed configuration for upcoming tests

optimum/onnxruntime/modeling_ort.py
Fixes the correct docstring sample
=> [fix] Documentation: Sse correct docstring sample for ORTModelForCausalLM

optimum/onnx/configuration.py
=> Add keywords for arguments in `OnnxConfig` wrappers

.github/workflows/build_pr_documentation.yml
Optimum equavlent of https://github.com/huggingface/doc-builder/pull/214
if [build dev doc](https://github.com/huggingface/optimum/runs/6569992218?check_suite_focus=true) succeeds, it may fix docbuild error on https://github.com/huggingface/optimum/pull/199
=> Update PR docs to use `doc-builder push`

examples/onnxruntime/training/question-answering/README.md, examples/onnxruntime/training/text-classification/README.md, examples/onnxruntime/training/token-classification/README.md, examples/onnxruntime/training/translation/README.md
links in examples was broken. this fixes them
@JingyaHuang
=> fix install links for examples

optimum/onnxruntime/trainer.py
`deespeed_reinit` has been removed from `transformers.deespeed` (see this [PR](https://github.com/huggingface/transformers/pull/17151)). This PR updates `ORTTrainer` with these changes.
=> Remove deepspeed_reinit

README.md, docs/source/quickstart.mdx, examples/onnxruntime/quantization/multiple-choice/run_swag.py, examples/onnxruntime/quantization/question-answering/run_qa.py, examples/onnxruntime/quantization/text-classification/run_glue.py, examples/onnxruntime/quantization/token-classification/run_ner.py, optimum/onnxruntime/runs/__init__.py
This should fix notably some errors in examples after https://github.com/huggingface/optimum/pull/226 .
@regisss
=> Replace `quantizer.tokenizer` by `quantizer.preprocessor` everywhere

.github/workflows/build_documentation.yml
Fixes YAML formatting of doc build proposed in #239
=> Fix GH actions YAML

.github/workflows/build_documentation.yml
This PR fixes a problem for setting the env variable for the doc version - hopefully the last fix needed :)
=> Fix env variable setting for doc build

examples/onnxruntime/training/docker/Dockerfile-ort1.11.0-cu102, optimum/onnxruntime/trainer.py, optimum/onnxruntime/trainer_seq2seq.py
* Update `ORTTrainer` with transformers.Trainer v4.20.1 since 4.16.0
* Update `ORTSeq2SeqTrainer` with transformers.Trainer v4.20.1 since 4.16.0
=> [ORT] Update `ORTTrainer` with transformers 4.20.1

optimum/onnxruntime/utils.py
Adds support for CodeGen in ORTOptimizer
=> add codegen support for ort optimizer

optimum/fx/optimization/transformations.py
- Fixes the way the reverse composition is performed
=> Fix compose for computing the reverse composition

optimum/fx/optimization/transformations.py, tests/fx/optimization/test_transformations.py
- Adds a `signature` property to the `Transformation` class, allowing to identify transformations
- Adds a node marking system, allowing to check whether a node was transformed by a given transformation or not (using the transformation signature)
=> FX Transformation signature

optimum/onnxruntime/modeling_ort.py
This PR fixes the documentation for ORTModelForImageClassification.
=> Fix documentation for ORTModelForImageClassification

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml, docs/README.md
Adds support to build the Graphcore documentation. 
Before merging:
=> Add Graphcore and Intel documentation

examples/onnxruntime/training/docker/Dockerfile-ort-nightly-cu113, examples/onnxruntime/training/docker/Dockerfile-ort1.11.1-cu113, examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu113, examples/onnxruntime/training/docker/run.sh, examples/onnxruntime/training/language-modeling/run_clm.py
Update clm example as fp16 training for GPT-2 is fixed and ORT fused adam optimizer integrated in optimum.
=> Update clm example for ORTTrainer

docs/source/fx/optimization.mdx, optimum/fx/optimization/__init__.py, optimum/fx/optimization/transformations.py, tests/fx/optimization/test_transformations.py
- Adds a transformation that fuses the weight and the bias in linear modules
=> FuseBiasInLinear transformation

.github/workflows/test_benckmark.yml
=> Remove transformers main in benchmark test

docs/combine_docs.py
Fixes a bug where building documentation fails because of subsections (for instance [here](https://github.com/huggingface/optimum-habana/blob/main/docs/source/_toctree.yml) where sections are not all at the same level). [This](https://github.com/huggingface/optimum/runs/7645249951?check_suite_focus=true) is an example where this bug occurred.
More precisely, in [`docs/combine_docs.py`](https://github.com/huggingface/optimum/blob/main/docs/combine_docs.py), local files are renamed to add a prefix corresponding to the associated subpackage:
```python
for item in subpackage_toc:
for file in item["sections"]:
file["local"] = f"{subpackage}_" + file["local"]
```
This will fail when `item["sections"]` contains another `"section"` key because the `"local"` key will then be inside the second …
=> Fix bug in docs/combine_docs.py when there are subsections

optimum/onnxruntime/modeling_ort.py
=> Fix typo in variable name

.github/workflows/build_main_documentation.yml
Adds a way to trigger the action through a dispatch
=> Add documentation dispatch

optimum/onnxruntime/optimization.py
Fixes #361 
Fixes `AutoConfig` that was not imported in `onnxruntime/optimization.py`
=> fix(optimization): AutoConfig is not Imported

docs/source/onnxruntime/optimization.mdx, docs/source/onnxruntime/quantization.mdx
Fix wrong model class in documentation
=> Fix documentation

setup.py
This PR adds a `habana-deepspeed` extra to `setup.py` to install Optimum Habana with DeepSpeed.
**It should not be merged before the next release of Optimum Habana.**
=> Add habana-deepspeed extra to setup.py

optimum/configuration_utils.py
In this PR we fix https://github.com/huggingface/optimum/issues/344 by adapting `BaseConfig` in preview of transformers release v4.22.0
=> Adapt BaseConfig for next transformers release

examples/onnxruntime/training/docker/Dockerfile-ort-nightly-cu113, examples/onnxruntime/training/docker/Dockerfile-ort1.11.0-cu102, examples/onnxruntime/training/docker/Dockerfile-ort1.11.1-cu113, examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu113, examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu115, examples/onnxruntime/training/docker/Dockerfile-ort1.9.0-cu102, examples/onnxruntime/training/docker/Dockerfile-ort1.9.0-cu111, examples/onnxruntime/training/docker/run.sh
Move some dependencies from `run.sh` to dockerfiles.
=> Update dockerfiles for ORT training

optimum/fx/optimization/transformations.py
The `torch.fx` transformations now use the marking methods `mark_as_transformed`, `mark_as_restored`, `get_transformed_nodes` instead of manual (artisanal) implementation,
=> FX transformations now use marking methods

docs/README.md, docs/source/fx/optimization.mdx, docs/source/index.mdx, docs/source/pipelines.mdx
Signed-off-by: Ryan Russell <git@ryanrussell.org>
small readability touch ups in `.md*` files
=> docs: `md` readability fixups

optimum/onnxruntime/utils.py, tests/onnxruntime/test_optimization.py
Add support for marian models to apply `ORTOptimizer`. 
Fixes #392
=> Add marian optimizer support

optimum/fx/optimization/transformations.py, optimum/fx/quantization/functions.py
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Readability fixups in `optimum/fx/`
This updates a couple of docstrings.
`implemement` -> `implement`
`operaetors` -> `operators`
=> docs: `fx` readability fixups

optimum/onnxruntime/modeling_ort.py
=> Add default export feature for ORTModelForCustomTasks

.github/workflows/test_onnxruntime_train.yml, optimum/onnxruntime/trainer.py, optimum/onnxruntime/trainer_seq2seq.py, tests/onnxruntime/nightly_test_trainer.py
* Update `ORTTrainer` to be compatible with transformers 4.24.0
* Update CI to onnxruntime 1.13.0 CUDA 11.6
* Fix training test (seq2seq, xsum metric)
=> Fix ORT training test & update

docs/combine_docs.py, docs/source/_redirects.yml
This PR uses https://github.com/huggingface/moon-landing/pull/4324 to redirect old documentation links to the new ones following https://github.com/huggingface/optimum/pull/429.
=> Redirect old documentation links

optimum/onnxruntime/modeling_seq2seq.py
- Update `self.device` when sending the model. -> #365
=> Fix seq2seq model device update

.github/workflows/test_onnxruntime_gpu.yml
Will merge it right away.
See e.g. https://github.com/huggingface/optimum/actions/runs/3434693610/jobs/5726266315
=> Add python alias on ec2 instance for gpu tests

.github/workflows/test_onnxruntime_gpu.yml
=> Fix python call for gpu EC2 test

docs/source/bettertransformer/tutorials/contribute.mdx
Fixes a small nit on the BT documentation
cc @fxmarty @michaelbenayoun
=> [BT] Fix doc nit

tests/bettertransformer/test_bettertransformer_vision.py
FIxes a small nit on Vision models test
cc @fxmarty
=> [BT] Change variable name in Vision Test

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml
=> Fix doc build

.github/workflows/build_main_documentation.yml
Follow up to https://github.com/huggingface/optimum/pull/477
=> Doc build hotfix

docs/source/_toctree.yml, docs/source/exporters/onnx/overview.mdx, docs/source/exporters/onnx/package_reference/configuration.mdx, docs/source/exporters/onnx/package_reference/export.mdx, docs/source/exporters/onnx/usage_guides/contribute.mdx, docs/source/exporters/onnx/usage_guides/export_a_model.mdx, docs/source/exporters/overview.mdx, docs/source/exporters/task_manager.mdx, docs/source/utils/dummy_input_generators.mdx, docs/source/utils/normalized_config.mdx, optimum/exporters/__init__.py, optimum/exporters/onnx/__init__.py, optimum/exporters/onnx/__main__.py, optimum/exporters/onnx/base.py, optimum/exporters/onnx/config.py, optimum/exporters/onnx/convert.py, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, optimum/utils/__init__.py, optimum/utils/input_generators.py, optimum/utils/normalized_config.py, tests/onnxruntime/test_optimization.py
- Adds the documentation for `optimum.exporters`
- Adds missing docstrings
- Refactors some utility functions
=> Documentation for optimum.exporters

docs/source/onnxruntime/usage_guides/gpu.mdx
Add documentation for IOBinding on the GPU guide.
=> Add doc for IOBinding

tests/onnxruntime/test_modeling.py
=> Fix whisper device for gpu test

setup.py
See https://github.com/huggingface/transformers/commit/37e016331f6fee7a6b8c430057c08129da48c97f and the corresponding slack thread
=> Fix tensorflow CI

docs/source/bettertransformer/overview.mdx
Let's merge directly once the doc test passes.
=> Fix broken links in the doc

optimum/onnxruntime/modeling_seq2seq.py
Update iobinding foR `ORTEncoderForWhisper`. Add `contiguous` for `input_features` input.
=> Update iobinding ORT encoder whisper

optimum/utils/normalized_config.py
The error message displayed was incomplete. With this addition, the user is reminded that by setting allow_new=True, a new attribute can be added.
=> fix NormalizedConfig init error message

docs/source/bettertransformer/tutorials/contribute.mdx
Fixes https://github.com/huggingface/optimum/issues/518
=> [BT] Fix doc bugs

optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, tests/exporters/test_onnx_export.py
As per title. It's a model where a robust test during the export is needed.
In a next PR we should make the tests for exporters faster on PRs and main.
=> Add Swin support in exporters.onnx

docs/source/onnxruntime/package_reference/modeling_ort.mdx
As per title.
Reorder the classes as well.
=> Add OrtModelForSpeechSeq2Seq to doc

optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_seq2seq.py, optimum/utils/__init__.py
This PR adds a `check_if_transformers_greater` method in order to factorize the checks that are carried out in some source files.
=> Add check_if_transformers_greater to manage different versions of transformers

optimum/exporters/onnx/__main__.py
Fixes https://github.com/huggingface/optimum/issues/552#issuecomment-1340641025
=> Fix import in ONNX export CLI

docs/source/bettertransformer/overview.mdx, optimum/bettertransformer/models/__init__.py, optimum/bettertransformer/models/base.py, optimum/bettertransformer/models/encoder_models.py, optimum/bettertransformer/transformation.py, optimum/utils/testing_utils.py, tests/bettertransformer/test_bettertransformer_vision.py, tests/bettertransformer/testing_bettertransformer_utils.py
The support is only for the vision model, as the text model uses causal attention that is likely not supported by PyTorch Better Transformer.
=> Add CLIP BetterTransformer

tests/bettertransformer/test_bettertransformer_encoder.py, tests/bettertransformer/testing_bettertransformer_utils.py
Fixes https://github.com/huggingface/optimum/pull/542#issuecomment-1341205518
=> Fix flaky BetterTransformer test

docs/source/quicktour.mdx
Update the documentation following changes in #550
=> Update documentation quick tour section

optimum/utils/testing_utils.py, tests/bettertransformer/test_bettertransformer_encoder.py, tests/bettertransformer/test_bettertransformer_vision.py, tests/onnxruntime/test_modeling.py, tests/utils/test_dummpy_input_generators.py
As per title.
Could have helped identify https://github.com/huggingface/optimum/issues/572 https://github.com/huggingface/optimum/issues/569
=> More robust tests for ORTModel using decoders and use_cache=True

optimum/exporters/onnx/__main__.py, optimum/exporters/tasks.py, tests/exporters/exporters_utils.py, tests/exporters/test_exporters_onnx_cli.py, tests/exporters/test_onnx_export.py
This PR fixes the tests that were failing in exporters.onnx following the new tests added.
=> Fix exporters.onnx tests

docs/source/onnxruntime/usage_guides/models.mdx, docs/source/onnxruntime/usage_guides/optimization.mdx, docs/source/onnxruntime/usage_guides/pipelines.mdx, docs/source/onnxruntime/usage_guides/quantization.mdx, optimum/bettertransformer/transformation.py, optimum/modeling_base.py, optimum/onnxruntime/modeling_ort.py, optimum/pipelines.py, optimum/utils/file_utils.py
- Updates the `pipelines` with the ONNX Runtime accelerator to make them easier to use.
- Updates the pipeline with ONNX Runtime documentation guide 
- Updates the modeling with ONNX Runtime documentation guide
- Updates the graph optimization with ONNX Runtime documentation guide
=> Update on the ONNX Runtime documentation

optimum/version.py
=> Update dev version

tests/onnxruntime/test_modeling.py
=> Fix ORT GPU test

docs/source/utils/normalized_config.mdx, optimum/utils/normalized_config.py
Related: https://github.com/huggingface/optimum/issues/618
=> Add GPT-J normalized config

optimum/fx/optimization/transformations.py
=> fixed FuseBiasInLinear by specifying device

docs/source/onnxruntime/usage_guides/gpu.mdx
Fixes #580
Added a note for the user to initialise HF Pipelines with device parameter which is required for GPU Execution.
=> Fixed GPU documentation for HF pipelines

optimum/version.py
=> Update dev version following the patch release

docs/source/exporters/onnx/package_reference/configuration.mdx, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, optimum/utils/normalized_config.py, tests/exporters/exporters_utils.py
This PR tries to add ```PoolFormer``` models for ONNX support
=> Add PoolFormer support in exporters.onnx

optimum/onnxruntime/optimization.py
Fixes #649. The `disable_shape_inference` field of the optimization configuration should be taken into account when calling `convert_flot_to_fp16` while optimizing a model.
=> Fix disable shape inference for optimization

docs/source/exporters/onnx/package_reference/configuration.mdx, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, optimum/utils/normalized_config.py, tests/exporters/exporters_utils.py
=> Support pegasus exporters

docs/source/exporters/onnx/overview.mdx, docs/source/exporters/onnx/usage_guides/export_a_model.mdx, docs/source/quicktour.mdx
Document `--for-ort` and `--task XXX-with-past`.
Fixes https://github.com/huggingface/optimum/issues/640
=> Improve documentation around ONNX export

optimum/utils/normalized_config.py
For bloom, blenderbot, blenderbot-small.
=> Add missing normalized configs

optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_seq2seq.py
As per title.
Fixes https://github.com/huggingface/optimum/issues/658
=> Remove code duplication in ORTModel's load_model

optimum/exporters/onnx/__main__.py
Saves the model configuration, feature extractor and scheduler when exporting a stable diffusion model to ONNX using the CLI
=> Add saving of diffusion model additional components for onnx export

docs/source/exporters/onnx/usage_guides/export_a_model.mdx, optimum/commands/export/onnx.py, optimum/exporters/onnx/__main__.py, optimum/modeling_base.py, optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_ort.py, optimum/onnxruntime/modeling_seq2seq.py, tests/exporters/test_exporters_onnx_cli.py, tests/onnxruntime/test_modeling.py
As per title.
Fixes https://github.com/huggingface/optimum/issues/693
=> Support trust remote code option in ONNX export and ONNX Runtime integration

optimum/exporters/tasks.py
=> Fix exception condition

docs/source/onnxruntime/package_reference/modeling_ort.mdx
=> Add ORTModelForMultipleChoice to the documentation

optimum/onnxruntime/__init__.py
=> Allow `from optimum.onnxruntime import QuantizationConfig`

docs/source/bettertransformer/tutorials/contribute.mdx, docs/source/exporters/onnx/usage_guides/contribute.mdx, docs/source/exporters/onnx/usage_guides/export_a_model.mdx, docs/source/exporters/task_manager.mdx, docs/source/onnxruntime/quickstart.mdx, docs/source/onnxruntime/usage_guides/gpu.mdx, docs/source/onnxruntime/usage_guides/models.mdx, docs/source/onnxruntime/usage_guides/optimization.mdx, docs/source/onnxruntime/usage_guides/pipelines.mdx, docs/source/onnxruntime/usage_guides/quantization.mdx, docs/source/quicktour.mdx, docs/source/torch_fx/usage_guides/optimization.mdx, optimum/exporters/tasks.py, optimum/fx/optimization/transformations.py, optimum/fx/quantization/functions.py, optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_ort.py, optimum/onnxruntime/modeling_seq2seq.py
As per title, this goes along https://github.com/huggingface/optimum/pull/704.
Catching a few code snippets failing along the way.
=> Fix documentation for doctest tests to pass

setup.py
=> Use transformers>=4.26.0 in setup.py

docs/source/onnxruntime/usage_guides/trainer.mdx, examples/onnxruntime/training/docker/Dockerfile-ort-nightly-cu116, examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu113, examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu115, examples/onnxruntime/training/docker/Dockerfile-ort1.13.1-cu116, examples/onnxruntime/training/docker/run.sh
* Refactoring of docker files
* Update Trainer doc
=> Update docker and doc of ORT Trainer

docs/source/_redirects.yml
This PR redirects some links of the Optimum Habana's documentation following https://github.com/huggingface/optimum-habana/pull/147.
=> Add some redirections to Optimum Habana's documentation

optimum/exporters/onnx/model_configs.py
As per title, fixes https://github.com/huggingface/optimum/issues/740
=> Remove dead code in whisper ONNX output

optimum/bettertransformer/transformation.py, optimum/utils/testing_utils.py, tests/bettertransformer/test_bettertransformer_encoder.py, tests/bettertransformer/test_integration.py, tests/bettertransformer/testing_bettertransformer_utils.py
As requested in https://github.com/huggingface/transformers/pull/21259#discussion_r1084146743
=> Raise error on double call to `BetterTransformer.transform()`

.github/workflows/test_bettertransformer_gpu.yml, .github/workflows/test_onnxruntime_train.yml, tests/bettertransformer/Dockerfile_bettertransformer_gpu, tests/bettertransformer/test_bettertransformer_encoder.py
As requested in https://github.com/huggingface/transformers/pull/21259#issuecomment-1418938913
=> Add GPU tests for BetterTransformer

.github/workflows/doctests.yml
Fix `the input device is not a TTY` in https://github.com/huggingface/optimum/actions/runs/4094339189/jobs/7060478797
=> Fix doctest

optimum/onnxruntime/io_binding/io_binding_helper.py, tests/onnxruntime/Dockerfile_onnxruntime_gpu, tests/onnxruntime/test_modeling.py
The GPU tests were failing again: https://github.com/huggingface/optimum/actions/runs/4111377893/jobs/7095115898
We should add a slackbot just as transformers and accelerate to catch those.
=> Fix GPU tests

tests/onnxruntime/Dockerfile_onnxruntime_gpu, tests/onnxruntime/test_modeling.py
=> Fix flaky ONNX Runtime generation test with past key value reuse

.github/workflows/test_export_onnx.yml, .github/workflows/test_export_onnx_cli.yml, .github/workflows/test_exporters_slow.yml, optimum/exporters/onnx/convert.py, optimum/utils/__init__.py, optimum/utils/import_utils.py, setup.py, tests/exporters/onnx/test_onnx_config_loss.py, tests/exporters/onnx/test_onnx_export.py
As per title, as `tf2onnx` has not updated yet.
=> Pin numpy only for tensorflow export

optimum/onnxruntime/modeling_ort.py, pyproject.toml, tests/onnxruntime/test_modeling.py
As per title.
Fixes https://old.reddit.com/r/MachineLearning/comments/113m1ly/d_huggingface_considered_harmful_to_the_community/j8r6o9x/
=> Accept numpy.ndarray as input and output to ORTModel

tests/onnxruntime/test_optimization.py
As per title. Add more tests for seq2seq model along the way.
=> Test ORTOptimizer with IO Binding

examples/onnxruntime/training/image-classification/run_image_classification.py, examples/onnxruntime/training/language-modeling/run_clm.py, examples/onnxruntime/training/text-classification/run_glue.py, examples/onnxruntime/training/token-classification/run_ner.py, optimum/configuration_utils.py, optimum/exporters/onnx/utils.py, optimum/fx/optimization/transformations.py, optimum/onnxruntime/base.py, optimum/onnxruntime/optimization.py, pyproject.toml, tests/bettertransformer/test_bettertransformer_encoder.py, tests/exporters/common/test_tasks_manager.py, tests/exporters/onnx/test_onnx_config_loss.py
This PR adds an option to auto-format list/dict comprehension with `ruff` as it is now done in Transformers: https://github.com/huggingface/transformers/pull/21694 and https://github.com/huggingface/transformers/commit/ee6e71e29cbe8c6df45dd42993c345001788ed9d.
=> Update rules for ruff

docs/source/bettertransformer/overview.mdx, optimum/bettertransformer/models/__init__.py, tests/bettertransformer/test_bettertransformer_encoder.py
=> added BetterTransformer support for Marian

.github/workflows/test_onnxruntime_gpu.yml, .github/workflows/test_onnxruntime_train.yml
=> All back workflow dispatch on GPU tests

optimum/onnxruntime/runs/__init__.py, optimum/pipelines.py, tests/bettertransformer/test_integration.py
Fixes the padding error that appears in _bettertransformer_ pipeline if onnxruntime is not installed.
Fixes #809
=> BetterTransformer pipeline padding issue fix

tests/exporters/Dockerfile_exporters_gpu, tests/exporters/exporters_utils.py, tests/exporters/onnx/test_exporters_onnx_cli.py, tests/exporters/onnx/test_onnx_export.py
Some remaining failing tests, simply due to the CI here.
=> Fix failing GPU tests

.github/workflows/test_onnxruntime.yml, examples/onnxruntime/training/test_examples.py, optimum/exporters/tflite/config.py, optimum/onnxruntime/modeling_seq2seq.py, optimum/pipelines.py, tests/onnxruntime/test_modeling.py
Fixing a slight bug in https://github.com/huggingface/optimum/pull/824
=> Fix pipeline task dropping arguments bug

optimum/onnxruntime/quantization.py
As discussed offline @echarlaix . Not that calling `ORTQuantizer.from_pretrained()` was already failing if the ORTModelForCausalLM was instanciated and with two ONNX.
Tests are missing but I think it is OK to not add them now.
=> Fix ORTQuantizer behavior with ORTModelForCausalLM

optimum/exporters/onnx/config.py, optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_ort.py, tests/onnxruntime/test_modeling.py
As per title and discussed internally.
=> Keep intermediary models for ONNX causal-lm

optimum/exporters/__init__.py, optimum/exporters/onnx/__init__.py
=> Apply lazy import for exporters

docs/source/_toctree.yml, docs/source/exporters/tflite/overview.mdx, docs/source/exporters/tflite/usage_guides/export_a_model.mdx
This PR fixes one section title in the documentation.
=> Fix typo in documentation

optimum/bettertransformer/models/base.py, optimum/bettertransformer/transformation.py, tests/bettertransformer/test_bettertransformer_audio.py, tests/bettertransformer/test_bettertransformer_encoder.py, tests/bettertransformer/test_bettertransformer_vision.py, tests/bettertransformer/testing_bettertransformer_utils.py
Fixes https://github.com/huggingface/optimum/issues/847
cc @younesbelkada as discussed offline
=> Disable reverse BetterTransformer

optimum/onnxruntime/modeling_ort.py, tests/onnxruntime/test_modeling.py
Remove iobinding for ORTModelForCTC as not supported
=> Remove iobinding ORTModelForCTC

optimum/bettertransformer/transformation.py
Fixes https://github.com/huggingface/optimum/pull/853#issuecomment-1457970677
=> Fix pytorch version check in bettertransformer

optimum/bettertransformer/models/__init__.py, optimum/bettertransformer/models/decoder_models.py, optimum/bettertransformer/transformation.py, tests/bettertransformer/test_common.py, tests/bettertransformer/test_decoder.py, tests/bettertransformer/test_encoder.py, tests/bettertransformer/test_encoder_decoder.py, tests/bettertransformer/testing_utils.py
=> Bart support scaled_dot_product_attention

pyproject.toml, tests/bettertransformer/test_encoder.py
as per title for a more convenient way of running accelerate only tests
cc @fxmarty
=> [`BT`] add `accelerate_test` markers

optimum/bettertransformer/models/__init__.py, optimum/bettertransformer/transformation.py, tests/bettertransformer/test_encoder_decoder.py, tests/bettertransformer/testing_utils.py
Most probably wav2vec2, whisper, hubert would support as well, but I'll leave it to an other PR once we have benchmarked with what we already have.
=> Mbart, pegasus, blenderbot, marian, m2m_100 support scaled_dot_product_attention

optimum/exporters/onnx/base.py, optimum/exporters/onnx/model_configs.py
As reported in: https://github.com/microsoft/onnxruntime/issues/14865#issuecomment-1460668587
=> Fix causal-lm ONNX axis names

optimum/bettertransformer/models/base.py, optimum/bettertransformer/models/decoder_models.py, optimum/bettertransformer/models/encoder_models.py, optimum/bettertransformer/transformation.py, optimum/utils/__init__.py, optimum/utils/modeling_utils.py, optimum/utils/testing_utils.py, tests/bettertransformer/test_audio.py, tests/bettertransformer/test_common.py, tests/bettertransformer/test_decoder.py, tests/bettertransformer/test_encoder.py, tests/bettertransformer/test_encoder_decoder.py, tests/bettertransformer/test_vision.py, tests/bettertransformer/testing_utils.py
Should be good now.
Wav2vec2 and Hubert can not be loaded on meta device due to a bug in PyTorch.
=> Add bettertransformer reverse transform

tests/benchmark/benchmark_bettertransformer_training.py, tests/benchmark/benchmark_bettertransformer_training_minimal.py, tests/benchmark/better_transformer_training_minimal.py
cc @younesbelkada 
Run with: `CUDA_VISIBLE_DEVICES=1 python benchmark_bettertransformer_training.py --use-cuda --model-name gpt2 --num-epochs 1 --use-half`
=> Add bettertransformer training benchmark script

optimum/exporters/onnx/base.py, optimum/utils/import_utils.py
=> Remove onnx and ort dependencies on the TasksManager

optimum/exporters/onnx/base.py, optimum/exporters/onnx/convert.py, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py
This one is broken, let's merge once transformers 4.27 is released to fix.
Fixes https://github.com/huggingface/optimum/issues/882
=> Fix ONNX export on transformers 4.27 release

optimum/exporters/tasks.py
=> Fix stable diffusion framework detection

optimum/exporters/onnx/base.py, optimum/utils/__init__.py, optimum/utils/input_generators.py
previous dummy label generator only support text tasks.
=> Fix dummy label generator for vision tasks

examples/onnxruntime/training/image-classification/run_image_classification.py
Adds option to run inference with ort for run_image_classification in official optimum example
=> add option to run inference with ort

optimum/exporters/onnx/__main__.py
Bug introduced in https://github.com/huggingface/optimum/pull/897 as well
=> Fix onnx export preprocessors save

README.md
=> Remove GC from README

optimum/utils/testing_utils.py
It adds a user and the associated token to tests Optimum on the Hub.
=> Add user and token for CI

optimum/bettertransformer/models/attention.py, optimum/bettertransformer/transformation.py, tests/benchmark/benchmark_bettertransformer.py, tests/benchmark/benchmark_bettertransformer_training_minimal.py
We split the original model and bettertransformer benchmarks in two steps to avoid OOM issues.
=> Improve bettertransformer benchmark script

optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_ort.py, optimum/onnxruntime/modeling_seq2seq.py, optimum/onnxruntime/utils.py
As it is not tested and does not work: https://github.com/huggingface/optimum/blob/main/tests/onnxruntime/test_modeling.py#L2326-L2331
Better to catch the issue ahead of time with an understandable error.
We should support this case and change the test.
=> Raise error with use_cache=False, use_io_binding=True

optimum/exporters/tasks.py, tests/exporters/onnx/test_exporters_onnx_cli.py
We'll need yet a patch for this one, not good.
=> Fix auto-task detection in TasksManager

optimum/onnx/graph_transformations.py, setup.py
Use 2000000000 as onnx (for some reason) instead of 2147483648.
Fixes https://github.com/huggingface/optimum/issues/894
=> Fix protobuf max allowed size

optimum/exporters/tasks.py, tests/exporters/onnx/test_exporters_onnx_cli.py
As per title, fixes https://github.com/huggingface/optimum/issues/991
=> Fix sentence-similarity task in TasksManager

optimum/exporters/tasks.py
Decoupling from https://github.com/huggingface/optimum/pull/995
Edit: actually not a simplification, but reduces bug chances
=> Simplify auto task detection

optimum/bettertransformer/models/__init__.py, optimum/bettertransformer/models/attention.py, optimum/bettertransformer/models/decoder_models.py, optimum/bettertransformer/transformation.py, tests/bettertransformer/test_decoder.py, tests/bettertransformer/testing_utils.py
As per title, let me benchmark a bit. Fixes https://github.com/huggingface/optimum/issues/956
=> Support llama bettertransformer

optimum/onnxruntime/base.py
Fixes https://github.com/huggingface/optimum/issues/1005
=> Fix merged decoder usage with fp16

optimum/exporters/onnx/__main__.py
=> Fix typo for custom shapes passed at ONNX export

.github/workflows/build_main_documentation.yml
This PR fixes an issue where the file `_versions.yml` is not updated in the `build_main_documentation` workflow for new releases.
This issue comes from the fact that the file `_versions.yml` is downloaded in `build_dir/optimum` (see [here](https://github.com/huggingface/optimum/blob/ccf4b4dbb6d5f4421551ed0d83e0eb07b0261257/.github/workflows/build_main_documentation.yml#L74)) while the doc is generated in `optimum/optimum-doc-build/optimum` (see [here](https://github.com/huggingface/optimum/blob/ccf4b4dbb6d5f4421551ed0d83e0eb07b0261257/.github/workflows/build_main_documentation.yml#L101)) and that's when the version file is updated if it exists (see [here](https://github.com/huggingface/doc-builder/blob/3f6a2fd4c0e88be4ef55d74930b2517f50cf24cb/src/doc_builder/commands/build.py#L111)). …
=> Fix _versions.yml upload in doc build

optimum/onnxruntime/quantization.py, tests/onnxruntime/test_quantization.py
As requested. I verified on a large model that it works well and mode size is reduced.
=> ORTQuantizer supports subgraphs

setup.py
=> Update setup.py to add optimum-neuron extras

optimum/exporters/tasks.py
=> Sentence transformers ONNX export fix

optimum/exporters/onnx/__main__.py, optimum/exporters/tasks.py
=> Fix task inference for sam

setup.py
This PR adds the constraint `transformers<4.29.0` in the Habana extra.
=> Add "transformers<4.29.0" in Habana extra

optimum/utils/input_generators.py, tests/exporters/exporters_utils.py, tests/exporters/onnx/test_exporters_onnx_cli.py, tests/exporters/onnx/test_onnx_export.py
=> ONNX SAM export - change `input_points` data type

.github/workflows/test_cli.yml, optimum/commands/export/tflite.py, tests/cli/test_cli.py
`optimum-cli export tflite ...` currently fails with the following error message:
```
File "/home/regis/HuggingFace/dev/venv/bin/optimum-cli", line 8, in <module>
sys.exit(main())
File "/home/regis/HuggingFace/dev/venv/lib/python3.8/site-packages/optimum/commands/optimum_cli.py", line 162, in main
service = args.func(args)
File "/home/regis/HuggingFace/dev/venv/lib/python3.8/site-packages/optimum/commands/base.py", line 90, in defaults_factory
return self.__class__(
TypeError: __init__() got multiple values for argument 'parser'
```
The class `TFLiteExportCommand` should be updated following #940.
This PR also adds a test so that `optimum-cli export tflite ...` is tested.
=> Fix CLI for TFLite export

optimum/exporters/onnx/convert.py
=> Raise MinimumVersionError when OnnxConfig.MIN_TORCH_VERSION is not satisfied

optimum/exporters/onnx/__main__.py, optimum/onnxruntime/optimization.py
As per title, fixes https://github.com/huggingface/optimum/issues/901 & make https://github.com/microsoft/onnxruntime/pull/15067 usable
=> Fix float16 ORT conversion for models > 2GB

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml, .github/workflows/delete_doc_comment.yml, .github/workflows/delete_doc_comment_trigger.yml
Following https://github.com/huggingface/doc-builder/pull/379.
=> Update doc workflows

docs/source/exporters/onnx/overview.mdx, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, tests/exporters/exporters_utils.py
Add onnx exporter for Lilt model.
Partial issue fix of https://github.com/huggingface/optimum/issues/1024.
=> Add onnx exporter for Lilt model

optimum/commands/onnxruntime/quantize.py, optimum/onnxruntime/quantization.py
As per title, fixes https://github.com/huggingface/optimum/issues/1090
=> Error out on `ORTQuantizer.quantize` call for static quantization when no calibration range is provided

optimum/exporters/onnx/convert.py
=> Run validation of exported model in no_grad mode

optimum/exporters/onnx/__main__.py, optimum/exporters/tasks.py
Significantly reduces load time, especially for large models
=> Load model directly on cuda device for the ONNX export

optimum/exporters/onnx/__main__.py, optimum/exporters/onnx/base.py, optimum/exporters/onnx/config.py, optimum/exporters/onnx/convert.py, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, tests/exporters/exporters_utils.py
Fixes https://github.com/huggingface/optimum/issues/1086
Fixes as well a bug in the ONNX export validation where gradients would be computed for the PyTorch model.
edit: actually moved the gradient bug to https://github.com/huggingface/optimum/pull/1111 to have it merged right away
=> Support document-question-answering ONNX export for vision-encoder-decoder

optimum/onnxruntime/utils.py, tests/onnxruntime/test_optimization.py
=> Add ViT to ORTConfigManager

docs/source/bettertransformer/overview.mdx, docs/source/bettertransformer/tutorials/convert.mdx
Minor typos in docs; add link to BetterTransformer guideline docs
=> Small typos

optimum/bettertransformer/models/__init__.py
Refactoring of methods to make them less ugly ;)
=> Refactor BetterTransformerManager requirement validation methods

examples/onnxruntime/training/language-modeling/run_clm.py
Set the default `block_size = model_max_length`.
=> update the default block size

optimum/commands/__init__.py, optimum/commands/onnxruntime/__init__.py, optimum/commands/onnxruntime/base.py, optimum/commands/onnxruntime/optimize.py, optimum/commands/onnxruntime/quantize.py
Fix some typos of ONNXRuntimme to ONNXRuntime
=> Fix typos of ONNXRuntimme -> ONNXRuntime

optimum/onnxruntime/base.py
Fixes https://github.com/huggingface/optimum/issues/1158
=> Fix encoder attention mask input order for ORT

optimum/onnxruntime/modeling_ort.py, optimum/onnxruntime/utils.py, tests/onnxruntime/test_utils.py
Fixes https://github.com/huggingface/optimum/issues/1156
=> Fix ORTModel initialization on specific device id

.github/workflows/test_onnx.yml, setup.py
Let's see if the CI passes @regisss
=> Unpin tensorflow

docs/source/bettertransformer/overview.mdx
Following https://github.com/huggingface/optimum/pull/1125
=> Add BLIP-2 to BetterTransformer documentation

docs/source/onnxruntime/usage_guides/quantization.mdx
=> Fix broken link in doc

optimum/bettertransformer/models/attention.py, tests/bettertransformer/test_decoder.py
=> Fix BT test

setup.py
=> Update setup.py to add optimum-furiosa extras

optimum/exporters/tasks.py
Fix ONNX export of SD model with safetensors weights such as [`stable-diffusion-xl-base-1.0`](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0)
=> fix SD loading when safetensors weights only

setup.py
Fixes https://github.com/huggingface/optimum/issues/1237
=> Update onnxruntime minimum version to 1.11

optimum/bettertransformer/models/attention.py, tests/bettertransformer/testing_utils.py
=> Support Llama 2 in BetterTransformer.

docs/source/bettertransformer/overview.mdx, optimum/bettertransformer/models/__init__.py, optimum/bettertransformer/models/encoder_models.py, optimum/bettertransformer/transformation.py, optimum/onnxruntime/trainer.py, tests/bettertransformer/test_encoder.py, tests/bettertransformer/test_encoder_decoder.py
=> Drop mask for training in all cases for BetterTransformer & precise documentation

optimum/bettertransformer/models/attention.py
As per title, see the comment in the PR & https://github.com/pytorch/pytorch/issues/95210
=> SDPA dispatches to flash for MQA

.github/ISSUE_TEMPLATE/bug-report.yml
=> Update bug report template

optimum/onnxruntime/base.py
It was not properly detected up to now.
=> Fix fp16 ONNX detection for decoder models

optimum/version.py
=> Update version following 1.11.2 patch

tests/benchmark/README.md, tests/benchmark/benchmark_gptq.py, tests/benchmark/memory_tracker.py
As per title, still need to add results.
=> Add AutoGPTQ benchmark

tests/test_configuration_utils.py
Some more tests failing following 4.32 release.
=> Fix staging tests following transformers 4.32 release

optimum/bettertransformer/models/__init__.py, optimum/bettertransformer/models/attention.py, optimum/bettertransformer/models/decoder_models.py, optimum/bettertransformer/transformation.py, optimum/utils/import_utils.py
As per title. This can be used as well for future code patching of transformers.
Fixes https://github.com/huggingface/optimum/issues/1176
=> Improve BetterTransformer backward compatibility

tests/benchmark/README.md, tests/benchmark/benchmark_gptq.py
=> Add bitsandbytes benchmark

optimum/onnx/transformations_utils.py, tests/benchmark/benchmark_gptq.py
This PR fixes a minor typo in a logging message, replacing `Addind` with `Adding`.
=> fix typo in log message

tests/benchmark/benchmark_bettertransformer.py
As per title, among others avoid running sweep when not requested.
=> Fix BT benchmark script

optimum/onnx/graph_transformations.py, optimum/onnx/transformations_utils.py, setup.py, tests/exporters/onnx/test_exporters_onnx_cli.py, tests/onnxruntime/test_quantization.py
As per title. It is unclear why the CI is green (https://github.com/huggingface/optimum/actions/runs/6050752962/job/16420709454) although there was still this bug cc @xenova
=> Fix initializer detection for weight deduplication

optimum/version.py
As per title. Next is fixing failing TFLite tests due to the added sentence-transformers test.
=> Update version to 1.14.0.dev0

.github/workflows/test_export_tflite.yml, .github/workflows/test_export_tflite_cli.yml, .github/workflows/test_export_tflite_cli_dynamic_quantization_int8.yml, .github/workflows/test_export_tflite_cli_quantization_fp16.yml, .github/workflows/test_export_tflite_cli_quantization_full_int8.yml, .github/workflows/test_export_tflite_cli_quantization_int8_custom_dataset.yml, .github/workflows/test_export_tflite_cli_quantization_int8_default_dataset.yml, .github/workflows/test_export_tflite_cli_quantization_int8x16.yml, tests/exporters/tflite/test_exporters_tflite_cli.py, tests/exporters/tflite/test_tflite_export.py
As per title and discussed offline @michaelbenayoun
=> Fix tests collection for TFLite export and trigger TFLite tests only when relevant

optimum/gptq/quantizer.py
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>
=> feat: add support for loading quantisation from config.json

docs/source/exporters/onnx/package_reference/configuration.mdx
=> Fix docbuild

optimum/onnxruntime/utils.py
As per title, disable it as explained in https://github.com/huggingface/optimum/issues/1402
=> Fix provider availability check on ORT 1.16.0 release

tests/onnxruntime/docker/Dockerfile_onnxruntime_gpu
failing test :  https://github.com/huggingface/optimum/actions/runs/6250963114/job/16971088458
=> Fix  ONNX Runtime Dockerfile

optimum/onnxruntime/modeling_diffusion.py
=> Ignore .xml files for Stable Diffusion ORT downloads

optimum/exporters/tasks.py
Fixes https://github.com/huggingface/optimum/issues/1414
=> Fix owlvit task detection

optimum/bettertransformer/models/encoder_models.py
=> Fix typo in BetterTransformer CLIP

docs/source/llm_quantization/usage_guides/quantization.mdx, optimum/gptq/quantizer.py, tests/gptq/test_quantization.py
=> default to exllama when exllamav2 is disabled

optimum/gptq/quantizer.py, optimum/utils/import_utils.py
Refer: https://github.com/PanQiWei/AutoGPTQ/pull/385
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>
=> Add support for CPU Inference

optimum/utils/import_utils.py
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/391
=> Fix minimum version of auto-gptq

setup.py
Transformers v4.35, which will be released soon, is currently not supported by Optimum Habana.
=> Update Transformers dependency for Habana extra

optimum/bettertransformer/models/attention.py, optimum/bettertransformer/models/base.py, tests/bettertransformer/test_decoder.py
As per title, still some tests failing (notably `test_save_load_invertible`).
We may at some point deprecate some of the BT implementations following https://github.com/huggingface/transformers/pull/26572
=> Fix BT on transformers 4.35 release

optimum/exporters/onnx/model_configs.py, optimum/utils/input_generators.py
Fixes https://github.com/huggingface/optimum/issues/1522
=> Fix whisper v3 ONNX export

optimum/exporters/onnx/model_patcher.py
=> Fix model patcher ONNX decoder export

.github/workflows/build_main_documentation.yml
=> Add Optimum-amd documentation to the PR & release doc

docs/source/index.mdx
Add nvidia to the documentation
=> optimum-nvidia

docs/source/index.mdx, docs/source/onnxruntime/usage_guides/amdgpu.mdx
Replacing IPU with NPU for AMD Ryzen
=> Update doc for AMD

README.md
=> Use doc links in the README for subpackages

.github/workflows/test_export_onnx_cli_timm.yml, tests/exporters/onnx/test_exporters_onnx_cli.py
=> Run timm ONNX CI only once per day

optimum/bettertransformer/transformation.py, tests/bettertransformer/test_audio.py
As per title, will do a patch.
=> Show correct error message on using BT for SDPA models

optimum/exporters/onnx/model_configs.py
Fixes https://github.com/huggingface/optimum/issues/1621#issuecomment-1874598197
=> Bump sentence-transformers ONNX opset

optimum/onnxruntime/utils.py, optimum/utils/import_utils.py
Fixes https://github.com/huggingface/optimum/issues/1619
Tested on colab CPU, it is now working.
=> Fix cupy detection

optimum/utils/import_utils.py
cc @regisss, bug introduced in https://github.com/huggingface/optimum/pull/1635
=> Fix ORT detection

optimum/exporters/onnx/utils.py
Enable sdpa export for pytorch v2.1.0 or higher
=> Enable sdpa export for SD unet component

optimum/bettertransformer/transformation.py
Attempt to improve the error message to clarify that 'optimum' is not required for certain model types.
Fixes this (closed) transformers [issue](https://github.com/huggingface/transformers/issues/28330).
=> Improve error message

optimum/exporters/onnx/convert.py, setup.py
As done in transformers https://github.com/huggingface/transformers/pull/28207 (also fixes an import error as `is_torch_less_than_1_11` has been removed in #28207)
=> Bump min torch version

optimum/gptq/data.py
This PR fixes the loading of c4 dataset. This happens beacause the "allenai--c4" configuration doesn't exist for this dataset (it's a legacy scheme from old versions of the datasets library). See related [thread](https://huggingface.co/datasets/allenai/c4/discussions/7) here. The modification should still work for older version of datasets too.
=> Fix c4 dataset loading

optimum/exporters/onnx/base.py
=> Avoid loading onnx file in weight deduplication if not necessary

optimum/exporters/onnx/__main__.py, optimum/exporters/onnx/model_configs.py
As per title, addresses https://github.com/huggingface/optimum/issues/1633#issuecomment-1893483420
=> Allow lower ONNX opsets

setup.py
=> Add rjieba install

docs/source/exporters/onnx/overview.mdx, optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, optimum/utils/normalized_config.py, tests/exporters/exporters_utils.py, tests/onnxruntime/utils_onnxruntime_tests.py
Needed for https://github.com/xenova/transformers.js/issues/475
=> Add ONNX export for table-transformer

optimum/commands/export/onnx.py, optimum/exporters/onnx/__main__.py, optimum/exporters/onnx/convert.py, tests/onnxruntime/test_modeling.py
=> Add option to disable ONNX constant folding

optimum/exporters/tasks.py
Adds support for export of https://huggingface.co/nomic-ai/nomic-embed-text-v1. Tested and uploaded the resulting files to the repo [here](https://huggingface.co/nomic-ai/nomic-embed-text-v1/tree/main/onnx).
=> Pass `trust_remote_code` to sentence transformers export

setup.py
As per title, needed for the soon-to-be-released v1.10.2 of Optimum Habana that supports Transformers v4.37 but will not be compatible with v4.38.
=> Update Transformers dependency in Habana extra

optimum/version.py
As per title, following v1.17 release.
=> Bump dev version

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml
This is blocking for the release.
=> Skip graphcore docbuilding

examples/onnxruntime/training/image-classification/README.md, examples/onnxruntime/training/image-classification/run_image_classification.py
Updates image classification example script to reflect latest addition of `--label_column_name` and `--image_column_name` data parameters.
Requested Reviewer(s): @JingyaHuang
=> update image classification example

optimum/onnxruntime/training_args.py
Fixes [# 1705](https://github.com/huggingface/optimum/issues/1705)
=> Add handle for empty fsdp_config[xla_fsdp_v2]

examples/onnxruntime/training/image-classification/run_image_classification.py
This PR fixes the import statements for ORTTrainer and ORTTrainingArguments in the Image Classification example.
Requested Reviewer(s): @regisss @JingyaHuang
=> Image Classification Example Bug Fix

optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, optimum/onnxruntime/modeling_ort.py, tests/onnxruntime/test_modeling.py
Partially fixes https://github.com/huggingface/optimum/issues/1672
=> Whisper ONNX audio-classification

optimum/onnxruntime/trainer.py
See issue description in #1723 
It's caused by transformers PR https://github.com/huggingface/transformers/commit/4f09d0fd888dbf2660313f9715992822acfb99ce
Follow the same changes in ORTTrainer
=> Follow grad_norm changes in transformers #27326

.github/workflows/test_onnx.yml
Fix https://github.com/huggingface/optimum/actions/workflows/test_onnx.yml (see https://github.com/huggingface/optimum/actions/runs/8330008937)
=> Fix ONNX tests tensorflow version

docs/source/exporters/onnx/overview.mdx, optimum/exporters/onnx/model_configs.py, optimum/exporters/onnx/utils.py, optimum/exporters/tasks.py, optimum/onnxruntime/modeling_decoder.py, optimum/utils/normalized_config.py, tests/exporters/exporters_utils.py, tests/onnxruntime/test_modeling.py, tests/onnxruntime/utils_onnxruntime_tests.py
This submission enables optimum to support the qwen2 family model and support onnxruntime export of related models. The onnx code related to this model has been verified.
Qwen1.5 is the beta version of Qwen2, a transformer-based decoder-only language model pretrained on a large amount of data. In comparison with the previous released Qwen, the improvements include:
6 model sizes, including 0.5B, 1.8B, 4B, 7B, 14B, and 72B;
Significant performance improvement in Chat models;
Multilingual support of both base and chat models;
Stable support of 32K context length for models of all sizes
No need of trust_remote_code.
For more details, please refer to our [blog post](https://qwenlm.github.io/blog/qwen1.5/) and [GitHub repo](https://github.com/QwenLM/Qwen1.5).
=> Support qwen2 family model (qwen1.5)

setup.py
Fix Exporters ONNX / Python - Test https://github.com/huggingface/optimum/actions/runs/8355790029/job/22871571606 now https://github.com/huggingface/optimum/actions/runs/8392478292/job/22985214444
issue since https://github.com/huggingface/transformers/commit/415e9a0980b00ef230d850bff7ecf0021c52640d
=> Fix ONNX export for tf models

optimum/exporters/onnx/base.py, optimum/exporters/tasks.py
Remove "image-feature-extraction" task added in https://github.com/huggingface/optimum/pull/1726/files and set it as a synonym of "feature-extraction" 
fix : https://github.com/huggingface/optimum/actions/workflows/test_export_tflite_cli.yml
=> Fix tflite export

tests/exporters/exporters_utils.py
model was removed from `hf-internal-testing` https://huggingface.co/hf-internal-testing/tiny-random-PhiForCausalLM
=> Update test model id

README.md
Add Nvidia and AWS Neuron to our Optimum doc:
* @mfuntowicz please confirm the installation of Optimum Nvidia is accurate
* cc. @michaelbenayoun and @dacorvo for the Neuron part
=> Add Nvidia and Neuron to README

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml, docs/combine_docs.py, docs/source/_redirects.yml, docs/source/index.mdx
Add the Google TPU button to the documentation
=> Add Google TPU to the mix

docs/source/_redirects.yml
See https://huggingface.slack.com/archives/C06GAFTA5AN/p1712593418110649?thread_ts=1712576681.519389&cid=C06GAFTA5AN
=> Add redirection for Optimum TPU

docs/source/installation.mdx
=> Add Nvidia and Neuron to the installation doc

optimum/version.py
=> Update dev version to 1.20.0.dev0

setup.py
Will do a patch release to include latest transformers version cc @regisss @JingyaHuang @michaelbenayoun does that work for you ?
=> Bump transformers version

.github/workflows/build_main_documentation.yml
Fixes the current error in the main doc build workflow:
```
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1610 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main …
```
=> Remove call to `apt update` before `apt purge` in the main doc build workflow

.github/workflows/build_main_documentation.yml
See https://github.com/huggingface/optimum/actions/runs/8814386505/job/24194120535#step:15:475 .
=> Remove bad PPA in main doc build workflow

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml
Needs to give an index to pip.
=> Fix TPU doc build

setup.py
=> Update the Transformers dependency in the Habana extra

optimum/utils/normalized_config.py
=> Expand support

docs/source/onnxruntime/usage_guides/amdgpu.mdx
=> Update ORT doc for ROCM 6.0

.github/workflows/trufflehog.yml
Adding a GH action to scan for leaked secrets on each commit.
=> feat(ci): add trufflehog secrets detector

optimum/gptq/data.py, tests/gptq/test_quantization.py
=> Remove dataset with restrictive license

docs/source/_redirects.yml
Following https://github.com/huggingface/optimum-intel/pull/765
=> Add redirection for optimum intel doc

setup.py
=> Fix code quality

setup.py
To be in sync with optimum-habana.
=> Update Habana extra

tests/exporters/exporters_utils.py, tests/onnxruntime/test_modeling.py, tests/onnxruntime/utils_onnxruntime_tests.py
Needs transformers>4.42.3 to include https://github.com/huggingface/transformers/pull/31755
=> Add export test for swin with shifted windows

optimum/exporters/onnx/model_patcher.py
Fixes https://github.com/huggingface/optimum/issues/1952
=> Fix unmask_unattended_patched signature

docs/source/concept_guides/quantization.mdx
Fixed 3 typos
Fixes documentation typos
@fxmarty, @SunMarc
=> Fix typos in quantization.mdx

setup.py
Needed for the new release of Optimum Habana (v1.13.0) where the Transformers dependency is upgraded.
=> Update Habana extra in setup.py

setup.py
=> Fix TFLite tests

docs/source/bettertransformer/overview.mdx
=> Fix typo in BetterTransformer's overview docs

.github/workflows/test_fx_automatic_parallel.yml
=> CI - update runner type

optimum/exporters/onnx/convert.py, tests/exporters/onnx/test_exporters_onnx_cli.py
Following https://github.com/huggingface/optimum/pull/2053
=> fix onnx export for transformers>=4.45

.github/workflows/test_bettertransformer.yml, .github/workflows/test_onnx.yml
Fix :
https://github.com/huggingface/optimum/actions/runs/11290608247/job/31402830526
https://github.com/huggingface/optimum/actions/runs/11290608260/job/31402830356
=> Upgrade macOS image for tests compatibility with numpy v2

.github/workflows/build_main_documentation.yml
This PR fixes an issue when uninstalling packages: https://github.com/huggingface/optimum/actions/runs/11294092310/job/31413744411#step:10:249
=> Fix main doc build

.github/workflows/build_main_documentation.yml
=> Enter venv before pushing doc in main doc build workflow

.github/workflows/test_fx_automatic_parallel.yml
=> Remove unused HF_TOKEN environment variable

optimum/onnxruntime/modeling_diffusion.py
Following https://github.com/huggingface/optimum-intel/pull/952
=> Fix compatibility with diffusers < 0.25.0

setup.py
Update the `habana` extra to be compatible with Transformers v4.45. Needed for the release of Optimum Habana v1.14.
=> Update the habana extra

docs/source/onnxruntime/usage_guides/models.mdx
cc @regisss  who suggested this addition :fire:
=> Add sentence-transformers and timm documentation example

optimum/subpackages.py, setup.py
=> Skip optimum-benchmark when loading namespace modules

.github/workflows/build_pr_documentation.yml
See https://github.com/huggingface/doc-builder/pull/541.
=> Fix PR doc upload

README.md
Following https://github.com/huggingface/optimum/pull/2024/files#r1933925612
Can be merged after the release
=> Update ort training installation instructions

optimum/exporters/onnx/utils.py
Fixes a type on in the file causing KeyError in the format.
=> Fix typo in exporters/onnx/utils.py

.github/workflows/test_onnxruntime.yml, optimum/exporters/onnx/model_patcher.py, optimum/onnxruntime/modeling_diffusion.py, tests/onnx/test_onnx_graph_transformations.py, tests/onnxruntime/test_modeling.py
=> Fix diffusers

docs/source/onnxruntime/usage_guides/gpu.mdx
Updates the docs for TRT engine following https://github.com/huggingface/optimum/issues/1395
=> TRT engine docs

optimum/configuration_utils.py, optimum/exporters/onnx/__main__.py, optimum/exporters/tasks.py, optimum/fx/parallelization/distributed/dist_ops.py, optimum/fx/parallelization/utils.py, optimum/modeling_base.py, optimum/onnxruntime/modeling_decoder.py, optimum/onnxruntime/modeling_diffusion.py, optimum/onnxruntime/modeling_ort.py, optimum/onnxruntime/modeling_seq2seq.py, optimum/utils/file_utils.py, optimum/utils/testing_utils.py, tests/onnx/test_onnx_graph_transformations.py, tests/onnxruntime/test_modeling.py, tests/test_configuration_utils.py
=> Always use a deafult user agent

optimum/exporters/onnx/model_configs.py, optimum/utils/save_utils.py
=> add loading image processor

optimum/exporters/onnx/model_patcher.py
=> Fix `CLIPSdpaAttention` had dropped since v4.48

optimum/exporters/tasks.py
This PR adds the token-classification task for the qwen2 model.
Fix Issue: https://github.com/huggingface/optimum/issues/2257
=> adding token classification task for qwen2

docs/source/index.mdx
"google TPUs" title section not displayed correctly in doc
https://huggingface.co/docs/optimum/v1.25.0/en/index
=> tpu section gradient top to right

optimum/onnxruntime/modeling_diffusion.py, optimum/onnxruntime/modeling_ort.py, tests/onnxruntime/test_modeling.py
returns tuple if not return_dict
=> Match transformers behavior with return_dict

optimum/pipelines/pipelines_base.py, tests/onnxruntime/test_modeling.py
Fix https://github.com/huggingface/optimum/issues/2273
=> Fix ORT pipeline

.github/workflows/build_main_documentation.yml, .github/workflows/build_pr_documentation.yml, docs/combine_docs.py, docs/source/_toctree.yml, docs/source/furiosa_overview.mdx
Main documentation build is currently failing coming from furiosa doc https://github.com/huggingface/optimum/actions/runs/15497191527/job/43636622455
Moving furiosa doc build in optimum-furiosa : https://github.com/huggingface/optimum-furiosa/pull/19
=> Furiosa documentation

optimum/exporters/onnx/model_configs.py, optimum/exporters/tasks.py, optimum/utils/__init__.py, optimum/utils/input_generators.py
To be able to move everything onnx/ort related in optimum-onnx
=> Add task onnx register

optimum/utils/input_generators.py
Add the necessary input names for VisualBERT to the `DummyVisionInputGenerator`.
=> Adding DummyInputGenerator for VisualBert

optimum/utils/input_generators.py
Reverts huggingface/optimum#2303 which break the optimum cli
=> Revert "Adding DummyInputGenerator for VisualBert"

optimum/commands/export/onnx.py, optimum/commands/export/tflite.py, optimum/utils/input_generators.py
Add dummy input generator for visualbert
=> add dummy input generator for VisualBert

.github/workflows/test_exporters_tflite.yml, .github/workflows/test_exporters_tflite_cli.yml, optimum/exporters/tflite/base.py
=> Fix tflite cli

optimum/utils/input_generators.py
To support minicpm4v
https://huggingface.co/openbmb/MiniCPM-V-4/blob/main/config.json#L19
=> [ONNX, OpenVINO]Update the dummy generator for Llama

optimum/commands/optimum_cli.py, setup.py
While adding support in optimum-intel I noticed that the parameter `submodule_search_locations` can contain the same path multiple times, resulting in the command being registered multiple times, this fixes it.
=> Fix register loop
