huggingface/optimum

- examples/pytorch/language-modeling/config/inc/quantization.yml
- examples/pytorch/language-modeling/run_clm.py
- examples/pytorch/language-modeling/run_mlm.py
- examples/pytorch/multiple-choice/config/inc/quantization.yml
- examples/pytorch/multiple-choice/run_swag.py
- examples/pytorch/question-answering/config/inc/quantization.yml
- examples/pytorch/question-answering/run_qa.py
- examples/pytorch/test_examples.py
- examples/pytorch/text-classification/config/inc/quantization.yml
- examples/pytorch/text-classification/run_glue.py
- examples/pytorch/token-classification/config/inc/quantization.yml
- examples/pytorch/token-classification/run_ner.py
- src/optimum/intel/neural_compressor/config.py
- tests/intel/test_inc.py
This PR adds a metric tolerance argument in order for the user to easily set an accepted drop in performance without having to directly change the config file. This PR also changes the test examples quantization approach from dynamic to static and furthermore reduce the number of evaluation and training examples of the INC quantization tests.
> Update examples test quantization approach from dynamic to static

- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/quantization.py
This PR adds supports for explicitly setting nodes to quantization/nodes to exclude while exporting models through the `ORTQuantizer`
> Added a few more quantization parameters required for qranium.

- examples/inc/pytorch/language-modeling/README.md
- examples/inc/pytorch/language-modeling/run_clm.py
- examples/inc/pytorch/language-modeling/run_mlm.py
- examples/inc/pytorch/multiple-choice/README.md
- examples/inc/pytorch/multiple-choice/run_swag.py
- examples/inc/pytorch/question-answering/README.md
- examples/inc/pytorch/question-answering/run_qa.py
- examples/inc/pytorch/text-classification/README.md
- examples/inc/pytorch/text-classification/run_glue.py
- examples/inc/pytorch/token-classification/README.md
- examples/inc/pytorch/token-classification/run_ner.py
- optimum/intel/neural_compressor/quantization.py
- tests/intel/test_inc.py
In this PR we fix broken links in examples readme files, remove the sparsity computation in the examples scripts as the latter is incompatible with static and aware training quantization and change the default value of calibration dataloader to None when the quantization applied is different from static quantization.
> Fix broken links 

- examples/onnxruntime/pytorch/question-answering/run_qa.py
- examples/onnxruntime/pytorch/text-classification/run_glue.py
- examples/onnxruntime/pytorch/token-classification/run_ner.py
- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/quantization.py
In this PR we add the list of the types of operators to quantize `op_types_to_quantize` as argument to when applying an ONNX Runtime quantization. We also add the saving of the ORT configuration in the examples scripts.
> Add list of the types of operators to quantize to ORT quantization

- .github/workflows/build_documentation.yml
In #86 I built the docs with the `optimum` version number, but in general we'll want to have the docs reflect the state on the `main` branch. This PR does that and once we have integrated the rest of the API docs, we can revisit setting the version number with future releases.
cc @mishig25
> Use main branch as default "version" when building docs

- .github/workflows/build_dev_documentation.yml
- .github/workflows/build_documentation.yml
This PR attempts to fix a `module 'google.protobuf.descriptor' has no attribute '_internal_create_key'` error in the doc build on the `main` branch. According to [this SO answer](https://stackoverflow.com/questions/61922334/how-to-solve-attributeerror-module-google-protobuf-descriptor-has-no-attribu), the solution is to simply upgrade `protobuf`. 
This PR also re-instates the checks to auto-update the docs on changes to the PR. As this doesn't touch any other parts of the codebase, I'll do a merge once the CI passes.
cc @echarlaix
> Fix protobuf dependency in doc build

- examples/inc/pytorch/question-answering/run_qa.py
This PR fixed `ValueError: Got [n] predictions and [n+m] features` of `run_qa.py`.
If `training_args.dataloader_drop_last` was set, the length of predictions may not match features, due to dataset didn't reduce last batch.
> Fix qa data mismatch

- optimum/onnxruntime/model.py
In this PR, we fix the inputs of the onnx runtime inference session and only feed to the latter it if the desired inputs is present in the dataset
> Fix ORTModel inference session inputs

- examples/onnxruntime/training/token-classification/run_ner.py
- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/trainer_seq2seq.py
- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_onnxruntime_train.py
-  Fix `fix_atenops_to_gather` broken due to changed ops names.
-  Patch `Seq2SeqORTTrainer` to be compatible with `BART` model.
- Enable inference within PyTorch when ONNX Runtime doesn't work.
> [ORTTrainer] Fix to be compatible with onnxruntime 1.11.0

- optimum/onnxruntime/__init__.py
In this PR, we change the type of the elements of the list `ORT_FULLY_CONNECTED_OPERATORS` used as the default value of the `operators_to_quantize` parameter when instantiating an `QuantizationConfig` object by using `AutoQuantizationConfig`. The elements composing the list were previously `ORTQuantizableOperator` instances, which resulted in errors as the `ORTQuantizer` `partial_fit` methods expects a list of strings (which is also the case for `QuantizationConfig`).
> Change element type of list initializing the auto quantization config

- optimum/onnxruntime/preprocessors/passes/excluders.py
- optimum/onnxruntime/preprocessors/passes/fully_connected.py
- optimum/onnxruntime/preprocessors/passes/gelu.py
- optimum/onnxruntime/preprocessors/passes/layernorm.py
- optimum/onnxruntime/preprocessors/quantization.py
In this PR, we add the `IncludeFullyConnectedNodes` class, which allows to find the nodes composing the model's fully connected layers, in order to include those to the list of nodes to quantize. We also force the intersection of the two sets respectively representing the nodes to quantize `global_nodes_to_quantize` an the nodes to exclude `global_nodes_to_exclude` to be an empty set, in order to prevent any overlap.
> Add quantization preprocess to include fully connected layer nodes

- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_onnx.py
This PR adds a transformation on ONNX models that scans for weights that are shared (or exact duplicates) and prunes all the redundancy. The resulting model ends up smaller, and the computation remains unchanged.
This can be useful for models such as Albert.
> ONNX weight sharing

- optimum/onnx/configuration.py
Segment the `generate_dummy_inputs()` method into two cases: PyTorch / TensorFlow for clarity.
> Segment generate dummy inputs to smaller cases

- .github/workflows/build_documentation.yml
This PR fixes a small bug by including a `v` prefix to the generated builds in the `doc-build` repo: https://github.com/huggingface/doc-build/tree/main/optimum
> Fix version number shown in doc build

- optimum/onnxruntime/quantization.py
In `optimum/onnxruntime/quantization.py`, we currently have:
```python
LOGGER.info(
f"Creating {'dynamic' if quantization_config.is_static else 'static'} quantizer: {quantization_config}"
)
```
'dynamic' and 'static' should be swapped.
> Fix logging mistake where "dynamic" is logged if static quantization is performed

- examples/onnxruntime/quantization/question-answering/run_qa.py
- examples/onnxruntime/quantization/text-classification/run_glue.py
- examples/onnxruntime/quantization/token-classification/run_ner.py
- optimum/onnxruntime/preprocessors/quantization.py
- optimum/onnxruntime/quantization.py
Currently, for the onnxruntime backend, the [`QuantizationPreprocessor`](https://github.com/huggingface/optimum/blob/3b522e4d82c765660d7f60839d65ad7eda208f58/optimum/onnxruntime/preprocessors/quantization.py#L36) is usable only for static quantization to exclude nodes to quantize, because the onnx model needs to be already saved when initializing `QuantizationPreprocessor`, which was handled by [`partial_fit`](https://github.com/huggingface/optimum/blob/3b522e4d82c765660d7f60839d65ad7eda208f58/optimum/onnxruntime/quantization.py#L237) method used during calibration.
With this PR, it is possible to use `QuantizationPreprocessor` for dynamic quantization (if it happens to be relevant at some point -- at least I would like to test it), while making no change to the current workflow.
- …
> Allow onnxruntime quantization preprocessor for dynamic quantization

- setup.py
Bump `huggingface_hub` version to be able to use evaluate
> Bump `huggingface_hub` version to be able to use `evaluate` & `protobuf` fix

- docs/source/_toctree.yml
- docs/source/benchmark.mdx
- optimum/utils/__init__.py
- optimum/utils/doc.py
- optimum/utils/runs.py
- setup.py
Remove the previous pydantic dependency for the benchmark code. This PR allows to generate the documentation without additional dependencies.
> Remove pydantic for benchmarks & use dataclass instead

- .github/workflows/build_documentation.yml
- .github/workflows/build_pr_documentation.yml
- setup.py
Install the dependencies on `optuna` and `tqdm` before generating the documentation (necessary for the benchmark part). For some reason the action `build_pr_documentation` passed (see https://github.com/huggingface/optimum/actions/runs/2455809780 or this PR dev doc), but the `build_documentation` fails because of missing dependencies still (760a7e6e4aba963feefd1fae86fa8590d1200ada).
> Fix documentation dependency

- optimum/onnxruntime/modeling_ort.py
- tests/onnxruntime/test_modeling_ort.py
Currently when you load a locally saved optimized/quantized model (different file name than `model.onnx`) with `from_pretrained` it will correctly load but is not saving the "file" name for saving the model in a later state. Currently it always defaults to `model.onnx`. 
Reproduce:
```python
model = ORTModelForSequenceClassification.from_pretrained(onnx_path,file_name="model-quantized.onnx")
print(model.latest_model_name)
model.save_pretrained(tmp_store_directory)
```
Current workaround is to set `model.latest_model_name` to `file_name` after loading.
> [Fix] Local Load and save for ORTModel for optimized/quantized models

- docs/source/onnxruntime/modeling_ort.mdx
- docs/source/pipelines.mdx
- optimum/onnxruntime/__init__.py
- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/optimization.py
- optimum/onnxruntime/quantization.py
- optimum/onnxruntime/runs/utils.py
- optimum/pipelines.py
- setup.py
- tests/onnxruntime/test_modeling_ort.py
- tests/onnxruntime/test_onnxruntime.py
Fixes #173. This PR enables:
- to use an image-classification pipeline
- to perform quantization/optimization with computer vision models
At the moment, static post-training quantization with percentile/entropy calibration may not work with some models due to an issue with ONNX Runtime.
> Add support for image classification

- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_onnxruntime.py
* Register DeBERTa-V2 in `ORTConfigManager`.
* Add to the test.
Fixes #207
> Add ORTOptimizer DeBERTa-V2 models support

- .github/workflows/build_documentation.yml
This PR attempts to fix a problem with the way the docs are versioned with every push to `main` vs from a release branch.
I thought `doc-builder` would automatically build the `main` docs when the `--version` flag contained a `.dev0` suffix, but this turns out to be incorrect.
The current fix checks if `.dev0` exists in the version and then sets the appropriate flag in `doc-builder`
cc @fxmarty @mishig25
> Fix doc versions

- setup.py
Updates the transformers version in the required packages in setup.py
This [PR](https://github.com/huggingface/optimum/pull/226) (#226) imports the ImageClassifierOutput function from modeling_outputs.py from transformers, but the ImageClassifierOutput function was only added to transformers in versions 4.18.0 and above.
> updated transformers version in required packages

- optimum/runs_base.py
- optimum/utils/runs.py
`__post_init__()` of parent `Run` class did not run in `RunConfig`. Also, a parameter was missing in the run returned body.
> Correct bug in benchmarks post_init

- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/optimization.py
- tests/onnxruntime/test_optimization.py
This PR adds support for converting model weights from `fp32` to `fp16` by adding a new Optimization parameter. If the `fp16` arg is provided in the `OptimizationConfig` the weights are converted. I also added a test to make sure the model is not containing any fp32 weights
> Adding support for float16 conversion for GPUs

- examples/onnxruntime/training/language-modeling/run_mlm.py
- examples/onnxruntime/training/question-answering/run_qa.py
- examples/onnxruntime/training/text-classification/run_glue.py
- examples/onnxruntime/training/token-classification/run_ner.py
- examples/onnxruntime/training/translation/run_translation.py
- optimum/onnxruntime/__init__.py
- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/training_args.py
- optimum/onnxruntime/training_args_seq2seq.py
- tests/onnxruntime/nightly_test_trainer.py
* Integrate ort fused adam optimizer
* Subclass TrainingArguments to include ort optimizers
* Update training examples
* Add to the nightly test
-------------------------
__Who can review__
@zhijxu-MS @carzh
> Add ORT fused adam optimizer

- examples/onnxruntime/optimization/text-classification/run_glue.py
- examples/onnxruntime/optimization/token-classification/run_ner.py
- examples/onnxruntime/quantization/image-classification/run_image_classification.py
- examples/onnxruntime/quantization/text-classification/run_glue.py
- examples/onnxruntime/quantization/token-classification/run_ner.py
Fix a bug for certain text-classification models using a sentence pair input. 
In text classification, some models have different ids than the dataset label for the same label name. For example, in glue/mnli, the model `roberta-large-mnli` has
```
"label2id": {
"CONTRADICTION": 0,
"ENTAILMENT": 2,
"NEUTRAL": 1
},
```
while the dataset labels has the order `"label": {"num_classes": 3, "names": ["entailment", "neutral", "contradiction"]`, effectively swapping "contradiction" and "entailment" labels.
In transformers example, this is fixed using an additional piece of code, see https://github.com/huggingface/transformers/blob/d6b8e9cec7301ba02f642588a6f12e78ec3b9798/examples/pytorch/text-classification/run_glue.py#L395-L413 . This piece of code is missing in the optimization and quantization …
> Fix wrong mapping between dataset label ids and model.config.label2id in examples

- docs/source/_toctree.yml
- docs/source/modeling_base.mdx
- optimum/modeling_base.py
Add to the documentation `save_pretrained()` and `from_pretrained()` methods of `OptimizedModel`. I added it to a "Main classes" section, not sure if it is the best way to go, as e.g. the `ORTModelFor...` classes are in the ONNX Runtime --> Inference section. Was not sure how to go as well given that we want to merge the doc from subpackages (should we have a shared "Main classes" for all subpackages?).
If we prefer to have subclass-specific documentation (the one I wrote is too short I think, compare https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained), we could do in `ORTModel`:
```python
@classmethod
def from_pretrained(
cls,
model_id: Union[str, Path],
from_transformers: bool = False,
force_download: bool = True, …
```
> Add documentation of OptimizedModel methods

- optimum/fx/optimization/transformations.py
- Creates the merged linear on the same device as the previous individual linears, and with the same dtype. If the individual linears were on the different devices, the device of the first linear is used. The same thing is done if the dtypes are different.
- Inserts the new linear right before the first individual linear, instead of right after the input node. This is most of the time equivalent, except when some other transformation insert nodes in between.
> MergeLinears set proper device and dtype

- .github/workflows/test_fx.yml
- .github/workflows/test_onnx.yml
- .github/workflows/test_onnxruntime.yml
- .github/workflows/test_optimum_common.yml
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/nightly_test_trainer.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/test_optimization.py
The goal of this PR is to make the Onnxruntime tests much faster, as they usually run for more than 1 hour. 
To do that, this PR:
- Fuses multiple tests together in `tests/test_modeling.py`:
- `test_supported_transformers_architectures`, `test_model_call` are fused to `test_compare_to_transformers`
- `test_default_pipeline_and_model_device` is fused to `test_pipeline_ort_model`
- `test_generate_utils_with_input_ids` is fused to `test_generate_utils`
- Uses smaller model architectures to test, instead of big ones
> OnnxRuntime tests refactor to make them faster

- docs/source/onnxruntime/modeling_ort.mdx
- optimum/onnx/configuration.py
- optimum/onnxruntime/modeling_seq2seq.py
This PR allows more flexibility for ONNX Runtime inference of seq2seq models by removing assumption on the ONNX model input names
> Fix seq2seq onnx config

- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_optimization.py
This PR adds config for xlm-roberta based models to be used in ORTOptimizer.
(This is a duplicate PR of #312 due to the restructuring of the test)
Fixes #322
> Add support of xlm-roberta in config for ORTOptimizer

- .github/workflows/test_onnxruntime_train.yml
- examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu113
- examples/onnxruntime/training/docker/Dockerfile-ort1.12.0-cu115
- examples/onnxruntime/training/docker/run.sh
- tests/onnxruntime/nightly_test_trainer.py
* Update `torch==1.12.0 onnx==1.12.0` in ort-1.12.0-cu113
* Create ort-1.12.0-cu115 dockerfile
* Update run.sh (currently a bug of fairescale in transformers 4.21.0)
> Update train docker to onnxruntime-training 1.12.0

- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_optimization.py
This small PR adds config for big-bird based models to be used in ORTOptimizer.
> Add support of big-bird in config for ORTOptimizer 

- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
> allow string device input for OrtModel.to(device)

- optimum/fx/optimization/transformations.py
- Fixes the way linears are removed from their parent module when merging.
- Fixes the way linears are inserted back to the model when umerging.
> Fix the way the linear modules are removed from the parent module

- .github/workflows/build_pr_documentation.yml
- Makefile
- docs/Dockerfile
- docs/source/index.mdx
In the Docker image associated to the container building the doc, the repo is cloned but it points by default to the main branch. Thus, the doc generated for each PR is actually the doc of the main branch. This is fixed by checking out the commit associated to the PR when cloning the repo in the Dockerfile. See [here](https://github.com/huggingface/optimum-habana/pull/78) for more explanations.
If the PR comes from a fork, it also clone the right repo in the Docker container. This must also be done for Optimum Graphcore/Habana/Intel.
> Fix bug where the PR doc is actually the main doc

- optimum/modeling_base.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
We passed by default `force_download=True`, although the caching works well when passing `force_download=False`. Especially when passing `from_transformers=False`, everything works as expected as the onnx model is loaded from the cache `hub/` subfolder.
When passing `from_transformers=True`, although we cache only the PyTorch model (before [the new transformers cache system ](https://github.com/huggingface/transformers/pull/18438) in `transformers/` cache subfolder, in `hub/` subfolder in the next transformers release), the `force_download` argument is anyway ignored in `_from_transformers` so this PR has no impact there:
https://github.com/huggingface/optimum/blob/e90332463f7d2c1ae7e6feb93cfb379f92ed6231/optimum/onnxruntime/modeling_ort.py#L239-L303
> Do not force download by default in ORTModel

- optimum/onnxruntime/optimization.py
- optimum/onnxruntime/quantization.py
Fixes #364 
Optimize or quantize a model but the user does not want a suffix so the user tries to use :
`file_suffix=None` => RuntimeError (for optimization)
`file_suffix=""` => saved file name is like `encoder_model_.onnx`
Little logic to handle optional or empty file_suffix
The doc was already saying the parameter could be optional (even if not with the current code)
> fix(optimization): handle empty file suffix

- Makefile
This PR fixes #372 where the generation of the main documentation fails. This happens because the clone URL is only taken from the PR which triggered the workflow, and since the main documentation build workflow is not triggered by a PR no clone URL is given. The fix consists in checking if the clone URL is empty or not, and give it a default value if it is.
> Add default clone url for making doc

- setup.py
The extra "habana-deepspeed" has to be removed because `optimum-habana[deepspeed]` makes uploading `optimum-habana` on PyPI impossible since it does not accept direct dependencies specified as URLs like Habana Deepspeed. See https://github.com/huggingface/optimum-habana/pull/96.
> Remove extra "habana-deepspeed"

- examples/onnxruntime/optimization/text-classification/run_glue.py
- examples/onnxruntime/optimization/token-classification/run_ner.py
- examples/onnxruntime/quantization/image-classification/run_image_classification.py
- examples/onnxruntime/quantization/text-classification/run_glue.py
- examples/onnxruntime/quantization/token-classification/run_ner.py
- optimum/utils/preprocessing/image_classification.py
- optimum/utils/preprocessing/token_classification.py
Following https://github.com/huggingface/optimum/pull/197 , as per the title. For example 
```python
cfg = AutoConfig.from_pretrained("howey/bert-base-uncased-sst2")
print(cfg)
"""prints
BertConfig {
"_name_or_path": "howey/bert-base-uncased-sst2",
"architectures": [
"BertForSequenceClassification"
],
"attention_probs_dropout_prob": 0.1,
"classifier_dropout": null,
"finetuning_task": "sst2",
"gradient_checkpointing": false,
"hidden_act": "gelu",
"hidden_dropout_prob": 0.1,
"hidden_size": 768,
"initializer_range": 0.02,
"intermediate_size": 3072,
"layer_norm_eps": 1e-12,
"max_position_embeddings": 512,
"model_type": "bert",
"num_attention_heads": 12,
"num_hidden_layers": 12,
"pad_token_id": 0,
"position_embedding_type": "absolute",
"problem_type": "single_label_classification", …
```
> Raise warning in examples for classification tasks where the model's label mapping can not automatically match with the dataset labels

- optimum/onnxruntime/runs/__init__.py
- optimum/runs_base.py
- optimum/utils/preprocessing/image_classification.py
- optimum/utils/preprocessing/question_answering.py
- optimum/utils/preprocessing/text_classification.py
- optimum/utils/preprocessing/token_classification.py
- setup.py
- tests/benchmark/test_transformers_optimum_examples_parity.py
This is part of an effort on my end to simplify the benchmark scripts. As much of the logic of the evaluation using pipelines was moved to subclasses of Evaluator in evaluate, we make use of them following the 0.2.0 release, see https://huggingface.co/docs/evaluate/package_reference/evaluator_classes
In a following PR, we could make use of them in the example scripts as well.
PRs will follow after this one to:
* Have an option after a benchmark to save the model with config and results.
* Dissociate backends (do not run pytorch and onnxruntime at the same time).
* Have a tutorial in the documentation on how to use the benchmark scripts.
* Ideally, I would like to support at some points other backends than ONNX Runtime. This would involve building pipeline wrappers just like for …
> Use evaluators in the benchmark scripts

- optimum/modeling_base.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
`ORTModel.load_model` was not accepting custom session options, making it hard for example to use a given number of CPU cores with an `ORTModel` for inference. Indeed, onnxruntime obey neither `psutil.cpu_affinity` nor `taskset`.
This may close https://github.com/huggingface/optimum/issues/262
> Add InferenceSession options and Provider to ORTModel

- examples/onnxruntime/training/translation/run_translation.py
Signed-off-by: Ryan Russell <git@ryanrussell.org>
`sacreblue` -> `sacrebleu`
> docs: correct `sacrebleu` ref

- README.md
- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/trainer_seq2seq.py
* Update `ORTTrainer` and `ORTSeq2SeqTrainer` with transformers 4.22.1 release.
* Enable PyTorch’s Fully Sharded Data Parallel (FSDP) training feature in the trainers.
> Update ORTTrainer with transformers 4.22.1 release

- Makefile
- docs/Dockerfile
- docs/README.md
This should be merged after https://github.com/huggingface/doc-builder/pull/278 is accepted.
This PR fixes the broken documentation links in Optimum documentation as the structure is not `src/optimum/` but directly `optimum/` (see e.g. the broken links in https://huggingface.co/docs/optimum/main/en/onnxruntime/quantization#optimum.onnxruntime.ORTQuantizer ).
> Fix broken documentation links

- optimum/configuration_utils.py
- setup.py
- tests/test_configuration_utils.py
This PR updates the `BaseConfig` class to synchronize with the updates performed on the `transformers.PretrainedConfig`, and fixes the issue induced by the `transformers` 4.22 release, breaking the current `BaseConfig.push_to_hub` method.
> BaseConfig update for transformers>=4.22.0

- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
`InferenceSession` init can take the `provider_options` argument, that may set some custom parameters depending on the execution provider: see https://onnxruntime.ai/docs/api/python/api_summary.html#inferencesession & https://onnxruntime.ai/docs/api/c/group___global.html .
This is useful for example when using `TensorrtExecutionProvider`, we need to pass `{"trt_int8_enable": True}` to enable TensorRT INT8 precision, otherwise getting the error `Internal Error (Int8 precision has been set for a layer or layer output, but int8 is not configured in the builder)`.
> Add possibility to pass `provider_options` to `ORTModel.from_pretrained()`

- optimum/onnxruntime/quantization.py
Pass `AddQDQPairToWeight`, `DedicatedQDQPair`, `QDQOpTypePerChannelSupportToAxis` to `QDQQuantizer` or `ONNXQuantizer`, as those configuration attributes are available in `QuantizationConfig` but were not passed up to now.
This is useful if we later aim at using `TensorrtExecutionProvider` with a static quantized model.
> Use more extra quantization options of ONNX Runtime

- examples/onnxruntime/training/docker/run.sh
- examples/onnxruntime/training/language-modeling/run_clm.py
- examples/onnxruntime/training/language-modeling/run_mlm.py
- examples/onnxruntime/training/question-answering/run_qa.py
- examples/onnxruntime/training/summarization/run_summarization.py
- examples/onnxruntime/training/text-classification/run_glue.py
- examples/onnxruntime/training/token-classification/run_ner.py
- examples/onnxruntime/training/translation/run_translation.py
- optimum/onnxruntime/training_args.py
- tests/onnxruntime/nightly_test_trainer.py
Bugged after the recent change of log level in `transformers.TrainingArgs`: https://github.com/huggingface/transformers/pull/19239
* Fix by updating `ORTTrainingArguments`.
* CI will install transformers from source to track the possible breaking changes led by transformers' updates. 
* Add test for PyTorch DDP.
* Update training example minimal transformers version.
Fixes #418
> Fix ORT training args log level bug

- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/onnxruntime/utils.py
- tests/benchmark/test_transformers_optimum_examples_parity.py
- tests/onnxruntime/test_modeling.py
Support to pass a specific device id (e.g. as an int) for ORTModel, as transformers does for pipelines.
For example, `model.to(1)` will use the GPU with id 1.
Fixes #426
> Support specific device id for ORTModel

- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/quantization.py
This PR fixes a couple of errors that appeared with ORT 1.13.1:
- `disable_shape_inference` is added to `OptimizationConfig` since it has been added to `FusionOptions` in ORT (see https://github.com/microsoft/onnxruntime/pull/12215),
- replace `input_qType` by `activation_qType` in `quantization.py` since this argument name has changed in ORT (see https://github.com/microsoft/onnxruntime/pull/12873).
> Fixes for ORT 1.13.1

- docs/combine_docs.py
- docs/source/index.mdx
This PR changes the way the documentation of Optimum's subpackages is combined to the main doc. We currently add a prefix `subpackage_` at the beginning of each file but the code is not adapted to the new documentation structure (cf. #395).
The new logic consists in creating a new repository for each subpackage. Then, the structure of the subpackages' documentations are copied inside each one of these subpackage folders.
> Change the logic to combine subpackages' documentation

- examples/onnxruntime/optimization/question-answering/run_qa.py
- examples/onnxruntime/optimization/text-classification/run_glue.py
- examples/onnxruntime/optimization/token-classification/run_ner.py
- examples/onnxruntime/quantization/image-classification/run_image_classification.py
- examples/onnxruntime/quantization/question-answering/run_qa.py
- examples/onnxruntime/quantization/text-classification/run_glue.py
- examples/onnxruntime/quantization/token-classification/run_ner.py
- tests/onnxruntime/nightly_test_trainer.py
`datasets.load_metric` is deprecated, replace it everywhere with `evaluate.load`.
Fixes #350
> Replace dataset's load_metric by evaluate load

- optimum/modeling_base.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
Currently, ORTModel `config` attribute was loading the config key/items from a vanilla dict using `PretrainedConfig.from_dict()`. With this PR, we rather load the config with `AutoConfig.from_pretrained()` that allows to instanciate child classes from `PretrainedConfig`, e.g. `DistilBertConfig`, `XLMRobertaConfig`, etc.
The current way may have been intended, is it the case @philschmid ? Do you think this change is OK? With the current code, the key `model_type` was not saved in the `config.json` when using `save_pretrained`.
Fixes #402
> Use PretrainedConfig child classes for ORTModel config attribute

- docs/combine_docs.py
This PR generates a `{subpackage}_index.html` so that existing links to it still work. They currently don't work because of the doc overhaul (see #429).
> Add former subpackage_index.html

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/tasks.py
This PR enables automatic task detection for `optimum.exporters`.
> Exporters automatic task detection

- optimum/modeling_base.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
Allow to pass the argument `subfolder` to `ORTModel.from_pretrained()` in a similar fashion to transformers `PreTrainedModel`. It allows to host several models (e.g. optimized) in the same model repository.
The preprocessor is expected to be loaded from the parent directory.
Fixes #308
> Add Model loading from subfolders similar to transformers

- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
Fixes #404 
* Force tensors to be contiguous (otherwise might populate in the wrong address).
* Add bs>1 and beam search to test.
Kudos to @soocheolnoh for testing and catching the bug.
> Fix IOBinding population error when batch_size>1

- optimum/modeling_base.py
https://github.com/huggingface/optimum/pull/436 broke the error message when the specified model is neither on the Hub or a local path. We would only get `UnboundLocalError: local variable 'config' referenced before assignment`
This PR fixes the issue.
> Explicit error message when model not found for ORTModel

- optimum/onnxruntime/modeling_ort.py
There was no `optimum/gpt2`. An alternative could be to add `optimum/gpt2`, here the advantage is that if `gpt2` is already cached no need to redownload it.
Note that the modified docstring `TEXT_GENERATION_EXAMPLE` is used only once.
> Fix docstring example for ORTModelForCausalLM

- docs/source/onnxruntime/package_reference/configuration.mdx
- docs/source/onnxruntime/usage_guides/optimization.mdx
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/model_configs.py
- optimum/onnxruntime/__init__.py
- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/onnxruntime/optimization.py
- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_optimization.py
- Renames the attributes for the `OptimizationConfig`: 
- The previous naming was not very clear, because it was matching the naming from what was done in `onnxruntime` for instance `disable_attention` for disabling attention fusion.
- Make things clearer in terms of optimization tool by explicitly specifying which attributes tune the general purpose ONNX Runtime optimizer (compared to the other which are tuning the transformers specific optimizer).
- Adds an `AutoOptimizationConfig` class, with several optimization levels that cover the most common use cases, to make it easy to create an `OptimizationConfig` without having to dive in the ONNX Runtime ecosystem. 
- Uses `NormalizedConfig` when possible.
To be done:
> ORTOptimizer refactor

- optimum/onnxruntime/modeling_seq2seq.py
Add missing normalised config in the `ORTEncoder` class.
The issue leads to error in when exporting model using the `ORTModelForSeq2SeqLM` class.
> Added normalized config ORTEncoder

- docs/source/bettertransformer/overview.mdx
- optimum/bettertransformer/models/__init__.py
- optimum/bettertransformer/models/encoder_models.py
- optimum/bettertransformer/transformation.py
- tests/benchmark/benchmark_bettertransformer_vit.py
- tests/bettertransformer/test_bettertransformer_audio.py
- tests/bettertransformer/test_bettertransformer_encoder.py
- tests/bettertransformer/test_bettertransformer_vision.py
- tests/bettertransformer/testing_bettertransformer_utils.py
Adds `ViT` family to BetterTransformer integration
Adds also `Wav2vec2` family to BT integration
Replaces #469 
cc @fxmarty @michaelbenayoun
> `vit` + `wav2vec2` support

- docs/source/_toctree.yml
The "The Tasks Manager" section was not in the right place in the index.
> Re-order the task manager doc

- optimum/onnxruntime/__init__.py
With this PR, `from optimum.onnxruntime import ORTModel` imports from `modeling_ort.py`.
All examples use `from optimum.onnxruntime.model import ORTModel` so no need to modify them, and `ORTModel` was not used in the doc.
This is potentially breaking change.
> Change import structure for ORTModel

- .github/workflows/test_bettertransformer.yml
fixes the failing CI tests for BT
using `transformers==4.24.0` , the snippet:
```
import requests
from PIL import Image
from transformers import AutoFeatureExtractor
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
feature_extractor = AutoFeatureExtractor.from_pretrained("hf-internal-testing/tiny-random-ViTModel")
inputs = feature_extractor(images=image, return_tensors="pt")
```
fails
Using the main branch of `transformers` should fix the issue
cc @fxmarty
> [BT] Fix failing CI tests

- optimum/onnxruntime/modeling_seq2seq.py
key/value names is an attribute in init, no need to reuse if else.
> Remove redundant condition statement in ORTDecoder(Seq2seq)

- optimum/bettertransformer/transformation.py
This PR puts the decorator `check_if_pytorch_greater_112` in the correct place. In fact, putting the decorator above the definition of the class does not somehow activates the check
cc @michaelbenayoun @fxmarty
> [BT] put decorator on the correct place

- optimum/bettertransformer/models/base.py
- optimum/utils/__init__.py
This PR fixes a small nit, when users run `BetterTransformer` under some models that uses `norm_first` the error message is not clear. This PR adds a sanity check and a clear explanation of what a user should do in case they're using a BT model under PyTorch 1.12 that uses `norm_first` 
cc @fxmarty @michaelbenayoun
> [BT] clearer error message for `norm_first`

- docs/source/bettertransformer/overview.mdx
- optimum/bettertransformer/models/__init__.py
- optimum/bettertransformer/models/encoder_models.py
- tests/bettertransformer/test_bettertransformer_vision.py
Added BetterTransformer support for ViLT architecture. 
Added test model for ViltModel.
Tested the conversion of ViltLayer:
```
from optimum.bettertransformer import BetterTransformer
model = BetterTransformer.transform("hf-internal-testing/tiny-random-ViltModel")
print(model)
ViltModel(
(embeddings): ViltEmbeddings(
(text_embeddings): TextEmbeddings(
(word_embeddings): Embedding(1124, 32)
(position_embeddings): Embedding(512, 32)
(token_type_embeddings): Embedding(16, 32)
(LayerNorm): LayerNorm((32,), eps=1e-12, elementwise_affine=True)
(dropout): Dropout(p=0.1, inplace=False)
)
(patch_embeddings): ViltPatchEmbeddings(
(projection): Conv2d(3, 32, kernel_size=(2, 2), stride=(2, 2))
)
(token_type_embeddings): Embedding(2, 32)
(dropout): Dropout(p=0.1, inplace=False)
)
(encoder): …
```
> [BT] add `BetterTransformer` support for ViLT architecture

- optimum/bettertransformer/models/base.py
- optimum/bettertransformer/transformation.py
- optimum/utils/__init__.py
Fixes
```
terminate called after throwing an instance of 'c10::Error'
what():  Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
Exception raised from sizes_custom at ../aten/src/ATen/NestedTensorImpl.cpp:80 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f76e70c520e in /home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x60 (0x7f76e70a06a9 in /home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x17836a3 (0x7f769f3a56a3 in /home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packag …
```
> Deprecate PyTorch 1.12. for BetterTransformer

- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/onnxruntime/utils.py
- optimum/utils/__init__.py
This adds more precise error messages with guidance to the user when the ONNX Runtime configuration is badly installed for some execution provider (notably CUDA, Tensorrt).
Note the fuzzy stuff with tokenizers env variable to avoid the warnings https://github.com/huggingface/transformers/issues/5486 , not sure how to do it better.
I did not add tests as this would require to install / uninstall pip packages to run (or have several docker images, on for each case), not sure if I should? What do you think?
Note that there remains an issue: in case `onnxruntime-gpu` is indeed installed but the dependencies are not met, ONNX Runtime will show `CUDAExecutionProvider` and `TensorrtExecutionProvider` in `get_available_providers()` but initializing the inference session with them will fail …
> Clearer error messages when initilizing the requested ONNX Runtime execution provider fails

- examples/onnxruntime/training/docker/conda/requirements.yml
- examples/onnxruntime/training/docker/run.sh
- setup.cfg
- setup.py
The `sklearn` package on PyPI is an historical thing and will start failing from December 1st 2022, see https://github.com/scikit-learn/sklearn-pypi-package for more details.
I checked the first one as this seems the one more applicable here:
> Replace sklearn by scikit-learn

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- optimum/modeling_base.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/test_optimization.py
- Uses `optimum.exporters.onnx` to export transformers models in `ORTModel`
- Refactors / clean the API 
- Docstring
Fixes: #481
> ORTModel uses optimum.exporters.onnx

- .github/workflows/test_dummy_inputs.yml
- docs/source/exporters/onnx/package_reference/configuration.mdx
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/model_configs.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/onnxruntime/optimization.py
- optimum/onnxruntime/utils.py
- optimum/utils/__init__.py
- optimum/utils/doc.py
- optimum/utils/input_generators.py
- optimum/utils/normalized_config.py
- tests/utils/test_dummpy_input_generators.py
As per title, this is part of the effort to make ONNX export more reliable (reference https://github.com/huggingface/optimum/issues/503 )
Next PRs will come to:
* Allow custom shapes during `torch.onnx.export`
* More extensive testing of exported models with `optimum.exporters`
* Include log information in the ONNX export, some info on the supported/unsupported shapes / inputs
> Support custom shapes for dummy inputs

- docs/source/_toctree.yml
In the side-bar of the documentation of Optimum, all sections are currently unfolded (see [here](https://huggingface.co/docs/optimum/index)). This looks overwhelming and it would be clearer if main sections are folded.
With this PR, only the "Overview" section is unfolded so that the "Installation" and "Quick tour" subsections are visible and easily accessible.
This will need to be done for the doc of subpackages too.
> Fold sections by default in the documentation's side-bar

- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_seq2seq.py
As mentioned in https://github.com/huggingface/transformers/pull/20096#issuecomment-1335122572, in Transformers 4.25 the class `GenerationMixin` is located in `transformers.generation` and not in `transformers.generation_utils` as before. This PR enables to deal with both cases.
> Import GenerationMixin from transformers.generation if transformers >= 4.25.0

- docs/source/bettertransformer/overview.mdx
- optimum/bettertransformer/models/__init__.py
- tests/bettertransformer/test_bettertransformer_encoder.py
Add BetterTransformer support for RemBERT (part of [#20372](https://github.com/huggingface/transformers/issues/20372))
- ~~[ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case)~~.
- RemBERT's primary change is decoupling in/output embeddings. Since RemBERT uses the same Attention mechanism in BERT, it can use the same `BertLayerBetterTransformer`. (please correct me if I'm wrong)
- Minor code cleanup to sort model names alphabetically as the convention in transformers repo.
- All tests for encoders passed on GPU
cc @younesbelkada, @michaelbenayoun, @fxmarty. Thanks.
> Add BetterTransformer support for RemBERT

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/utils.py
- optimum/modeling_base.py
- optimum/onnx/configuration.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/onnxruntime/optimization.py
- optimum/onnxruntime/quantization.py
- optimum/onnxruntime/utils.py
- optimum/utils/save_utils.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/test_optimization.py
- tests/onnxruntime/test_quantization.py
- `ORTModel`, `ORTModelDecoder` and `ORTModelForConditionalGeneration` can load any ONNX model files regardless of their names, allowing to load optimized and quantized models without having to specify the `file_name` argument.
- `ORTModel._from_transformers` now downloads and loads the model in a temporary directory instead of the cache, which was not a right place to store it.  
- `ORTQuantizer` saves both the model configuration and the tokenizer / processor / feature extractor, making the exported directory usable end-to-end.
- `ORTOptimizer` was already saving the model configuration but not the tokenize / processor / feature extractor, it does now.
- `OnnxConfigWithPast` now has two class atributes (that will be used when no value is specified in the `__init__` to avoid having to …
> Optimum ONNX Runtime API improvement

- optimum/exporters/onnx/__main__.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/onnxruntime/utils.py
- optimum/utils/file_utils.py
- Refactors `validate_file_exists` 
- Refactors `infer_filename`
- Fixes function name in `optimum/exporters/onnx/__main__.py` (cc @mht-sharma)
As mentioned in #515 (cc @fxmarty)
> Refactor of 2 functions used in ORTModel

- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/training_args.py
> Fix ORTTrainer wrapper duplication / PyTorch evaluate / update with transformers 4.25.1

- optimum/exporters/onnx/__init__.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/utils.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/exporters/test_onnx_export.py
Currently, the `optimum.exporters.onnx` export in separate encoder / decoder files works well. However, for decoder-only models as gpt2, the support was not yet implemented. This PR allows decoder-only models exported through `optimum.exporters.onnx` to be loaded in `ORTDecoder` subclasses (as `ORTModelForCausalLM`).
Note: I am not sure it's super clean to duplicate methods like in this PR for specific cases. @echarlaix how do you plan to support the ONNX export for diffusion models in the current framework, and integrate in `optimum.exporters.onnx`?
There are tests missing to check:
* that `optimum.exporters.onnx` is well interfaced with ORTModel
* that the CLI of `optimum.exporters.onnx` works well
Fixes https://github.com/huggingface/optimum/issues/552
> Support decoder generated with `--for-ort` from `optimum.exporters.onnx` in `ORTDecoder`

- optimum/onnxruntime/trainer.py
This PR enables FP16 Optimizer when fp16 training is enabled.
This is the logs from both runs with and without fp16 training flag.
```
Roberta-large 
with fp16 optimizer :
***** train metrics *****
epoch                    =      13.33
train_loss               =     0.5796
train_runtime            = 0:02:46.34
train_samples            =       3668
train_samples_per_second =    307.796
train_steps_per_second   =      1.202
without fp16 optimizer
***** train metrics *****
epoch                    =      13.33
train_loss               =     0.5796
train_runtime            = 0:02:54.16
train_samples            =       3668
train_samples_per_second =    293.974
train_steps_per_second   =      1.148
```
-----------------------------------------------------
The recipe that I ran on this test: …
> enable FP16Optimizer for fp16 deepspeed training.

- optimum/onnxruntime/io_binding/io_binding_helper.py
- optimum/onnxruntime/modeling_ort.py
Move the `prepare_io_binding` function from `ORTModelForCustomTasks` to `IOBindingHelper` as this could be helpful and reusable for other ORT models, namely the ongoing `ORTModelForSemanticSegmentation`(#539).
> Move custom IOBinding to IOBindingHelper

- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/model_configs.py
- optimum/utils/input_generators.py
Fixes https://github.com/huggingface/optimum/issues/569
Note that the shapes we were providing were "wrong" in the first place, and that this commit breaks with our weird input shapes: https://github.com/huggingface/transformers/commit/97a51b0c7d483cdf13ea878a987f9aa1c9eecc91#diff-ebaff1224cad711fd3cefb771ce17d1392ae2dfc7f74dc7da9dd014d7642a344
@mht-sharma @michaelbenayoun What do you think of this fix?
So with this PR we have shapes during the export of the `decoder_with_past_model.onnx` model (sequence length = 16, batch size = 2, num beams = 3):
```
decoder_input_ids torch.Size([2, 1])
encoder_outputs len: 3
torch.Size([2, 16, 512])
None
None
attention_mask torch.Size([2, 16])
past_key_values (is list) 6
```
which somewhat match transformers (exception of the input preprocessing in …
> Fix exporters onnx shapes

- setup.py
As suggested in the title, the new NumPy has deprecated some features, we need to set it back to lower than 1.24.0 to pass CIs before patch releases of our partner libs.
> Constraint temprarily NumPy version to save CIs

- docs/source/exporters/onnx/package_reference/configuration.mdx
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/utils.py
This handles the export to ONNX in multiple files (for seq2seq models) directly in the relevant OnnxConfig itself, instead of using others.
cc @mht-sharma @fxmarty
> OnnxConfig now handle the export to encoder / decoder / decoder_with_past themselves

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
- tests/exporters/test_onnx_export.py
This PR tries to add `mobilenet` models for ONNX support 
Partially fixes https://github.com/huggingface/transformers/issues/20856 
Related: https://github.com/huggingface/transformers/pull/20860 
Also it seems that `Mobilenet` used to be supported by `transformers`? At least when I run: 
```
from transformers import  AutoModelForImageClassification
from transformers.onnx import FeaturesManager
model = AutoModelForImageClassification.from_pretrained("google/mobilenet_v2_1.0_224")
model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model)
```
Everything works fine, so maybe mobilenet has be forgotten by mistake?
cc @fxmarty @michaelbenayoun
> [`ONNX`] add `mobilenet` support

- .github/workflows/test_exporters.yml
- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/utils.py
- tests/exporters/test_exporters_onnx_cli.py
As per title, can be useful for large models.
The validation should be done on the same device as well.
> Add argument in the CLI to specify device to do the ONNX export on

- optimum/exporters/onnx/model_configs.py
For
```
optimum-cli export onnx --model runwayml/stable-diffusion-v1-5 sd_v15_onnx/
```
to pass. There should be a test for this!
Edit: I'll merge now for the tests to pass on main.
> Allow kwargs in all generate_dummy_inputs() methods

- optimum/exporters/tasks.py
Unspotted before because `task_to_automodel` was used instead of `tasks_to_automodel`, so ctrl+f did not do the job
Will do a patch for this next week
> Fix item access of some _TASKS_TO_AUTOMODELS

- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
As per title,
```
from optimum.onnxruntime import ORTModelForCausalLM
ort_model = ORTModelForCausalLM.from_pretrained("/path/to/gpt2_onnx", use_cache=True)
```
raises 
```
File "/home/fxmarty/hf_internship/optimum/optimum/onnxruntime/modeling_decoder.py", line 536, in _from_pretrained
decoder_with_past_path = ORTModelDecoder.infer_onnx_filename(
File "/home/fxmarty/hf_internship/optimum/optimum/onnxruntime/modeling_ort.py", line 351, in infer_onnx_filename
raise FileNotFoundError(f"Could not find any ONNX model file in {path}")
FileNotFoundError: Could not find any ONNX model file in /home/fxmarty/hf_internship/optimum/gpt2_onnx
```
which is not informative. With this PR, we get:
```
FileNotFoundError: The parameter `use_cache=True` was passed to ORTModelDecoder.from_pretrained() but no …
```
> Fix uninformative message when passing `use_cache=True` to ORTModel and no ONNX with cache is available

- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
When several providers are passed to the `InferenceSession`, which is the case when `TensorrtExecutionProvider` is chosen, the `provider_options` argument needs to be of the same length than `providers`, otherwise raising:
```
EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
```
Reference: https://onnxruntime.ai/docs/api/python/api_summary.html#inferencesession
This was untested up to now. Still need to add a test for this PR.
In a next PR: remove all the code duplication for `load_model()` in `modeling_ort.py`, `modeling_decoder.py`, `modeling_seq2seq.py`. But I won't do it in this PR.
This should fix https://github.com/huggingface/optimum/issues/606
> Fix provider options when several providers are passed

- docs/source/onnxruntime/usage_guides/gpu.mdx
This documentation addition clarifies the usage of the TensorRT engine. Note: https://github.com/huggingface/optimum/pull/653 is needed for the code samples to work.
> Add TensorRT engine to ONNX Runtime GPU documentation

- docs/source/exporters/onnx/usage_guides/contribute.mdx
Adds a missing import for BertOnnxConfig
Updates the parameter order of get_exporter_config_constructor and export functions, which were inverted recently.
> minor updates on ONNX config guide

- optimum/exporters/onnx/model_configs.py
Flaubert requires `token_type_ids` just like BERT, so `FlaubertOnnxConfig` inherints from `BertOnnxConfig` instead of `DistilBertOnnxConfig` to fix that.
Fixes #667
> Fix FlaubertOnnxConfig

- .github/workflows/test_onnxruntime_gpu.yml
- tests/onnxruntime/Dockerfile_onnxruntime_gpu
GPU test may need TensorRT, so let's use an image that has TensorRT pre-installed.
Still need to test that everything runs fine before merging.
> Use nvcr.io/nvidia/tensorrt image for GPU tests

- optimum/exporters/onnx/model_configs.py
- optimum/onnxruntime/utils.py
- optimum/utils/normalized_config.py
- tests/onnxruntime/test_optimization.py
This PR adds support for optimizing LongT5 using the ORT transformer optimizer script.
Example usage:
```
from optimum.onnxruntime import ORTModelForSeq2SeqLM, AutoOptimizationConfig, ORTOptimizer
import torch
import time
model_name = 'google/long-t5-local-base'
device = 'cuda'
batch_size = 4
sequence_length = 16
inputs = {
'input_ids': torch.ones((batch_size, sequence_length), dtype=torch.int64).to(device),
'attention_mask': torch.ones((batch_size, sequence_length), dtype=torch.int64).to(device),
'decoder_input_ids': torch.ones((batch_size, sequence_length), dtype=torch.int64).to(device)
}
model = ORTModelForSeq2SeqLM.from_pretrained(model_name, from_transformers=True, use_io_binding=True, provider='CUDAExecutionProvider')
start_time = time.time()
outputs_before = model(**inputs) …
```
> Add support for LongT5 optimization using ORT transformer optimizer script

- docs/source/exporters/onnx/package_reference/configuration.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
This PR adds the possibility to export MPNet models into the ONNX format.
> Add MPNet ONNX export

- optimum/onnx/__init__.py
- optimum/onnx/graph_transformations.py
- optimum/onnx/transformations_utils.py
- optimum/onnxruntime/modeling_decoder.py
- tests/onnx/test_onnx_graph_transformations.py
As per title.
Partially fixes #627 , we need to integrate this in this CLI and document + test.
Try with:
```python
import onnx
from pathlib import Path
from optimum.onnx import model_to_int32
path = "/path/to/decoder_model.onnx"
model = onnx.load(path)
model = model_to_int32(model)
onnx.save(
model,
path,
save_as_external_data=True,
all_tensors_to_one_file=True,
location=Path(path).name + "_data",
)
onnx.checker.check_model(path)
```
Inspect the original and transformed models "Slice" nodes.
> ONNX transformation to cast int64 constants to int32 when possible

- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
Attributes as `self.model`, `self.model_name`, `self.model_path` are unwanted and actually may take some RAM for no reason.
> Avoid initializing unwanted attributes for ORTModel's having several inference sessions

- optimum/onnxruntime/quantization.py
The `file_name` parameter of the `ORTQuantizer` `from_pretrained` method is currently discarded when it should be used if given by the users : resulting in errors when quantizing a seq2seq model as done in the current [documentation](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/quantization#quantize-seq2seq-models)
> Fix the ORTQuantizer loading from specific file

- optimum/exporters/onnx/model_configs.py
Fixes the whisper export
The current export for whisper fails because the cross attention key values are not exported as input in the ONNX model after the new condition introduced in the [transformers@97a51](https://github.com/huggingface/transformers/commit/97a51b0c7d483cdf13ea878a987f9aa1c9eecc91).
The error occurs due to incorrect dummy input generation for cross attention key values for export. The PR fixes the same.
Fixes #600
> Fix whisper export

- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_seq2seq.py
This PR adds support for generation config in ORTModel, following https://github.com/huggingface/transformers/pull/20388
Note: we should really add nightly tests tracking on transformers/diffusers main.
> Support generation config in ORTModel

- optimum/onnxruntime/modeling_ort.py
- optimum/utils/normalized_config.py
- tests/onnxruntime/test_modeling.py
Fixes
```
2023-01-25T13:47:05.2363205Z ======================================================================
2023-01-25T13:47:05.2364038Z ERROR: test_compare_generation_to_io_binding_0_bloom_True (test_modeling.ORTModelForCausalLMIntegrationTest)
2023-01-25T13:47:05.2365483Z ----------------------------------------------------------------------
2023-01-25T13:47:05.2366078Z Traceback (most recent call last):
2023-01-25T13:47:05.2367102Z   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
2023-01-25T13:47:05.2367838Z     return func(*(a + p.args), **p.kwargs)
2023-01-25T13:47:05.2368441Z   File "/workspace/optimum/tests/onnxruntime/test_modeling.py", line 1729, in test_compare_generation_to_io_binding
2023-01-25T13:47:05.2369012Z …
```
> Fix GPU tests

- optimum/bettertransformer/models/base.py
- optimum/bettertransformer/models/encoder_models.py
- optimum/bettertransformer/transformation.py
- optimum/utils/__init__.py
- optimum/utils/modeling_utils.py
- tests/bettertransformer/test_bettertransformer_audio.py
- tests/bettertransformer/test_bettertransformer_encoder.py
- tests/bettertransformer/test_bettertransformer_vision.py
- tests/bettertransformer/testing_bettertransformer_utils.py
This PR adds the `inverse_transform` support for BT-transformed models. 
In the future, PyTorch will support `BetterTransformer` for training. Therefore a user would want to first convert a model, train it with `BetterTransformer` as backend and save the trained model afterwards. Before this PR the keys of the model's state dict are changed, therefore saving the model out of the box would break the model architecture and support with `transformers`. This PR adds a new transformation `invert_transform` that will let users convert back the BT model in its original format so that they can push/save their model.
cc @fxmarty @michaelbenayoun @HamidShojanazeri
> [`BetterTransformer`] Let's make the transformation invertible

- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- optimum/utils/__init__.py
- optimum/utils/normalized_config.py
- tests/exporters/exporters_utils.py
- tests/exporters/test_exporters_onnx_cli.py
- tests/exporters/test_onnx_export.py
Supports vision-encoder-decoder export to onnx in optimum
Changes
* Adds generic class for exporting Encoder-Decoder type models [doc](https://huggingface.co/docs/transformers/model_doc/encoder-decoder)
* Adds export for `vision-encoder-decoder` models using the above class
Limitation
* Past key value export not supported with TROcr
* Donut model is not supported
> Add vision encoder decoder model in exporters

- optimum/exporters/onnx/model_configs.py
Fixes export of `Speech2Text` models
1. Fixes #721 - Updated the `sequence_length` for  `past_key_values` generator for monolith case.
2. Updated normalised config for the model to fix export using decoder with past for some models.
> Fix speech2text export

- .github/workflows/test_exporters_slow.yml
- docs/source/exporters/onnx/usage_guides/export_a_model.mdx
- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/exporters/exporters_utils.py
- tests/exporters/test_exporters_onnx_cli.py
- tests/exporters/test_onnx_export.py
- tests/onnx/test_onnx_graph_transformations.py
As per title.
Breaking change: the old `--for-ort` behavior is now the default.
Additionally, the tests in `test_onnx_export.py` are now all slow.
> Replace `--for-ort` option in ONNX export by `--monolith`

- docs/source/onnxruntime/package_reference/modeling_ort.mdx
- docs/source/onnxruntime/usage_guides/pipelines.mdx
- optimum/onnxruntime/__init__.py
- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_seq2seq.py
- optimum/pipelines.py
- optimum/utils/normalized_config.py
- optimum/utils/testing_utils.py
- tests/onnxruntime/test_modeling.py
This PR enables the inference of the `VisionEncoderDecoder` models using ONNXRuntime. The PR adds `ORTModelForVision2Seq` for doing inference similar to `AutoModelForVision2Seq` by changing just a few lines.
```diff
>>> from PIL import Image
>>> from transformers import GPT2TokenizerFast, ViTImageProcessor
->>>  from transformers import AutoModelForVision2Seq
+>>>  from optimum.onnxruntime import ORTModelForVision2Seq
>>> import requests
>>> model_name = "nlpconnect/vit-gpt2-image-captioning"
->>> model = AutoModelForVision2Seq.from_pretrained(model_name)
+>>> model = ORTModelForVision2Seq.from_pretrained(model_name, from_transformers=True)
>>> tokenizer = GPT2TokenizerFast.from_pretrained(model_name)
>>> image_processor = ViTImageProcessor.from_pretrained(model_name)
>>> url = …
```
> Add ORTModelForVision2Seq for VisionEncoderDecoder models inference

- docs/source/exporters/onnx/package_reference/configuration.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- optimum/utils/normalized_config.py
- tests/exporters/exporters_utils.py
- tests/onnxruntime/test_modeling.py
Support GPT-Neo-X model config. 
Fixes #555
> Add gpt-neo-x support

- .github/workflows/test_onnxruntime.yml
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
This should fix at least partially https://github.com/huggingface/optimum/issues/753
It seems possible that the `prepare_inputs_for_generation` redefined in `modeling_decoder.py` and `modeling_seq2seq.py` is not valid for some models that do some special preprocessing before the `self` call in `generate()`.
Tests are added to make sure reusing past key values is faster (on CPU).
> Fix ONNX Runtime cache usage for decoders, add relevant tests

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/utils.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
**Breaking change:** The export with `--monolith` along with `--task ...-with-past` is no longer supported. It made no sense anyway.
As per title, for GPT2 for causallm, the right shapes should be along the lines of:
```
-----
input_ids: torch.Size([1, 13])
attention_mask torch.Size([1, 13])
encoder_hidden_states None
encoder_attention_mask None
-----
input_ids: torch.Size([1, 1])
past_key_values
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
torch.Size([1, 4, 13, 8])
attention_mask torch.Size([1, 14])
encoder_hidden_states None
encoder_attention_mask None
-----
input_ids: torch.Size([1, 1]) …
```
> Fix wrong shapes used at ONNX export and validation

- docs/source/exporters/onnx/usage_guides/contribute.mdx
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/model_configs.py
- optimum/onnx/configuration.py
This PR changes the type annotation for dictionaries in `exporters.onnx` from [`Mapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping) to `Dict`.
> Change type annotation

- optimum/onnxruntime/utils.py
As per title, the reliance on `_ld_preload.py` is not robust on Windows as reported in https://github.com/huggingface/optimum/issues/769
> Disable ONNX Runtime provider check on Windows

- setup.py
We are probably good now with the ORT 1.14 release, could still be that `tf2onnx` has not updated (is this package even maintained? https://github.com/onnx/tensorflow-onnx/pull/2097 )
> Unpin numpy <1.24.0

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/convert.py
Passing `CUDA_VISIBLE_DEVICES=""` made the export fail. Besides, `_ld_preload.py` is not a reliable source to detect the CUDA/TRT install on Windows.
> Fix used shapes, device at ONNX export

- .github/workflows/test_cli.yml
- .github/workflows/test_onnx.yml
- .github/workflows/test_onnxruntime.yml
As per title & https://github.com/microsoft/onnxruntime/issues/14663
> Temporarily disable python 3.9 + macOS test due to onnxruntime 1.14 regression

- docs/source/onnxruntime/usage_guides/trainer.mdx
- examples/onnxruntime/training/docker/Dockerfile-ort1.14.0-cu116
- optimum/onnxruntime/trainer.py
> Update ORT Training to 1.14.0

- .github/workflows/test_onnxruntime_gpu.yml
- tests/onnxruntime/Dockerfile_onnxruntime_gpu
- tests/onnxruntime/test_modeling.py
As it yields a core dump that stops the workflow.
> Temporarily disable segformer TensorRT test

- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_decoder.py
- tests/onnxruntime/test_modeling.py
As per title. The tests from `pytest tests/onnxruntime/test_modeling.py -k "test_compare_to_io_binding and ORTModelForCausalLMIntegrationTest" -s` all pass.
> Support IO Binding for merged decoder

- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/utils.py
- tests/onnxruntime/test_modeling.py
This allows to avoid repeated regex calls when using IOBinding.
The tests from `pytest tests/onnxruntime/test_modeling.py -k "test_compare_to_io_binding" -s` all pass.
> Use a stateful ordered_input_names in ORTModel

- examples/onnxruntime/training/image-classification/README.md
- examples/onnxruntime/training/language-modeling/README.md
- examples/onnxruntime/training/question-answering/README.md
- examples/onnxruntime/training/summarization/README.md
- examples/onnxruntime/training/text-classification/README.md
- examples/onnxruntime/training/token-classification/README.md
- examples/onnxruntime/training/translation/README.md
Update readmes to use torchrun for DDP, as the current snippets use DP which are not suggested by PyTorch anymore.
> Update ONNX Runtime training doc - use torchrun

- optimum/exporters/onnx/model_configs.py
- tests/exporters/exporters_utils.py
- tests/exporters/onnx/test_onnx_export.py
A few slow tests were yet again broken due to the monolith + with-past deprecation, and due to the testing on several shapes.
> Fix ONNX export tests

- optimum/exporters/tasks.py
- optimum/exporters/tflite/config.py
- optimum/exporters/tflite/model_configs.py
Adds ResNet support for TFLite export. 
I tried testing it with the following in isolation:
```python
from optimum.exporters.tflite import export, validate_model_outputs
from optimum.exporters.tasks import TasksManager
from transformers import AutoConfig
from optimum.exporters.tflite.model_configs import ResNetTFLiteConfig
from tempfile import NamedTemporaryFile
from pathlib import Path
task = "image-classification"
model_name = "microsoft/resnet-50"
model_class = TasksManager.get_model_class_for_task(task, framework="tf")
config = AutoConfig.from_pretrained(model_name)
model = model_class.from_config(config)
tflite_config = ResNetTFLiteConfig(model.config, task)
atol = tflite_config.ATOL_FOR_VALIDATION
with NamedTemporaryFile("w") as output:
try:
_, tflite_outputs = export(
model=model, …
```
> [TFLite Export] Adds support for ResNet

- optimum/exporters/onnx/model_configs.py
The feature dimension is static, the dimension shape will be equal to `config.hidden_size` for the `CLIPTextModel` and to  `config.cross_attention_dim` for the `UNet2DConditionModel`.
> Remove feature dimension as dynamic axes for stable diffusion ONNX export

- setup.py
- tests/exporters/Dockerfile_exporters_gpu
Fixing it yet again, this time due to a conflicting `onnxruntime` and `onnxruntime-gpu` install.
> Fix exporters GPU CI

- optimum/exporters/tasks.py
- optimum/onnx/transformations_utils.py
As per comment in the PR, we had duplicated initializer names pointing out to different data. This was the case for codegen.
All slow tests pass for codegen, merging this one for the release as requested.
> Fix duplicate name merged decoder

- optimum/exporters/onnx/model_configs.py
The removed code was removed to export the models when `--monolith` and `use_past=True` are both passed. Since their use is removed the code is no longer required.
> Remove redundant code

- optimum/bettertransformer/models/__init__.py
- optimum/bettertransformer/models/decoder_models.py
- tests/bettertransformer/test_encoder.py
- tests/bettertransformer/testing_utils.py
This is only usable for the decoder, with [`T5LayerCrossAttention`](https://github.com/huggingface/transformers/blob/820c46a707ddd033975bc3b0549eea200e64c7da/src/transformers/models/t5/modeling_t5.py#L647) as discussed offline, due to the position bias present in `T5LayerSelfAttention`.
> Support scaled_dot_product_attention for t5

- tests/benchmark/benchmark_bettertransformer.py
This PR adds the benchmark script adapted for decoder-based models as well, to benchmark the speedup we obtain with `torch.sdpa` and `transformers` models
cc @fxmarty
> [`BT`] add decoder benchmark script

- optimum/bettertransformer/models/decoder_models.py
- tests/bettertransformer/test_decoder.py
- tests/bettertransformer/testing_utils.py
Currently on the `main` branch the fp16 inference for BetterTransformer decoder models is not supported, this PR aims to fix this
cc @fxmarty
> [`BT`] Add fp16 support

- optimum/bettertransformer/transformation.py
The [syntax](https://peps.python.org/pep-0570/) for specifying positional-only parameters in python function was introduced in python v3.8 and will throw error for lower version (for `v3.7` in our case)
> Remove positional-only parameters not support by python < v3.8

- tests/exporters/onnx/test_exporters_onnx_cli.py
- tests/onnxruntime/test_optimization.py
Some tests temporarily disabled were fixed in https://github.com/huggingface/optimum/pull/871
> Reactivate export & optimization tests for causal-lm models

- optimum/onnxruntime/modeling_diffusion.py
In this PR we enable the loading of stable diffusion ONNX model even when the model configuration is the model original configuration
> Fix loading of an ONNX stable diffusion model when config doesn't match

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/model_patcher.py
WavLM uses `torch.nn.functional.multi_head_attention_forward` that dispatches on `scaled_dot_product_attention` that is not supported by the ONNX export in PyTorch 2.0. We need to patch the model to avoid this call.
Reference: https://github.com/pytorch/pytorch/blob/c263bd43e8e8502d4726643bc6fd046f0130ac0e/torch/nn/functional.py#L5293-L5342
> Fix WavLM onnx export upon torch 2.0 release

- optimum/configuration_utils.py
PushToHubMixin._create_repo broke due to transformers 4.27 release, that broke some tests.
Compare https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/utils/hub.py#L666 and https://github.com/huggingface/transformers/blob/v4.27.1/src/transformers/utils/hub.py#L657
> Fix PushToHubMixin._create_repo according to transformers 4.27 release

- .github/workflows/test_bettertransformer.yml
- .github/workflows/test_cli.yml
- .github/workflows/test_onnx.yml
- .github/workflows/test_onnxruntime.yml
- .github/workflows/test_optimum_common.yml
- setup.py
As PyTorch did: https://github.com/pytorch/pytorch/releases/tag/v2.0.0
> Drop python 3.7 support

- optimum/exporters/onnx/convert.py
- optimum/onnxruntime/optimization.py
Previously we had errors as
```
File "/home/user/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/user/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/user/scripts/optimum/optimum/exporters/onnx/__main__.py", line 255, in <module>
main()
File "/home/user/scripts/optimum/optimum/exporters/onnx/__main__.py", line 212, in main
optimizer.optimize(save_dir=args.output, optimization_config=optimization_config, file_suffix="")
File "/home/user/scripts/optimum/optimum/onnxruntime/optimization.py", line 192, in optimize
optimizer.save_model_to_file(output_path.as_posix(), use_external_data_format, one_external_file)
File …
```
> Automatic support for large ONNX models in ORTOptimizer

- optimum/exporters/tasks.py
- tests/exporters/common/test_tasks_manager.py
Adds a registering mechanism for the `TasksManager`, allowing to dynamically register configs for any (backend, model, task) triplet.
> Registering mechanism for the `TasksManager`

- optimum/exporters/onnx/base.py
Slight error where axis with different length were sharing the same name, bug introduced by myself in https://github.com/huggingface/optimum/pull/872
Some GPU and TRT tests were failing due to this.
> Fix axis name for seq2seq ONNX models

- docs/source/exporters/onnx/overview.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
I noticed that there is still no support for exporting to ONNX `facebook/opt-{x}` models when I needed them. Therefore, I propose very simple changes that add this support.
I checked the ability to export models with 350M, 1.3B and 6.7B parameters on A100 40GB, as you can see from the results, they can be used. Although, not all outputs for 1.3B and 6.7B models are successfully checked for closeness, in my experience, this is not something terrible.
I am [attaching](https://pastebin.com/xtRgtRYF) the export log of the 1.3B model with the `causal-lm-with-past` task.
_Note: 80GB of free RAM is not enough to export 13B OPT model._
> Adding support for Facebook's OPT models

- optimum/exporters/onnx/__main__.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
As per title, fixes https://github.com/huggingface/optimum/issues/905, https://github.com/huggingface/optimum/issues/906
This bug is introduced by https://github.com/huggingface/transformers/pull/21252 that moves `generate()` implementation in `WhisperForConditionalGeneration`, hence breaking the inheritance order in transformers.
> Fix ORTModel MRO for whisper

- optimum/onnx/graph_transformations.py
- optimum/onnx/transformations_utils.py
- tests/onnx/test_onnx_graph_transformations.py
Fixes https://github.com/huggingface/optimum/issues/921
In next PRs:
1. Add the support for merged decoder for seq2seq models in `optimum-cli export onnx`
2. Add the support for merged decoder for seq2seq models in ORTModel
> Fix encoder-decoder ONNX merge

- docs/source/onnxruntime/usage_guides/optimization.mdx
- docs/source/onnxruntime/usage_guides/quantization.mdx
- optimum/commands/onnxruntime/optimize.py
- optimum/commands/onnxruntime/quantize.py
- tests/cli/test_cli.py
This PR makes the `-o` / `--output` argument for `optimum-cli onnxruntime optimize / quantize` mandatory and does not allow it to be the same as the original directory.
Still wondering whether we should raise an error or just a warning.
While saving everything under the same directory is completely working here, it makes it unusable with `ORTModel`s because multiple ONNX files are in the directory. While we could provide the filename explicitly, I feel like keeping a easy to use workflow is better.
> `optimun-cli onnxruntime quantize / optimize` output argument is now required

- optimum/commands/__init__.py
- optimum/commands/base.py
- optimum/commands/env.py
- optimum/commands/export/__init__.py
- optimum/commands/export/base.py
- optimum/commands/export/onnx.py
- optimum/commands/export/tflite.py
- optimum/commands/onnxruntime/__init__.py
- optimum/commands/onnxruntime/base.py
- optimum/commands/onnxruntime/optimize.py
- optimum/commands/onnxruntime/quantize.py
- optimum/commands/optimum_cli.py
- optimum/commands/register/README.md
- optimum/commands/register/__init__.py
- tests/cli/cli_with_custom_command.py
- tests/cli/test_cli.py
This PR both refactors how the Optimum CLI was implemented and provides a way to register commands to the Optimum CLI for subpackages.
It is possible to register a command in the Optimum CLI, either as a command or a subcommand of an already existing command.
Steps to follow:
1. Create a command as a subclass of `optimum.commands.BaseOptimumCLICommand`.
2. Create a Python file under `optimum/commands/register/`, and define a `REGISTER_COMMANDS` list variable there.
3. Fill the `REGISTER_COMMANDS` as folows:
```python
from ..my_custom_commands import CustomCommand1, CustomCommand2
from ..export import ExportCommand
REGISTER_COMMANDS = [
CustomCommand1, 
(CustomCommand2, ExportCommand) # CustomCommand2 will be registered
]
> Register mechanism for the Optimum CLI

- optimum/onnxruntime/base.py
- optimum/utils/logging.py
- tests/onnxruntime/test_modeling.py
Following https://github.com/huggingface/optimum/pull/872, we make sure we have no breaking change for the existing exported models.
Thank you @echarlaix for pointing it out!
> Ensure backward compatibility of ORTModel

- optimum/onnx/transformations_utils.py
When exporting a causal lm model to onnx, the past key version and regular version are merged.  The merge loops through each tensor in the graph and stores the values as dict keys.  This requires massive memory (>100GB for an 11GB model), and prevents merging from happening.
This is due to the `tensor_data` in `_find_duplicate_initializers` being converted from `bytes` to a `tuple`.  I assume there is a good reason to convert it to a tuple (maybe for comparison across dtypes).
As such, this PR doesn't remove that conversion, but instead converts the tuple to a string and hashes it.  It uses SHA-512 to reduce the probability of a hash collision.  This uses very little memory to do the deduplication.
You could also:
-  just convert to `str` to remove the possibility of collisions - this …
> Hash tensor data during deduplication

- optimum/commands/base.py
- optimum/commands/optimum_cli.py
- tests/cli/cli_with_custom_command.py
- tests/cli/test_cli.py
The Optimum CLI was not printing the proper help message for subcommands.
```plain
optimum-cli export
```
Before adding the register mechanism to the CLI, the above command would give:
```plain
usage: optimum-cli <command> [<args>]
positional arguments:
{export,env,onnxruntime}
optimum-cli command helpers
export              Export PyTorch and TensorFlow models to several format (currently supported: onnx).
env                 Get information about the environment used.
onnxruntime         ONNX Runtime optimize and quantize utilities.
options:
-h, --help            show this help message and exit
```
Now, after adding the register mechanism, it gives:
```plain
File "/home/michael/micromamba/envs/optimum/bin/optimum-cli", line 8, in <module> …
```
> `optimum-cli` print the help of subcommands

- docs/source/exporters/onnx/usage_guides/export_a_model.mdx
- docs/source/onnxruntime/quickstart.mdx
- docs/source/onnxruntime/usage_guides/gpu.mdx
- docs/source/onnxruntime/usage_guides/models.mdx
- docs/source/onnxruntime/usage_guides/optimization.mdx
- docs/source/onnxruntime/usage_guides/pipelines.mdx
- docs/source/onnxruntime/usage_guides/quantization.mdx
- docs/source/quicktour.mdx
cc @echarlaix , as we are deprecating this argument in favor of `export`.
> Remove from_transformers references from the documentation

- optimum/bettertransformer/models/attention.py
- optimum/bettertransformer/models/decoder_models.py
- optimum/bettertransformer/transformation.py
- tests/bettertransformer/test_decoder.py
- tests/exporters/onnx/test_onnx_export.py
As per title
SDPA does not automatically detect train/eval mode.
> Fix slow tests & sdpa dropout

- optimum/exporters/tasks.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
Fixes conversational, summarization, zero-shot-classification, translation.
I believe they are the only "exotic" pipeline tags.
> Fix some pipeline tags usage in TasksManager

- optimum/exporters/onnx/model_configs.py
Fixes https://github.com/huggingface/optimum/issues/1004
> Fix past key value generator used for ONNX export validation for t5/mt5

- optimum/bettertransformer/transformation.py
Fixes the following error when model as weights offloaded to disk by providing an optional `offload_dir` argument that can be used with `BetterTransformer.transform`:
`ValueError: We need an 'offload_dir' to dispatch this model according to this 'device_map', the following submodules need to be offloaded...`
Example:
`model = BetterTransformer.transform(model_hf, keep_original_model=True, offload_dir="OFFLOAD-DIR")`
Let me know if you have any suggestions!
P.S. I don't think any of the below options applies
> fix: ValueError offload_dir

- docs/source/concept_guides/quantization.mdx
I was just now reading the quantization guide in the docs and noticed some small typos, so I'm submitting a PR to fix them.
Some notes on the fixes:
* indent in the enumeration in the calibration section, since it is being rendered as a single-level enumeration as opposed to a nested one
* `activation is computed at in advance at *quantization-time*` -> `activation is computed in advance at *quantization-time*`
* `thiw works well with activations` -> `this works well with activations`
* `then chooses according to some criterion.` -> `then chooses according to some criterion:`; when reading I was wondering if entropy/MSE/percentile were different approaches to the histogram method, or separate calibration techniques. I checked the code and confirmed it's the former, so I added a colon to …
> Fix some typos in the quantization guide

- optimum/exporters/onnx/base.py
The output name has changed for the `masked-im` task starting from `transformers==4.29`.
It was `logits` before, and it became `reconstruction`.
> `masked-im` output name fix for transformers >= 4.29.0

- setup.py
As discussed [here](https://github.com/huggingface/optimum/issues/1046#issuecomment-1545663717) the torchvision is not always needed. As such it can be removed from the requirements although it does need to be available for the tests, so it is now included in `TESTS_REQUIRE`.
Fixes https://github.com/huggingface/optimum/issues/1046#issuecomment-1545663717
> remove torchvision requirement

- optimum/exporters/tasks.py
- tests/exporters/common/test_tasks_manager.py
This fixes likely a bug in https://github.com/huggingface/optimum/pull/967, where transformers model type would not be filled in general.
As some model types as visualbert and pix2struct need a special class to be loaded (not autoclass), we need the model type on top of the task to retrieve the right class to load from the [`_CUSTOM_CLASSES` dict](https://github.com/huggingface/optimum/blob/4c2389a9be027220475e7ca74ef43c1e86ca5ef8/optimum/exporters/tasks.py#L225-L228).
`RUN_SLOW=1 pytest tests/exporters/common/test_tasks_manager.py -k "test_custom_class" -s` was not passing, now it does.
> Detect model type for all transformers models in TasksManager

- optimum/modeling_base.py
Push to hub is failing due to recent API change in huggingface_hub:
```
E       TypeError: create_repo() got an unexpected keyword argument 'name'
```
cf. https://huggingface.co/docs/huggingface_hub/package_reference/hf_api#huggingface_hub.HfApi.create_repo.repo_id
> Fix HF Push to hub

- optimum/onnxruntime/optimization.py
- tests/onnxruntime/test_optimization.py
ORT optimization support for `whisper` was added here #986 but `ORTOptimizer` didn't support `ORTModelForSpeechSeq2Seq`.
@regisss I can add tests if necessary.
> added ORTModelForSpeechSeq2Seq support to optimizer

- optimum/exporters/onnx/utils.py
- setup.py
Limit `transformers` version to avoind incompatibility issues and add warning log for `diffusers>=0.17.0` (as some subpackage like openvino)
> Fix transformers version 

- optimum/utils/normalized_config.py
I want to use TSModelForCausalLM class loading mpt model, but the model_type "mpt" missed. so I create `MptLikeNormalizedTextConfig` to normalize the config.
> Add mpt model_type to NormalizedTextConfig

- optimum/modeling_base.py
- setup.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
In this PR we add a workaround to fix pipeline inference with optimum models compatibility with `transformers>=v4.30.0`. Coming from [`infer_framework`](https://github.com/huggingface/transformers/blob/70c79940957fb25b54bd1b106935c756b90345eb/src/transformers/utils/generic.py#L568)  which should be modified to be compatible with optimum models
> Fix optimum model inference compatibility with transformers >= v4.30.0

- optimum/exporters/onnx/__main__.py
- optimum/exporters/tasks.py
- optimum/exporters/tflite/__main__.py
Fixes https://github.com/huggingface/optimum/issues/1104
> Improve the offline support for the ONNX/TFLite export

- optimum/exporters/onnx/utils.py
- optimum/utils/import_utils.py
- setup.py
As per title and discussed on slack, slightly more minimal than https://github.com/huggingface/optimum/pull/1108 given that SDPA ONNX export will be supported from PyTorch 2.1 onwards.
@echarlaix is it OK to have the requirement `diffusers>=0.17.0`?
> Fix stable diffusion ONNX export following diffusers breaking change

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/constants.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/utils.py
- optimum/utils/normalized_config.py
- tests/exporters/onnx/test_onnx_export.py
Post-processing (merging of decoders) still uses x2 the model size **in RAM, not GPU memory**.
May partially fix https://github.com/huggingface/optimum/issues/1069 https://github.com/huggingface/optimum/issues/1060 https://github.com/huggingface/optimum/issues/1055
Fixes as well a bug where ORT inputs generated in `generate_dummy_inputs_for_validation` were always of type fp32, even if the export is in fp16.
ONNX Runtime has the bad habit of not releasing GPU memory (see https://github.com/microsoft/onnxruntime/issues/7463 & https://github.com/microsoft/onnxruntime/issues/11362 & the script below) when doing
```python
del session
gc.collect()
```
or when simply exiting a function that initialized an InferenceSession.
Thus, in the ONNX export validation, as we initialize several …
> Lower GPU memory requirements at ONNX export

- optimum/bettertransformer/models/encoder_models.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- optimum/utils/normalized_config.py
- tests/exporters/exporters_utils.py
Added changes for CvT model
Fixes part of #555
@michaelbenayoun @fxmarty
> Add CvTONNX Config

- optimum/bettertransformer/models/__init__.py
- optimum/bettertransformer/models/base.py
- optimum/bettertransformer/models/decoder_models.py
- optimum/bettertransformer/transformation.py
- tests/bettertransformer/test_vision.py
- tests/bettertransformer/testing_utils.py
Add BLIP-2 to the BetterTransformer API.
Part of #1056
> Add blip-2 to bettertransformer

- docs/source/exporters/onnx/usage_guides/export_a_model.mdx
- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/model_patcher.py
- tests/exporters/onnx/test_onnx_export.py
As per title, described in the doc & requested by @xenova:
* Add a `model_kwargs (Dict[str, Any])` argument to `main_export` to allow to pass arbitrary kwargs to the model during the export and validation
* Add a `custom_onnx_configs (Dict[str, OnnxConfig])` argument to `main_export`, to allow to pass more smoothly custom configs for specific usages. An example is provided in the documentation for `output_attentions=True`.
This PR also disable the use of subprocesses by default in the validation in case `main_export` is not called from `optimum-cli export onnx`, as we use the `spawn` multiprocessing method that requires to use the `if __name__ == "__main__"` guard, that can be a breaking change.
> [ONNX export] Ability to pass arbitrary kwargs, custom ONNX configs

- optimum/exporters/onnx/convert.py
This PR resolves incomplete model memory release issue. The original code only delete the reference of model and onnx_model but not to trigger python gc and to release video memory. I found this issue when I tried to export llama based 13B model using fp16 on a A100 80G card. After showing that `Saving external data to one file...`, the the video memory usage rose up from 52G to 80G, which made the process crashed.
The export command is down below
```bash
optimum-cli export onnx --model TheBloke/Wizard-Vicuna-13B-Uncensored-HF \
--task causal-lm-with-past --fp16 --device cuda {save_dir}
```
There is no existing opening issue about this.
Now the export process will not use more than double the size of model weights memory for correct releasing models, which makes exporting 13B models on …
> [ONNX export] Fixed incomplete model memory release issue

- optimum/modeling_base.py
add trust remote code option for config when use xxxx.from_pretrained().
I found the issue when I used `TSModelForCausal` class, I pass the trust_remote_code, but it doesn't work.
```
user_model = TSModelForCausalLM.from_pretrained(
args.output_dir, file_name="best_model.pt", trust_remote_code=args.trust_remote_code
)
```
> Add trust remote code option for config

- docs/source/exporters/onnx/usage_guides/export_a_model.mdx
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- optimum/utils/save_utils.py
- setup.py
- tests/exporters/onnx/test_onnx_export.py
As per title. As a next step, we should support loading an `onnx_config.py` file from the custom model repository and use it for the ONNX export, so that e.g. the CLI works as well.
Fixes https://github.com/huggingface/optimum/issues/1061 https://github.com/huggingface/optimum/issues/1040 https://github.com/huggingface/optimum/issues/1134
> ONNX export for custom architectures & models with custom modeling code

- optimum/bettertransformer/models/attention.py
As per title, fixes https://github.com/huggingface/optimum/issues/1179
> Allow `attention_mask=None` for BetterTransformer in the inference batched case for gpt2 & gpt-neo

- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- optimum/onnxruntime/modeling_diffusion.py
- optimum/pipelines/diffusers/pipeline_stable_diffusion_xl_img2img.py
- optimum/utils/input_generators.py
In this PR we use `StableDiffusionXLImg2ImgPipeline` to load a SD XL pipeline by default before exporting each component as it will allow some components to be [optional](https://github.com/huggingface/diffusers/blob/v0.18.2/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L111) during loading.
Depending on the value of `requires_aesthetics_score` we create a dummy input of the corresponding expected shape https://github.com/huggingface/diffusers/blob/v0.18.2/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L571 when exporting the U-NET component
> fix SD XL ONNX export for img2img task

- docs/source/onnxruntime/usage_guides/trainer.mdx
This PR adds a section to the ORT Training Doc detailing stable diffusion integration with ONNX Runtime Training. This addition is in response to the new text-to-image example added by https://github.com/huggingface/optimum/pull/1136.
> add ort + stable diffusion documentation

- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_seq2seq.py
- tests/onnxruntime/test_modeling.py
As per title
Fixes https://github.com/huggingface/optimum/issues/1192
> Fix vision encoder decoder that may not cache cross-attention

- optimum/pipelines/diffusers/pipeline_stable_diffusion.py
- optimum/pipelines/diffusers/pipeline_stable_diffusion_inpaint.py
Set default value for model without any config such as [tiny-random-OnnxStableDiffusionPipeline](https://huggingface.co/hf-internal-testing/tiny-random-OnnxStableDiffusionPipeline). If no configuration provided, the default `height` and `width` value will be [512](https://github.com/huggingface/diffusers/blob/v0.8.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L392)
> Set default value to unet config sample size

- README.md
- docs/source/installation.mdx
As discussed with @regisss, adding `--upgrade-strategy eager` so that the latest subpackages are installed.
With `pip install --upgrade optimum[intel]`  the latest optimum version will be downloaded but not the latest version of optimum-intel
> add upgrade strategy

- optimum/bettertransformer/models/__init__.py
- optimum/bettertransformer/models/base.py
- optimum/bettertransformer/models/decoder_models.py
- optimum/bettertransformer/models/encoder_models.py
- optimum/bettertransformer/transformation.py
- optimum/utils/testing_utils.py
- tests/bettertransformer/test_audio.py
- tests/bettertransformer/test_common.py
- tests/bettertransformer/test_decoder.py
- tests/bettertransformer/test_encoder.py
- tests/bettertransformer/test_encoder_decoder.py
- tests/bettertransformer/test_vision.py
- tests/bettertransformer/testing_utils.py
WIP, support training for (almost) all archs.
Though for now for encoders we pass `attention_mask` to SDPA, so it will only dispatch to the math path. I tried to use nestedtensor https://github.com/pytorch/pytorch/issues/105913 without much success.
We probably should be more flexible to allow to use xformers / Hazy-flash that do support either custom mask or indexing.
cc @younesbelkada 
Fixes https://github.com/huggingface/optimum/issues/1081 https://github.com/huggingface/optimum/issues/952 https://github.com/huggingface/optimum/issues/971
Still some tests to add / make pass, and precise the doc
> BetterTransformer support training & autocast for all archs

- optimum/onnxruntime/configuration.py
- optimum/onnxruntime/quantization.py
As per title
Partially fixes https://github.com/huggingface/optimum/issues/1243 and align with the previous transformers script
> ORT quantizes by default all ops

- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/trainer_seq2seq.py
- optimum/onnxruntime/training_args.py
As per title.
__These PRs are for the inference__ (evaluation / prediction) of trainer APIs. Given that the Trainer APIs are mainly used for training, and the ORT inference can always be done with `ORTModel`(s) in the optimum library, there is no priority nor eta for the following PRs. If anyone is interested in contributing, please feel free to open a PR and tag me for review. I am willing to handle them, but I have no vision of when I can have the bandwidth for them...
* Improve the export of models
* Support merged decoder
* Register more tasks supported by Optimum right now
> Update ORT training to be compatible with transformers 4.31

- optimum/bettertransformer/models/attention.py
An other small fix. StarCoder is kind of special in that for layer-wise scaling, it unscales just before the softmax. So we actually do not need the `unscale` if we want numerical equivalence.
See https://github.com/huggingface/transformers/blob/641adca55832ed9c5648f54dcd8926d67d3511db/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L133 & https://github.com/huggingface/transformers/blob/641adca55832ed9c5648f54dcd8926d67d3511db/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L66-L71
Fixes https://github.com/huggingface/optimum/pull/1252#issuecomment-1665369601
> Fix BT starcoder fp16

- optimum/onnxruntime/trainer.py
Fix throughput drop using ORTModule. ORTModule gets a fp32 model therefore much slower now
Command
python -m torch.distributed.launch --nproc_per_node=8 --use-env optimum/examples/onnxruntime/training/text-classification/run_glue.py --model_name_or_path microsoft/deberta-large  \
--task_name MRPC --max_seq_length 128 --learning_rate 3e-6 --do_train --output_dir /dev/shm --overwrite_output_dir --max_steps 200 --logging_steps 200 --per_device_train_batch_size 32 --fp16 
Before
85%|████████▌ | 170/200 [01:31<00:08,  3.64it/s]
86%|████████▌ | 171/200 [01:31<00:07,  3.64it/s]
Now
85%|████████▌ | 170/200 [02:46<00:22,  1.35it/s]
86%|████████▌ | 171/200 [02:46<00:21,  1.35it/s]
> Fix ORTModule uses fp32 model issue

- .github/workflows/build_pr_documentation.yml
- .github/workflows/test_exporters_gpu.yml
- docs/source/quicktour.mdx
The Furiosa docbuilding requires secrets.
PRs from forks need to be labeled `build-pr-doc` to run the workflow.
> Fix build PR doc workflow

- .github/workflows/test_exporters_gpu.yml
- .github/workflows/test_onnxruntime_gpu.yml
- .github/workflows/test_onnxruntime_train.yml
As per title, correcting a bug in the exporters GPU workflow.
> Avoid triggering stop job on label

- optimum/bettertransformer/models/encoder_models.py
Some checks were missing in the encoders while present in the decoders.
Fixes https://github.com/huggingface/optimum/issues/1302
> Check output_attentions is False in BetterTransformer

- optimum/exporters/tasks.py
- optimum/pipelines/pipelines_base.py
- tests/exporters/onnx/test_onnx_config_loss.py
Various fixes for transformers 4.32.
For the disabled tests: we can fix in transformers if that is an issue to anybody. In the meantime I think it is very low priority, I doubt anybody uses these.
Disabling following https://github.com/huggingface/transformers/pull/24979/files that is breaking for us (now getting `onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ArgMax(13) node with name '/ArgMax`, see https://github.com/microsoft/onnxruntime/issues/10068)
> ONNX: disable text-generation models for sequence classification & fixes for transformers 4.32

- docs/source/llm_quantization/usage_guides/quantization.mdx
- optimum/gptq/quantizer.py
This PR fixes a few nits on the GPTQ integration such as default args values and the doc.
> Fix gptq params

- tests/benchmark/README.md
- tests/benchmark/benchmark_gptq.py
Add a benchmark just for the prefill step. It is interesting as we see that the GPTQ throughput for large batch size stays decent for large batch sizes during the prefill step, so it is fit for e.g. LoRA training.
> Add GPTQ prefill benchmark

- tests/exporters/onnx/test_onnx_export.py
Fix opset for onnx export
Current tests fail with this error 
```bash
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::tril' to ONNX opset version 13 is not supported. Support for this operator was added in version 14, try exporting with this version.
```
> Fix opset custom onnx export

- tests/exporters/onnx/test_onnx_export.py
The MPT model is now supported for export, so `test_custom_export_trust_remote_error` is failing. This PR proposes to replace the MPT model with the Ernie model.
> Replace mpt to ernie custom export

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/onnx/__init__.py
- optimum/onnx/graph_transformations.py
- optimum/onnx/transformations_utils.py
This is the case for example when the embedding weight and language modeling head share the same weight.
Although PyTorch has a pass to deduplicate identical initializers (https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/passes/onnx/deduplicate_initializers.cpp), one issue arises when torch.onnx.export does constant folding, that may e.g. transpose a weight (in the nn.Linear case), that later messes up with the initializer deduplication. See details: https://github.com/pytorch/pytorch/issues/108342
For small models, the duplication can result in ONNX weights >30% larger vs pytorch weight. The issue is less severe for large models. Given that doing constant folding is generally good, just passing `do_constant_folding=False` is not really a satisfying solution hence this PR.
e.g. …
> Fix PyTorch tied weights being duplicated in the exported ONNX models

- optimum/gptq/data.py
- optimum/gptq/quantizer.py
- optimum/utils/import_utils.py
- tests/gptq/test_quantization.py
This PR bumps the minimum required version of `auto_gptq` and adds the possibility to change the max input length when using exllama + act_order with gptq. 
We also do a couple of fixes: 
- disable exllama kernel when doing quantization with act order because the user may save the model with the weights in the wrong order. exllama + act_order should only be used for inference and the user should not save the model. This is a temporary measure until we are able to reorder the weights.
- `self.quant_method = QuantizationMethod.GPTQ `for people who wants to quantize with optimum api and load it with transformers like this [tutorial](https://www.philschmid.de/gptq-llama) .
> Version bump + add max_input_length to gptq 

- optimum/bettertransformer/models/__init__.py
- optimum/bettertransformer/models/attention.py
- optimum/bettertransformer/models/decoder_models.py
- optimum/utils/__init__.py
- optimum/utils/import_utils.py
- optimum/utils/input_generators.py
- optimum/utils/normalized_config.py
- tests/bettertransformer/test_decoder.py
- tests/bettertransformer/testing_utils.py
As per title, adds Falcon to BT ! 
We probably need to drop the call to torch.scaled_dot_product_attention in the modeling code of falcon to avoid code de-duplication
https://github.com/huggingface/transformers/blob/main/src/transformers/models/falcon/modeling_falcon.py#L434
cc @fxmarty
> [`BetterTransformer`] Add falcon to `BetterTransformer`

- optimum/onnxruntime/modeling_seq2seq.py
- tests/benchmark/benchmark_bettertransformer.py
Fix following https://github.com/huggingface/transformers/pull/22955
cc @mht-sharma @IlyasMoutawwakil
Currently if `decoder_input_ids` is passed (which is typically the case for donut, see https://huggingface.co/docs/transformers/v4.32.1/en/model_doc/donut#inference), inference with ORT for donut will fail:
```
File "/home/fxmarty/hf_internship/transformers/src/transformers/generation/utils.py", line 1499, in generate
input_ids, model_kwargs = self._prepare_decoder_input_ids_for_generation(
File "/home/fxmarty/hf_internship/transformers/src/transformers/generation/utils.py", line 695, in _prepare_decoder_input_ids_for_generation
elif self.config.model_type == "vision-encoder-decoder" and "donut" in self.name_or_path.lower():
AttributeError: 'ORTModelForVision2Seq' object has no attribute …
```
> Add name_or_path for donut generation

- optimum/pipelines/diffusers/pipeline_stable_diffusion_xl.py
Running the SDXL ORT pipeline with a negative prompt throws an error related to the shape of the embeds:
```
File "/opt/onnx-web/api/onnx_web/chain/base.py", line 158, in stage_tile
output_tile = stage_pipe.run(
File "/opt/onnx-web/api/onnx_web/chain/source_txt2img.py", line 109, in run
result = pipe(
File "/home/ssube/miniconda3/envs/onnx-web-rocm-pytorch2/lib/python3.9/site-packages/optimum/onnxruntime/modeling_diffusion.py", line 590, in __call__
return StableDiffusionXLPipelineMixin.__call__(self, *args, **kwargs)
File "/home/ssube/miniconda3/envs/onnx-web-rocm-pytorch2/lib/python3.9/site-packages/optimum/pipelines/diffusers/pipeline_stable_diffusion_xl.py", line 446, in __call__
prompt_embeds = np.concatenate((negative_prompt_embeds, prompt_embeds), …
```
> send both negative prompt embeds to ORT SDXL

- docs/source/bettertransformer/overview.mdx
Forgot it when adding the support.
> Add GPT BigCode to the BT documentation

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/utils.py
Bug introduced in https://github.com/huggingface/optimum/pull/1307, not catched in the review and visibly the GPU tests were not run offline. This will need a patch release as the fp16 ONNX export is broken.
> Fix wrong dtype in the ONNX export

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
As per title, we do not want to globally set the multiprocessing start method simply when importing `convert.py`, as it may mess up with external tools that rely on the fork start method.
Fixes https://github.com/huggingface/optimum/issues/1327
> Guard multiprocessing set start method

- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__init__.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/utils.py
- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/utils/input_generators.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/test_optimization.py
Supersede https://github.com/huggingface/optimum/pull/1289 & https://github.com/huggingface/optimum/pull/984
Fix a critical issue where the exported ONNX models could not produce meaningful results for batch size > 1 due to a very strong assumption in transformers: that all sequences are of the same length if `position_ids` is not passed. See: https://github.com/huggingface/transformers/blob/a796f7eea6c86b54671a6f522cebbe41f630bb62/src/transformers/models/gpt2/modeling_gpt2.py#L802
Left to do:
cc @xenova
> Add position ids in ONNX export and ORT

- tests/onnxruntime/test_modeling.py
Since https://github.com/huggingface/optimum/pull/1403 the `ImportError` will never be raised https://github.com/huggingface/optimum/blob/3c4ad78f16a15fa59ad6e71034ddaca714cdfc20/optimum/onnxruntime/utils.py#L225-L227
> Fix ORT execution provider test for onnxruntime v1.16.0

- docs/source/index.mdx
Fix (temporary?) as current links in the text of doc tiles is destroying the layout. It used to work before, even though nested `a` tags are not allowed in HTML.
> Remove links in doc tiles

- docs/source/index.mdx
Due to nested `<a>` elements, css style breaks
See broken [here](https://play.tailwindcss.com/bPgqtJj3yJ)
Fix it by replacing `<a>` elements with `<span>` elements with `on:click` attribute
See fixed [here](https://play.tailwindcss.com/9w2r6QGViN)
> Fix index.mdx rendering

- optimum/onnxruntime/utils.py
- optimum/utils/normalized_config.py
Replace key of `_conf` with underscore to dash so that we have the same format as the `TasksManager._SUPPORTED_MODEL_TYPE` https://github.com/huggingface/optimum/blob/6d1ae0eb9d3660b46f1b2e705ff2f61b38baacd6/optimum/exporters/tasks.py#L281 Currently there is a mix between the two which makes this model https://huggingface.co/hf-internal-testing/tiny-random-BlenderbotSmallForCausalLM/blob/main/config.json#L27 not compatible for example
> Fix normalized config key for models architecture

- optimum/bettertransformer/models/attention.py
This PR fixes the integration of llama in bettertransformers. Since the [PR](https://github.com/huggingface/transformers/pull/25598) about flashattention2 in llama models was merged, a new argument `padding_mask` was introduced silently in the forward of the attention module. This breaks the forward of the `llama_forward` in bettertransformer. 
@younesbelkada We may have to do it for every model that supports flashattention2. LMK if I should just do one PR for all supported + plan to support models ?
> Fix arg in bettertransformer llama attention 

- optimum/bettertransformer/models/attention.py
- optimum/bettertransformer/models/decoder_models.py
- optimum/utils/dummy_bettertransformer_objects.py
- optimum/utils/import_utils.py
- optimum/utils/input_generators.py
- optimum/utils/normalized_config.py
- tests/bettertransformer/testing_utils.py
Fixes https://github.com/huggingface/optimum/issues/1430
> Falcon BetterTransformer requires transformers>=4.34

- optimum/exporters/onnx/model_configs.py
LLama uses an optional configuration key `num_key_value_heads` for the number of heads, and uses `num_attention_heads` to compute the head dimension. This was unfortunately not implemented in https://github.com/huggingface/optimum/pull/975 (apart from llama2 70b, the llama and llama2 series do not make use of this num_key_value_heads key), as the key probably did not exist at the time.
Fixes https://github.com/huggingface/optimum/issues/1399
> Fix llama ONNX export

- optimum/onnxruntime/configuration.py
Fixes https://github.com/huggingface/optimum/issues/1418
> Improve ONNX quantization doc

- optimum/exporters/tasks.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/test_optimization.py
- tests/onnxruntime/test_quantization.py
PyTorch 2.1 introduced a breaking change in torchscript graph capture that make the export of bart for those tasks fail.
Given that there is probably low usage anyway, let's simply remove the support for it and let's try to get the CI green.
See details: https://github.com/pytorch/pytorch/issues/110597
> Disable bart onnx export for text-classification and question-answering

- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
Followup of https://github.com/huggingface/optimum/pull/1449
The variable is no longer used and it is cleaner to just remove it.
> Remove ARCH_MODEL_MAP from tests

- examples/onnxruntime/training/language-modeling/run_clm.py
**Changes Made**
- Added handling for configurations that may not have the max_position_embeddings attribute.
- Introduced a default value of 1024 for max_position_embeddings when it's missing in the configuration.
**Motivation and Context**
- Fixing this issue: https://github.com/huggingface/optimum/issues/1477
- This PR addresses an issue where some configurations lack the max_position_embeddings attribute, causing failures in certain scenarios.
> fix max_pos_embeddings error

- docs/source/llm_quantization/usage_guides/quantization.mdx
- optimum/gptq/quantizer.py
- optimum/utils/import_utils.py
- tests/gptq/test_quantization.py
This PR adds the possibility to choose exllamav2 kernels for GPTQ model This PR follows the [integration](https://github.com/PanQiWei/AutoGPTQ/pull/349) of the kernels in auto-gptq. I've also added a test to check that we are able to load and infer using exllamav2 kernel. I will update the benchmark in a follow-up PR.
> add_exllamav2

- optimum/exporters/onnx/__main__.py
Fixes https://github.com/huggingface/optimum/pull/1404#discussion_r1365673709
> Fix custom architecture detection in onnx export

- optimum/gptq/quantizer.py
This PR removes the possibility to quantize a model with exllamav2 as we don't be save to save the weights as they are somehow reordered.
> disable_exllamav2_for_quantization

- examples/onnxruntime/training/language-modeling/run_clm.py
Models with no sequence length limit will fail to create a dataset because the block_size will be -1.
and it will error this:
`ValueError: num_samples should be a positive integer value, but got num_samples=0`
this PR handles the case where max_position_embeddings  is -1, we set block size to a default value.
> Handling block_size value for models with no sequence length limit.

- optimum/gptq/data.py
- optimum/gptq/quantizer.py
This PR fixes the error when pad_token_id is set ( in order to user batch size > 1). 
```bash 
>>>  File "optimum/optimum/gptq/data.py", line 57, in <listcomp>
collate_data(new_examples[start : start + batch_size], pad_token_id)
File "optimum/optimum/gptq/data.py", line 88, in collate_data
label_blocks = [block["labels"] for block in blocks]
File "optimum/optimum/gptq/data.py", line 88, in <listcomp>
label_blocks = [block["labels"] for block in blocks]
KeyError: 'labels'
```
@SunMarc  Please have a look
> fix a argument error

- optimum/exporters/onnx/convert.py
- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_decoder.py
> Fix tests ORTModel

- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
> Swin2sr onnx

- optimum/exporters/onnx/model_patcher.py
- tests/exporters/exporters_utils.py
Fixes https://github.com/huggingface/optimum/issues/1495
For some reason ORT is unhappy about https://github.com/huggingface/transformers/blob/3ec10e6c76362191b61260300fe1d6173a8dd7e1/src/transformers/models/falcon/modeling_falcon.py#L166, and for some reason PyTorch ONNX export adds a cast to complex128 there.
> Fix Falcon ONNX export with alibi

- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
This PR adds the ability to export DPT+GLPN models to ONNX for depth-estimation, unblocking https://github.com/xenova/transformers.js/issues/350.
... and it crosses DPT+GLPN off [this list](https://github.com/huggingface/optimum/issues/555).
Running
```
optimum-cli export onnx -m hf-internal-testing/tiny-random-DPTModel o --task depth-estimation
```
now shows:
```
...
Validating ONNX model o/model.onnx...
-[✓] ONNX model output names match reference model (predicted_depth)
- Validating ONNX Model output "predicted_depth":
-[✓] (2, 32, 32) matches (2, 32, 32)
-[✓] all values close (atol: 1e-05)
The ONNX export succeeded and the exported model was saved at: o
```
Similarly,
```
optimum-cli export onnx -m hf-internal-testing/tiny-random-GLPNForDepthEstimation o
```
produces:
```
... …
```
> [ONNX export] Add depth-estimation w/ DPT+GLPN

- optimum/utils/normalized_config.py
It creates a `NormalizedTextConfigWithGQA` class that inherints `NormalizedTextConfig` to handle models that use GQA instead of vanilla MHA.
> Refactor NormalizedConfigs for GQA

- docs/source/index.mdx
- docs/source/installation.mdx
This PR adds an AMD tile to the optimum documentation main page to tease the incoming `optimum-amd` package.
> Add AMD to the documentation main page

- README.md
- docs/source/index.mdx
- docs/source/installation.mdx
can be merged once https://github.com/huggingface/optimum/pull/1555/ is merged
> Add amd documentation

- docs/source/onnxruntime/usage_guides/amdgpu.mdx
> Update ROCM ORT doc

- docs/source/exporters/onnx/overview.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- optimum/onnxruntime/modeling_ort.py
- optimum/utils/normalized_config.py
- tests/exporters/exporters_utils.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
Adds support for exporting [convnextv2](https://huggingface.co/models?other=convnextv2) models to ONNX.
Exports: https://huggingface.co/models?library=transformers.js&other=convnextv2&sort=trending
These exports have been tested (and work) with Transformers.js ([PR](https://github.com/xenova/transformers.js/pull/428)) 👍 
> Add `convnextv2` onnx export

- optimum/gptq/constants.py
- optimum/gptq/quantizer.py
- setup.py
- tests/gptq/test_quantization.py
As per title, fixes https://github.com/PanQiWei/AutoGPTQ/issues/462
> Fix GPTQ compatibility with AutoGPTQ

- .github/workflows/doctests.yml
- .github/workflows/test_bettertransformer_gpu.yml
- .github/workflows/test_exporters_gpu.yml
- .github/workflows/test_gptq.yml
- .github/workflows/test_onnxruntime_gpu.yml
- .github/workflows/test_onnxruntime_train.yml
Update GPU CIs with EC2 runners.
> Refactoring EC2 CIs

- optimum/gptq/quantizer.py
- tests/gptq/test_quantization.py
This PR adds the `inside_layer_modules` arg for GPTQ quantization. This will enable the user to quantize specific modules inside a block. This is needed for quantizing model and run quantized model such as https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GPTQ
> add `modules_in_block_to_quantize` arg for gptq

- tests/gptq/test_quantization.py
What does this PR do ? 
This PR fixes the failing [tests](https://github.com/huggingface/optimum/actions/runs/7142761585/job/19452757481). The tests are flaky depending on the hardware used. For now, I've only added multiple expected output but we might need to find a better way to tests these (comparing logits ?). solves #1575
> [GPTQ] fix tests

- docs/source/exporters/onnx/usage_guides/export_a_model.mdx
- optimum/exporters/tasks.py
This message is also shown when exporting models to OpenVINO format (in optimum-intel), which does not use ONNX. Replaced "Using pt to export to ONNX" with "Using pt to export the model".
@echarlaix
> Remove "to ONNX" from info message when exporting model

- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
QA pipeline post-processing is failing for models like https://huggingface.co/hf-internal-testing/tiny-random-XLMModel or https://huggingface.co/hf-internal-testing/tiny-random-xlm as described in https://github.com/huggingface/transformers/issues/28000
> Modify model id for test

- optimum/exporters/onnx/model_patcher.py
As noted by https://github.com/huggingface/optimum/issues/1621, the `all_layer_embeddings` may be unwanted.
> Fix sentence transformers ONNX export

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/model_patcher.py
- optimum/utils/input_generators.py
Adds support for supplying negative points in ONNX export.
> Add `input_labels` input to SAM model export

- docs/source/exporters/onnx/overview.mdx
- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
- tests/exporters/exporters_utils.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
Enable export of the models with fixed shapes.
This is required to support export of model like "vovnet" which cannot be exported with dynamic shapes.
```bash
optimum-cli export onnx --model timm/ese_vovnet39b.ra_in1k  out_vov --no-dynamic-axes
```
> Enable export of model with fixed shape

- optimum/gptq/data.py
This PR slices the wikitext2 dataset to only takes the first 1000 items (length of 288059). This is needed since tokenizing a big dataset for some tokenizer takes a long time. Fixes #1655.
> Fix wikitext2 processing

- optimum/gptq/quantizer.py
Fixes local variable 'dataset' referenced before assignment
```python
from transformers import AutoModelForCausalLM, AutoTokenizer, GPTQConfig
model_id = "facebook/opt-125m"
tokenizer = AutoTokenizer.from_pretrained(model_id)
dataset = [{"input_ids": [0, 1, 2, 3, 4], "attention_mask": [1, 1, 1, 1, 1]}]
gptq_config = GPTQConfig(bits=4, dataset=dataset, tokenizer=tokenizer)
quantized_model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", quantization_config=gptq_config)
```
The logic is broken if we pass a tokenized dataset to the GPTQQuantizer.
https://github.com/huggingface/optimum/blob/7376c6ad7f0a852cb81dfbb9e9539eb6ed14fd36/optimum/gptq/quantizer.py#L358-L382
```
File "lib/python3.10/site-packages/transformers/models/auto/auto_factor …
```
> Fix: local variable 'dataset' referenced before assignment

- optimum/pipelines/diffusers/watermark.py
`StableDiffusionXLPipelineMixin` https://github.com/huggingface/optimum/blob/7376c6ad7f0a852cb81dfbb9e9539eb6ed14fd36/optimum/pipelines/diffusers/pipeline_stable_diffusion_xl.py#L490 and `StableDiffusionXLImg2ImgPipelineMixin` https://github.com/huggingface/optimum/blob/7376c6ad7f0a852cb81dfbb9e9539eb6ed14fd36/optimum/pipelines/diffusers/pipeline_stable_diffusion_xl_img2img.py#L497
apply watermark to the output of `vae_decoder`. 
However, the default watermarker `StableDiffusionXLWatermarker` does not support `float16` images because `cv2.cvtColor` doesn't support it. 
Running the following code
```python
from optimum.pipelines.diffusers.watermark import StableDiffusionXLWatermarker
import numpy as np
watermarker = StableDiffusionXLWatermarker()
fp16_image = np.random.rand(1, 3, 1024, …
```
> Support float16 images in StableDiffusionXLWatermarker

- optimum/bettertransformer/models/encoder_models.py
In the current code, the check for `BertLayerBetterTransformer.forward` only contains these conditions:
```
if not self.training and not torch.is_autocast_enabled() and not torch.is_autocast_cpu_enabled():
```
These conditions cannot return the correct result of `autocast_enabled` on the Intel xpu platform, causing the model to use the wrong optimization method. `torch._C._is_any_autocast_enabled` contains more detections and can be a better choice.
> Extend autocast check to cover more platforms like XPU

- optimum/onnxruntime/modeling_decoder.py
It fixes the following error when using a fp16 model with split fp16 input/output cache:
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))`
> Add fp16 support for split cache

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/test_optimization.py
- tests/onnxruntime/test_quantization.py
This PR reactivate the Bart Onnx Export which was disabled because of a Pytorch 2.1 regression. 
Since Pytorch 2.1.2 it is now fixed.
This [issue](https://github.com/huggingface/optimum/issues/1485) was the original issue of the export failure.
Question: To prevent this issue, hard constraints might be put under torch to make sure nobody gets optimum installed with torch 2.0 trying to export those models ? It should be above 1.11 but under 2.0 and could be above 2.1 as well. 
Tagging @fxmarty as he disabled the tests.
> Reactivate BART Onnx Export

- optimum/onnxruntime/modeling_ort.py
- tests/onnxruntime/test_modeling.py
Matching previous behavior. Even sentence-transformers models are exported with `last_hidden_states` output.
> ORTModelForFeatureExtraction always exports as transformers models

- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- optimum/exporters/tflite/__main__.py
- tests/exporters/common/test_tasks_manager.py
- tests/exporters/exporters_utils.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
This is bad practice as `PretrainedConfig.model_type` is a class attribute.
We also dissociate `_SUPPORTED_MODEL_TYPE` by library, as suggested by @JingyaHuang.
Both
```
optimum-cli export onnx -m sentence-transformers/all-MiniLM-L6-v2 minilm_st_onnx --library-name sentence_transformers
```
and
```
optimum-cli export onnx -m sentence-transformers/all-MiniLM-L6-v2 minilm_onnx --library-name transformers
```
work as expected.
Still need to specify `transformers` in the `ORTModel` with `export=True` (we do not support sentence-transformers).
> Avoid overriding model_type in TasksManager

- optimum/gptq/quantizer.py
- tests/gptq/test_quantization.py
This PR fixes the case where the user passes device_map = "cpu". In that case, we still need to move each block to the gpu 0 on our own since we didn't add hooks. 
Fixes [28632](https://github.com/huggingface/transformers/issues/28632)
> Fix gptq device_map = "cpu"

- optimum/exporters/onnx/model_patcher.py
- tests/onnxruntime/test_modeling.py
As per title, fixes `RuntimeError: dictionary changed size during iteration`
> CI: Avoid iterating over a mutated iterable

- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
- tests/exporters/onnx/test_onnx_config_loss.py
Re-enables sequence classification for decoder-based models. This requires a user to pass in `--pad_token_id` which required a change to the tests
I also removed a default pad token override for GPT-2 which seemed like a bad idea (sets it to 0, which corresponds to `!`) -- let me know if this is problematic 
This passes a fair number of tests in `tests/exporters/onnx/` for me, but I deselected some so we may need to iterate here
Fixes https://github.com/huggingface/optimum/issues/1527
> re-enable decoder sequence classification

- docs/source/exporters/onnx/package_reference/export.mdx
- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__init__.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
- tests/exporters/onnx/test_onnx_export.py
As per title. It should ideally not be in `__main__.py`, as this file is kept simply for backward compatibility of `pythonm -m optimum.exporters.onnx`.
Motivation: not seeing `from optimum.exporters.onnx.__main__ import onnx_export` in code snippets.
> Move & rename `onnx_export`

- .github/workflows/build_main_documentation.yml
- tests/cli/test_cli.py
- tests/onnxruntime/test_quantization.py
Skip failing tests due to a regression in ORT that will be fixed in its next patch release
Fix as well `ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device` on the build main doc workflow (https://github.com/huggingface/optimum/actions/runs/7899612672)
> Disable failing test & free space when building documentation

- .github/workflows/build_main_documentation.yml
- .github/workflows/test_onnxruntime.yml
Github actions seem to have decreased the available space on its ubuntu runners, see https://github.com/actions/runner-images/discussions/9329 & https://github.com/actions/runner-images/pull/9251/files
Go from 19G to 54G free disk space in 3min.
> Fix no space left on device in actions

- tests/benchmark/README.md
- tests/benchmark/benchmark_gptq.py
As per title. Reran the whole benchmark with more recent torch / AutoGPTQ / transformers versions.
> Add end-to-end Marlin benchmark

- .github/workflows/build_main_documentation.yml
As per title. Building Furiosa doc somehow uses npm.
Merging as non-critical.
> Fix main doc build

- .github/workflows/build_pr_documentation.yml
- docs/combine_docs.py
- docs/source/index.mdx
This PR triggers the PR doc build for the `pull_request` event instead of `pull_request_target`. `pull_request_target` was used so that the secrets needed to build Furiosa's doc can be accessed from forks (after authorization). However, this event always triggers the associated workflow from main in PRs, which is not convenient when modifying this specific workflow because we cannot see the changes.
As a workaround, this PR switches back to `pull_request` and the doc of Furiosa is not built for PRs.
Needed for #1624.
> Switch back to `pull_request` event for PR doc build

- examples/onnxruntime/training/image-classification/run_image_classification.py
- optimum/exporters/model_preparation.py
- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- optimum/exporters/utils.py
This PR propose to move model preparation to export outside onnx exporter for ability reuse it in different exporters (e.g. openvino, neuron) that may have own export configs. Changes are backward compatible for onnx export, should not affect other components, but will help in reusage models preparation (partitioning, building export configs) in other optimum exporters
> move model for export preparation to be able reuse in other exporters

- examples/onnxruntime/training/image-classification/run_image_classification.py
- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_decoder.py
- tests/onnxruntime/test_modeling.py
As pointed out by @BBerabi @lidingsnyk, `_reorder_cache` was missing for `ORTGPTBigCodeForCausalLM`, which makes beam search fail.
Fixes https://github.com/huggingface/optimum/issues/1475
> Fix starcoder ORT integration

- optimum/exporters/onnx/base.py
- optimum/exporters/tasks.py
For some vision archs, the default pipeline tag was updated on the Hub, see https://huggingface.co/datasets/huggingface/transformers-metadata/commit/f6b73676b57a0b6624ebfcc823fa2a86ba716b60 & https://huggingface.slack.com/archives/C02EK7C3SHW/p1708984225769709
This fixes the auto task detection for these architectures.
> Add image feature extraction task

- optimum/onnxruntime/training_args.py
Transformers Introduced AccelerateConfigure dataclass https://github.com/huggingface/transformers/pull/28664
So we need to initialize it in Optimum Training Args.
Check this issue for reference: https://github.com/huggingface/optimum/issues/1749
> Initialize AcceleratorConfig in optimum TrainingArgs.

- optimum/gptq/quantizer.py
This PR set a maximum seqlen that we use to create our calibration dataset. For models like mistral, we have a seqlen of 32768 which results in issues when creating the calibration dataset. The dataset don't need to have data with a big seqlen too. 
Fixes https://github.com/huggingface/transformers/issues/29494
> Fix maximum seqlen for gptq quantization

- tests/exporters/exporters_utils.py
Test that would have catched https://github.com/huggingface/optimum/issues/1731 & https://github.com/UKPLab/sentence-transformers/pull/2510
This should be merged only by sentence_transformers 2.5.0 (or 2.4.1) release.
> Extend sentence-transformers ONNX test

- optimum/exporters/tasks.py
- optimum/onnxruntime/runs/__init__.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
Hiya 👋 
`ORTModelForSemanticSegmentation` is already implemented, DPT model in ONNX is already implemented too, but semantic segmentation isn't a task that was supported in DPT and DPT to ORT semantic segmentation integration tests, so I added that. The tests passed on my local so I hope it's gonna work fine. 
I also wanted to add BeiT but I got `op_name = 'adaptive_avg_pool2d, input size not accessible`
> Add DPT support for ORTModelForSemanticSegmentation

- optimum/exporters/tasks.py
- optimum/modeling_base.py
- tests/onnxruntime/test_modeling.py
This broke in https://github.com/huggingface/optimum/pull/1578 cc @mht-sharma 
Fixes https://github.com/huggingface/optimum/issues/1737
> Fix use_auth_token with ORTModel

- optimum/exporters/onnx/model_configs.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
- setup.py
Fix compatibility of ORTModels with transformers pipelines (broken since https://github.com/huggingface/transformers/commit/53d891247bd45f316d3d710c64b54964bea14a64)
Failing tests : https://github.com/huggingface/optimum/actions/runs/8377803444
Also update phi default opset (needed since https://github.com/huggingface/transformers/pull/29108)
> Fix compatibility with transformers v 4.39.0

- optimum/onnxruntime/training_args.py
Following https://github.com/huggingface/optimum/pull/1750 which breaks compatibility for transformers < `v4.38.0`
> Fix training args transformers compatibility

- optimum/onnx/graph_transformations.py
Following onnx 1.16 release (https://github.com/onnx/onnx/releases/tag/v1.16.0) with the new IR version 10 not yet handled by ORT.
Making the CI green
> Fix IR version for merged ONNX decoders

- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/training_args.py
This PR adds functionality to dump onnx graphs via input arguments to ORTTrainer. This will assist in easier debugging processes for developers running into ONNX Runtime errors. [[docs](https://github.com/microsoft/onnxruntime/wiki/Performance-Investigation)]
Test Machine: 8xV100, cu118, python3.10
Test Environment: 
```docker 
FROM mcr.microsoft.com/aifx/acpt/stable-ubuntu2004-cu118-py310-torch222
RUN pip install accelerate evaluate transformers scikit-learn
RUN git clone https://github.com/prathikr/optimum.git && cd optimum && git checkout prathikrao/add-debug-options && python setup.py install
```
Test Command: `torchrun --nproc_per_node 8 optimum/examples/onnxruntime/training/language-modelling/run_clm.py --model_name_or_path mistralai/Mistral-7B-v0.1 --dataset_name wikitext …
> adds debug options to dump onnx graphs

- .github/workflows/test_offline.yml
- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/tasks.py
- optimum/modeling_base.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_diffusion.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
Make ONNX export & ORT inference work offline when the Hub is down.
Fixes https://github.com/huggingface/optimum/issues/1796
> Fix offline compatibility

- optimum/exporters/onnx/convert.py
- optimum/onnx/utils.py
e.g.
```
(hf-inf) fxmarty@huggingface:~/qwen_onnx$ ls
added_tokens.json       merges.txt                                                   model.onnx               tokenizer_config.json
config.json             _model_layers.0_self_attn_rotary_emb_Constant_5_attr__value  model.onnx_data          tokenizer.json
generation_config.json  _model_layers.0_self_attn_rotary_emb_Constant_attr__value    special_tokens_map.json  vocab.json
```
`_model_layers.0_self_attn_rotary_emb_Constant_5_attr__value` and `_model_layers.0_self_attn_rotary_emb_Constant_attr__value` are actually in `model.onnx_data` already.
> Remove unnecessary constants for > 2GB ONNX models

- optimum/onnxruntime/utils.py
This PR adds an export option to pix2struct model (document vision-language model) by optimizing its ViT encoder
I have tested the export locally and have seen the model outputs the same captions as the original model (exported https://huggingface.co/google/pix2struct-screen2words-base and tested on https://github.com/google-research-datasets/screen2words dataset)
If there is more testing that I need to do or document the change somewhere please let me know
> Add onnx export function for pix2struct model

- .github/workflows/dev_test_bettertransformer.yml
- .github/workflows/dev_test_dummy_inputs.yml
- .github/workflows/dev_test_fx.yml
- .github/workflows/dev_test_onnx.yml
- .github/workflows/dev_test_onnxruntime.yml
- .github/workflows/dev_test_optimum_common.yml
- .github/workflows/test_bettertransformer.yml
- .github/workflows/test_cli.yml
- .github/workflows/test_dummy_inputs.yml
- .github/workflows/test_fx.yml
- .github/workflows/test_onnx.yml
- .github/workflows/test_onnxruntime.yml
- .github/workflows/test_optimum_common.yml
Python 3.8 and 3.9 on macos-latest no longer work
> update to github workflows 

- optimum/gptq/quantizer.py
For some GPTQ quantized models (e.g. TheBloke/Yi-34B-Chat-GPTQ), the Linear layers in the model do not include bias, but when using transformers to load these GPTQ quantized models, optimum randomly initializes bias in the Linear layers, causing a decrease in the model's accuracy. This PR fixes this issue.
- GPTQ, quantization: @fxmarty, @SunMarc
> Fix bug causing random initialization of bias when using GPTQ quantization with models without bias

- optimum/modeling_base.py
- optimum/utils/normalized_config.py
This PR adds support for Phi-3 mini in Optimum. The optimized and quantized ONNX models for Phi-3 mini are uploaded as part of the [Phi-3 collection](https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3) for the [4K instruct](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx) and [128K instruct](https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx) variants. 
Example usage:
```
git clone https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx
```
```
from optimum.onnxruntime import ORTModelForCausalLM
model = ORTModelForCausalLM.from_pretrained(
"./Phi-3-mini-128k-instruct-onnx/cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4",
decoder_file_name="phi3-mini-128k-instruct-cpu-int4-rtn-block-32-acc-level-4.onnx", …
```
> Add Phi-3 mini to Optimum

- optimum/exporters/onnx/model_configs.py
Ported from https://github.com/huggingface/optimum-intel/pull/692
remove number of channels from unet and vae dynamic inputs and outputs. From model topology perspective, this value can not be different during inference from specified in config (changing number of channels requires to recreate pytorch model as number of channels in the first conv depends on it). Having them static will simplify model graph
@echarlaix
> make stable diffusion unet and vae number of channels static

- docs/source/exporters/onnx/overview.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- optimum/utils/__init__.py
- setup.py
- tests/exporters/exporters_utils.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
as per title
Fixes #1826 
(Needs transformers>=4.41.0)
* CLI
```bash
optimum-cli export onnx --model microsoft/Phi-3-mini-4k-instruct phi3_onnx/
```
* ORTModel
```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
model_id = "microsoft/Phi-3-mini-4k-instruct"
model = ORTModelForCausalLM.from_pretrained(model_id, export=True)
model.save_pretrained("phi3_onnx/")
model_id = "phi3_onnx/"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = ORTModelForCausalLM.from_pretrained(model_id)
inputs = tokenizer(["Hello, my dog is cute"], return_tensors="pt")
outputs = model.generate(**inputs, max_length=50)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True))
```
> Add phi3 support in ONNX exporter

- optimum/commands/onnxruntime/quantize.py
There's a simple typo in the file quantize.py which comes up while converting onnx models to their quantized forms. Fixing that.
> Fix quantize.py

- .github/workflows/test_cli.yml
- optimum/commands/onnxruntime/quantize.py
- optimum/onnxruntime/configuration.py
- tests/cli/test_cli.py
> Fix ort config instantiation (from_pretrained) and saving (save_pretrained)

- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/utils.py
- optimum/utils/normalized_config.py
- tests/onnxruntime/test_optimization.py
Adds the segformer model to ORTOptimizer.  Based on the advice I got in https://github.com/huggingface/optimum/issues/1761, but I decided to start with segformer.
@mht-sharma maybe?
> ORTOptimizer for the model type Segformer

- optimum/commands/__init__.py
- optimum/commands/optimum_cli.py
- optimum/onnxruntime/subpackage/__init__.py
- optimum/onnxruntime/subpackage/commands/__init__.py
- optimum/onnxruntime/subpackage/commands/base.py
- optimum/onnxruntime/subpackage/commands/optimize.py
- optimum/onnxruntime/subpackage/commands/quantize.py
- optimum/subpackages.py
This introduces explicitly the concept of `optimum` subpackages that are loaded "dynamically" by the `optimum-cli` (and possibly in the future by other high-level abstraction modules that would require backend-specific implementations).
An `optimum` subpackage is primarily a package under the `optimum` namespace, but it can be also a module inside the `optimum` package itself, even if that module does not have its own `pyproject.toml` or `setup.py` (as a real namespace package would).
By convention, loading a subpackage means importing a `subpackage` module available at the root of the package.
This pull-request first adds a `load_subpackages` helper that will go through the installed namespace packages and try to "load" them.
It then adds a decorator to declare custom subcommands, using …
> Allow optimum to discover and load subpackages

- .github/workflows/test_onnxruntime.yml
- optimum/utils/testing_utils.py
- tests/onnxruntime/test_modeling.py
- tests/utils/test_task_processors.py
> Remove read token

- optimum/onnxruntime/base.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/utils/testing_utils.py
- tests/onnxruntime/test_modeling.py
Fixes multiple windows specific issues:
- dtype mismatch: numpy uses a default int representation that depends on os. On ubuntu/macos it uses `int64` but on windows it uses `int32`. This results in tokenizers returning input ids and attention masks in a different format than torch's default which is int64/long.
- shutil.rmtree doesn't always work on windows, there's some random failures that we can see when a tempfile is being closed (cleaned up) or when directly trying to shutil.rmtree a folder.
Also seq2seq decoder used to return past kv cache in torch format all the time.
> Fix Windows and onnx dtype compatibility

- optimum/onnxruntime/subpackage/commands/quantize.py
When quantizing the models >2Gb, it's important to set the flag use_external_data_format to 'true',
since otherwise the quantization will fail due to
`ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB`
However, currently there is no way to set the parameter when using optimum-cli because there is no such
command option. Theoretically, it could be set when using ORTConfig file with -c comman flag, because one of the configuration parameters in it is use_external_data_format. In fact, the optimum code ignores it and does not pass it in quantize() function.
The goal of this change is to close this gap.
Fixes #1916
> Read use_external_data_format from ORTConfig file

- .github/workflows/test_offline.yml
- setup.py
Fixes numpy v2 incompatibility with onnxruntime.
Transformers constrained numpy as well https://github.com/huggingface/transformers/pull/31569
> Pin numpy v1 for onnxruntime

- optimum/exporters/onnx/model_configs.py
in general case, number of encoder and decoder layers in seq2seq models like blenderbot, m2m, bart can be different from encoder.
As example blenderbot-3b - https://huggingface.co/facebook/blenderbot-3B/blob/main/config.json
If we use these models for causal lm case, where used only decoder, output names can be incorrect due to unequal number of layers in decoder and encoder (that is used for preparing inputs if model has past_key_values).
This PR fixes this issue
> Fix incorrect names for usage blenderbot for causallm

- optimum/exporters/onnx/model_patcher.py
`_update_causal_mask` was introduced in v4.42.0 (https://github.com/huggingface/transformers/pull/30642)
> Fix sentence transformers modeling patching for export

- optimum/exporters/onnx/model_patcher.py
OpenVINO exporter fails with this op even though ONNX exporter is okay with it.
> Remove inplace op in mistral patcher

- optimum/onnxruntime/modeling_ort.py
Fix forward bug in ORTModelForFeatureExtraction when using CUDAExecutionProvider.
Current code will result in crash when using cuda.
> Fix forward bug in ORTModelForFeatureExtraction

- examples/onnxruntime/optimization/multiple-choice/run_swag.py
- examples/onnxruntime/optimization/question-answering/run_qa.py
- examples/onnxruntime/optimization/text-classification/README.md
- examples/onnxruntime/optimization/text-classification/run_glue.py
- examples/onnxruntime/optimization/token-classification/run_ner.py
- examples/onnxruntime/quantization/image-classification/run_image_classification.py
- examples/onnxruntime/quantization/multiple-choice/run_swag.py
- examples/onnxruntime/quantization/question-answering/README.md
- examples/onnxruntime/quantization/question-answering/run_qa.py
- examples/onnxruntime/quantization/text-classification/README.md
- examples/onnxruntime/quantization/text-classification/run_glue.py
- examples/onnxruntime/quantization/token-classification/README.md
- examples/onnxruntime/quantization/token-classification/run_ner.py
- optimum/onnxruntime/model.py
- optimum/onnxruntime/utils.py
> Deprecate ORTModel class

- optimum/onnxruntime/subpackage/commands/optimize.py
The command line optimum-cli onnxruntime optimize ... is incorrectly parsed. With -c flag specified, it creates an empty ORTConfig object without loading a passed-in configuration file.
This change:
fixes the issue
fixes the typo "from_pretained" --> "from_pretrained"
adds handling of the error case when none of -O1, -O2, -O3, -O4 or -c options is provided
> Fix optimizer's command line reading

- optimum/exporters/tasks.py
> Fix undefined variable in library name inference

- .github/workflows/test_export_onnx_cli.yml
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/model_patcher.py
- setup.py
In https://github.com/huggingface/optimum/pull/1963 `unmask_unattended_patched`  signature was modified to fix compatibility with transformers >= v4.39.0, here we fix compatibility for  < v4.39.0
> fix gpt bigcode ONNX export for transformers<4.39.0

- optimum/exporters/tasks.py
- optimum/onnxruntime/runs/__init__.py
Some pipelines (eg. `StableDiffusionInstructPix2PixPipeline`) are not included in the auto pipelines of diffusers, we could previously still load these models for export. However, the refactoring #1947 limits the support to only pipelines included in those auto pipeline APIs.
Error I got with the refactoring:
```
======================================================================== test session starts ========================================================================
platform linux -- Python 3.8.10, pytest-8.0.0, pluggy-1.5.0
rootdir: /home/ubuntu/optimum-neuron
configfile: pyproject.toml
plugins: anyio-4.4.0
collected 14 items …
```
> Follow up the diffusers task refactoring

- .github/workflows/test_fx_automatic_parallel.yml
- optimum/fx/parallelization/api.py
- optimum/fx/parallelization/core.py
- optimum/fx/parallelization/decomp.py
- optimum/fx/parallelization/op_registry/__init__.py
- optimum/fx/parallelization/op_registry/op_handlers.py
- optimum/fx/parallelization/passes.py
- optimum/fx/parallelization/utils.py
As per title, this PR tries a more general approach rather than relying purely on human heuristics, basically it uses the following steps to search a possible parallelization strategy for a transformer model
- Use dynamo for graph tracing so that we get the graph to operate on
- Decompose and functionalize the traced graph so that we get a smaller op set to work with
- Apply parallel axis analysis and do a constrained backtracking search on the whole graph to get a possible solution(not necessarily optimal)
- Replace ops the original traced graph with their parallelized version(Linear -> ColumnLinear/RowLinear)
And for the API design, we disable the support of passing custom modules and only focus on models in transformers because supporting custom models is not the priority for now.
> Modify Parallelization Strategy to Make it More General

- optimum/utils/preprocessing/token_classification.py
`trust_remote_code` shouldn't be set by default to True, reverting from 7cc57e40f84e00f8ebc2849da303e40575fb23b4, might make sense to change the dataset instead cc @IlyasMoutawwakil
> Modify token classification processor default dataset args

- optimum/onnxruntime/io_binding/io_binding_helper.py
fix attribute name of [ORTmodel](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/modeling_ort.py#L271) from `inputs_names` to `input_names`
a solution for #1992
> fix attribute name from `inputs_names` to `input_names`

- examples/onnxruntime/training/image-classification/README.md
- optimum/onnxruntime/training_args.py
This PR applies the deprecated `evaluation_strategy` from https://github.com/huggingface/transformers/pull/30190.
TL;DR: `evaluation_strategy` -> `eval_strategy`
(Should go live in v4.41.0, but opening now so it's here when ready!)
- ONNX Runtime Training: @JingyaHuang
> Apply deprecated `evaluation_strategy`

- optimum/onnxruntime/trainer.py
- optimum/onnxruntime/trainer_seq2seq.py
Minor fixes corresponding to https://github.com/huggingface/transformers/pull/25599 and https://github.com/huggingface/transformers/pull/29334
> update transformers imports for `deepspeed` and `is_torch_xla_available`

- README.md
- setup.py
This simply adds an option to `setup.py` to install quanto, and some basic instructions to quantize, save and reload a model.
> Add quanto install and instructions

- optimum/onnxruntime/utils.py
This PR fixes discovery of CuPy when it's installed using one of the distributions of pre-built wheels.
The CuPy library ships both a source distribution (`cupy`) as well as versions containing pre-built wheels (`cupy-cuda11x`, `cupy-cuda12x`, `cupy-rocm-5-0`, `cupy-rocm-4-3`). Use of `_is_package_available` to detect CuPy only works for the source distribution of CuPy and fails when using the pre-built wheels versions.
This is because the `_is_package_available` will always attempt to resolve version information (even if it's not required) and in doing so assumes that the _importable_ package name matches the _installed_ distribution name. While this is usually the case, it doesn't work for CuPy and several other libraries. ONNX Runtime for example might be installed as `onnxruntime` or …
> Fixes detection of CuPy installed with pre-built wheels

- optimum/gptq/constants.py
- optimum/gptq/quantizer.py
> Disable the exllama on all non-cuda devices.

- optimum/fx/parallelization/decomp.py
- optimum/fx/parallelization/op_registry/op_handlers.py
- optimum/fx/parallelization/parallel_layers/__init__.py
- optimum/fx/parallelization/parallel_layers/loss.py
- optimum/fx/parallelization/passes.py
- optimum/fx/parallelization/utils.py
- tests/fx/parallelization/test_tensor_parallel.py
> Add Parallel Cross Entropy

- optimum/onnxruntime/trainer.py
Following https://github.com/huggingface/optimum/pull/2012. There is one occurrence of `is_torch_tpu_available` in the code of the `ORTTrainer` class, which will fail for `transformers >= 4.39.0`.
> Fix `is_torch_tpu_available` in ORT Trainer

- optimum/onnxruntime/__init__.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/runs/__init__.py
- optimum/pipelines/pipelines_base.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
Fixes #2030
Image To Image task consist lot more than Diffusion and there are transformer based model such as Swin. 
This PR adds the support for pielining image-to-image task with ORTModelForImage2Image.
e.g.
```python
from transformers import AutoImageProcessor
from optimum.pipelines import pipeline
from optimum.onnxruntime import ORTModelForImageToImage
from PIL import Image
model = ORTModelForImageToImage.from_pretrained("swin2sr-2x-onnx", use_io_binding=True)
processor = AutoImageProcessor.from_pretrained("caidas/swin2SR-classical-sr-x2-64")
onnx = pipeline("image-to-image", model=model, feature_extractor=processor, device="cuda")
image_path = "image.png"
image = Image.open(image_path)
output = onnx(image)
```
> Added image-to-image task for ORT Pipeline 

- setup.py
The version constraint for `numpy<2.0` in `transformers` has been removed by @ydshieh in https://github.com/huggingface/transformers/pull/32018
Fixes #2037
> Remove numpy version constraint in setup.py

- setup.py
To not block a release from optimum-intel, optimum-neuron, optimum-habana and others to support the latest transformers release (removing the need to dsync it with an optimum release)
> remove upper transformers version limit

- .github/workflows/stale.yml
Taken from TGI: https://github.com/huggingface/text-generation-inference/blob/main/.github/workflows/stale.yaml
> Add workflow to mark issues as stale

- optimum/exporters/onnx/convert.py
- tests/exporters/onnx/test_exporters_onnx_cli.py
Fixes https://github.com/huggingface/optimum/issues/2052
> Fix onnx export

- .github/workflows/test_onnxruntime.yml
- tests/onnxruntime/test_modeling.py
needed by `test_load_model_from_hub_private` which was previously always skipped https://github.com/huggingface/optimum/blob/9fd9ca5505e83f67c2a5e4c4f6f56d5fcf28442f/tests/onnxruntime/test_modeling.py#L974
> Fix tests expected environment variable name

- docs/source/onnxruntime/package_reference/modeling_ort.mdx
- docs/source/onnxruntime/usage_guides/models.mdx
Clarify that on-the-fly conversion + model saving + pushing your model on the hub work for all models (not just transformers models). 
Also replace `ORTXxxxPipeline` with `ORTDiffusionPipeline`, couple of code snippets were removed to not overburden the documentation, but could be moved in a tutorial page like done for openvino https://huggingface.co/docs/optimum/main/en/intel/openvino/tutorials/diffusers
> Clean up ORT documentation

- optimum/onnxruntime/modeling_ort.py
- tests/onnxruntime/test_modeling.py
Fix https://github.com/huggingface/optimum/issues/2062
> Create token type ids when not provided 

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/utils.py
- optimum/exporters/tasks.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/utils.py
- optimum/utils/normalized_config.py
- tests/exporters/exporters_utils.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
This PR adds support for models using IBM's [GraniteForCausalLM](https://github.com/huggingface/transformers/blob/main/src/transformers/models/granite/modeling_granite.py#L1008) architecture when converting to ONNX. The key changes are:
* ~~Allow users to opt into using `transformers>=4.45` for `onnx` conversions~~ No longer needed
* Add `"granite"` to model configs and tasks
* Add `"granite"` as a `model_type` that uses grouped attention
**NOTE**: I encountered an issue very similar to the one discussed in https://github.com/huggingface/optimum/issues/1835. The root cause for me was the need to add `"granite"` to the list of models requiring Grouped Query Attention in `modeling_decoder.py`. I don't believe that is the root cause for #1835 since `"llama"` is already present there, but it …
> Onnx granite

- docs/Dockerfile
Fixes doc generation now that python 3.8 was dropped in https://github.com/huggingface/optimum/pull/2086
> Update Dockerfile base image

- optimum/utils/input_generators.py
As per title, when using `DummyTimestepInputGenerator`, we don't necessarily need to generate all inputs managed by this generator. E.g. Pixart alpha, no "text_embeds" / "timestep_cond," no attribute `text_encoder_projection_dim`/`time_cond_proj_dim` then, but they are currently mandatory, making it diffisult to use the generator just to generate `timestep` / `time_ids.`
> Unbundle inputs generated by `DummyTimestepInputGenerator`

- docs/source/exporters/onnx/overview.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
- tests/onnxruntime/test_modeling.py
- tests/onnxruntime/utils_onnxruntime_tests.py
Fixes #2092
Hi, this pull request adds support for the RemBERT model based on the example mentioned in issue #2092.
@IlyasMoutawwakil
> Rembert onnx support

- optimum/exporters/onnx/model_patcher.py
When model's output is tuple or list, `filtered_outputs` doesn't get assigned and hence always a empty dict
> fix bug `ModelPatcher` returns empty outputs

- .github/workflows/stale.yml
https://github.com/huggingface/optimum/actions/runs/12131603639
```
Error: [#2083] Error when creating a comment: Resource not accessible by integration
Error: [#2083] Error when adding a label: Resource not accessible by integration
```
> Fix workflow to mark issues as stale

- docs/source/exporters/onnx/overview.mdx
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/onnx/model_patcher.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
- tests/onnxruntime/utils_onnxruntime_tests.py
Adds ONNX export support for https://huggingface.co/alibaba-damo/mgp-str-base
> Add ONNX export support for MGP-STR

- docs/source/exporters/onnx/overview.mdx
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
> Add ONNX export support for OLMo and OLMo2

- optimum/exporters/tasks.py
Fixes #2115
This passes on the `model_kwargs` in `get_model_from_task` to the SentenceTransformer's `model_kwargs` parameter. Additionally, we add `torch_dtype` to `model_kwargs` before doing this so we can export SentenceTransformer's models in different dtypes. 
Tagging @michaelbenayoun for a review
> Pass on `model_kwargs` when exporting a SentenceTransformers model

- optimum/exporters/onnx/base.py
- optimum/exporters/onnx/config.py
- optimum/exporters/onnx/convert.py
- optimum/exporters/onnx/model_configs.py
- optimum/exporters/utils.py
`check_dummy_inputs_allowed` is helpful function for any optimum that involves pytorch models conversion (e.g. openvino). Current place of it import trigger initialization of full onnx configuration for other backends that wish to reuse it and it may lead to some troubles with resolving dependencies. I suggest to move it to common utilities for avoiding unexpected errors like represented bellow:
Example of logs (issue visible on windows with onnx>1.16.2 and related to https://github.com/onnx/onnx/issues/6267):
```
File "C:\Users\chuquanc\openvino\py310\lib\site-packages\optimum\intel\openvino\__init__.py", line 51, in <module>
from .quantization import OVQuantizer
File "C:\Users\chuquanc\openvino\py310\lib\site-packages\optimum\intel\openvino\quantization.py", line 47, in <module>
from …
```
> move check_dummy_inputs_allowed to common export utils

- .github/workflows/test_bettertransformer.yml
- .github/workflows/test_onnxruntime.yml
https://github.com/huggingface/optimum/pull/2119#issuecomment-2538755578
Tests failing coming from mps not supported by arm64 macOS runners https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#limitations-for-arm64-macos-runners and from mps being now set default when device not specified and mps backend available since transformers v4.47 and [huggingface/transformers#34026](https://github.com/huggingface/transformers/pull/34026/files). Issue not related to optimum so merging to not block transformers v4.47 support
> Remove CI macos runners

- tests/onnxruntime/test_modeling.py
https://github.com/huggingface/optimum/actions/runs/12406440330/job/34639615964?pr=2114
```
FAILED tests/onnxruntime/test_modeling.py::ORTModelIntegrationTest::test_load_model_from_hub_private - huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6763cff5-38ad3a1d75a3598d6b742f30;13c34049-a28a-43d1-a22b-e79829428ccf)
Repository Not Found for url: https://huggingface.co/api/models/optimum-internal-testing/tiny-random-phi-private/tree/onnx?recursive=True&expand=False.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```
> Skip private model loading for external contributors

- optimum/exporters/utils.py
after some refactoring export part, sdxl-refiner model become broken for exporting.
https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0
This model does not have text_encoder and only text_encoder_2, now export failed with AtributeError: 'NoneType' object has no attribute 'config'
see for reference https://github.com/huggingface/optimum-intel/actions/runs/12426942003/job/34696091118?pr=1085
> fix sdxl refiner export

- optimum/gptq/constants.py
- optimum/gptq/utils.py
This PR fixes the issue encountered when using AutoModel to load the GPTQ model, which caused this error:
```
File "/root/GPTQModel/test_inf.py", line 5, in <module>
model = AutoModel.from_pretrained(model_id, revision="main")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/transformers/src/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
return model_class.from_pretrained(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/transformers/src/transformers/modeling_utils.py", line 4090, in from_pretrained
hf_quantizer.preprocess_model(
File "/root/transformers/src/transformers/quantizers/base.py", line 194, in preprocess_model
return self._process_model_before_weight_loading(model, **kwargs) …
```
> Fix AutoModel can't load gptq model due to module prefix mismatch vs AutoModelForCausalLM

- optimum/gptq/quantizer.py
A small fix for the device map. We should only assign the device to 0 when it detects the device is CPU. Otherwise, it will break the device_map="auto".
With this change, we could pass the device map check of transformers gptq test. See [here](https://github.com/huggingface/transformers/pull/35012/)
Hi @IlyasMoutawwakil . Please trigger the CI and review the tiny change. Thanks!
> fix device check

- optimum/exporters/onnx/__main__.py
- optimum/exporters/tasks.py
- optimum/exporters/tflite/__main__.py
- optimum/exporters/tflite/convert.py
issue found during attempt to export https://huggingface.co/BAAI/bge-small-zh-v1.5 via optimum-intel without --task specification
The root cause is infer_library_from_model detects task as sentence-transformers even if --library transformers selected in cli and there is no additional condition for specification task for sentence transformers, as the result method raises error
```
KeyError: "The task could not be automatically inferred. Please provide the argument --task with the relevant task from image-text-to-text, audio-classification, zero-shot-image-classification, masked-im, audio-xvector, image-to-text, audio-frame-classification, depth-estimation, visual-question-answering, semantic-segmentation, image-to-image, image-classification, feature-extraction, image-segmentation, …
```
> fix infer task from model_name if model from sentence transformer

- optimum/exporters/onnx/model_configs.py
- optimum/exporters/tasks.py
- tests/exporters/exporters_utils.py
Fixes #555 (issue)
Support Megatron Bert model config.
> Adding Onnx Support For Megatron-Bert

- docs/source/bettertransformer/overview.mdx
- docs/source/bettertransformer/tutorials/contribute.mdx
- docs/source/bettertransformer/tutorials/convert.mdx
- docs/source/onnxruntime/usage_guides/models.mdx
- docs/source/onnxruntime/usage_guides/optimization.mdx
- docs/source/quicktour.mdx
Fixed all typos in the docs section, this includes every single typos in any of the `.mdx` files.
@fxmarty, @JingyaHuang
> Fixed All Typos in docs

- optimum/exporters/tasks.py
- optimum/subpackages.py
in case if library_name detection has additional logic on optimum-integration path and not defined inside standard task manager approach to find library (e.g. open_clip integration),  parameters standardization may fail as the library will not be detected properly.
> avoid library_name guessing if it is known in parameters standartization

- setup.py
This updates the `neuronx` extra to remove the `transformers` version.
Installing `optimum-neuron` through `optimum` is anyway not the preferred installation mode: the documentation now recommends to install `optimum-neuron` directly.
> Update optimum neuron extra

- README.md
The README looks super crowded and I feel that it makes it even more difficult to understand the different support. In this PR we remove the many different code snippets and replace them with documentations links instead
> Remove README code snippets

- optimum/onnxruntime/trainer.py
Deepspeed (since 2022) already includes the FusedAdam FP16_Optimizer originally from NVIDIA/apex here (and it's better maintained wrt deepspeed grad_norm, MOE training, etc): https://github.com/deepspeedai/DeepSpeed/blob/master/deepspeed/runtime/fp16/fused_optimizer.py
Currently this line gives a warning saying:
```
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/onnxruntime/training/optim/_modifier_registry.py:56: UserWarning: Skip modifying optimizer because of optimizer name not found in the registry: accelerate.utils.deepspeed.DeepSpeedOptimizerWrapper
```
which is actually caused by `get_full_qualified_type_name(optimizer.optimizer) = 'deepspeed.runtime.fp16.fused_optimizer.FP16_Optimizer'` not being in the onnxruntime registry: …
> Remove FP16_Optimizer patch for DeepSpeed

- optimum/exporters/onnx/model_patcher.py
I observe that patching for `_prepare_4d_causal_attention_mask_for_sdpa` trying to override some native pytorch (torch.ops namespace) and unpatching does not return original behaviour back instead of that, it replaces pytorch module by function from transformers.
It lead to errors when torch.export used in the same environment, where optimum export called.
For avoid that suggested 2 additional fixes:
1. use prefix for avoiding patch some unexpected modules where object with the same name exists (if I right understand original intention was to change behavior for transformers only and that is more controlled)
2. check that type of object is the same before patching for avoid misplaced with replacing module or class by function
> reduce area of patch_everywhere for avoid unexpected replacements

- optimum/onnxruntime/modeling_ort.py
- tests/onnxruntime/test_modeling.py
This PR adds support for image models in ORTModelForFeatureExtraction, specifically addressing ViT and other visual models. The implementation modifies the forward method to dynamically handle both text and image inputs by detecting the presence of image-specific input keys like 'pixel_values'. This allows users to seamlessly use ORTModelForFeatureExtraction for both text and image feature extraction tasks without requiring a separate class structure. Tests have been updated to properly validate this functionality across all supported architectures, including Vision Transformer (ViT) models.
Fixes the issue : https://github.com/huggingface/optimum/issues/2226
> Add feature extraction support for image models

- optimum/onnxruntime/modeling_ort.py
- tests/onnxruntime/test_modeling.py
This PR updates the `ORTModelForFeatureExtraction`'s `forward `method to accept `**kwargs`, ensuring better compatibility with Hugging Face Transformers' conventions. In particular, it adds proper support for the `return_dict `argument: when explicitly passed, the output is returned as a plain dictionary instead of being wrapped in a `ModelOutput`. Additionally, any unused keyword arguments are logged with a warning to help users identify unsupported inputs while maintaining backward compatibility.
Fixes issue : https://github.com/huggingface/optimum/issues/2266
> Fix bug ORTModelForFeatureExtraction

- optimum/commands/export/onnx.py
- optimum/exporters/onnx/__main__.py
- optimum/exporters/onnx/convert.py
- optimum/utils/__init__.py
- optimum/utils/import_utils.py
- setup.py
- tests/exporters/onnx/test_export_cli.py
- tests/exporters/utils.py
This pr introduces [onnxslim](https://github.com/inisis/OnnxSlim), a new high performance onnx optimization tool.
for gpt2 model, we can reduce number of operators and model size without losing accuracy, and applies to many other models.
```
optimum-cli export onnx --model gpt2 gpt2_onnx/ --slim
```
```
+------------------------------+------------------------------------------+------------------------------------------+
|             Add              |                   114                    |                   114                    |
|             Cast             |                    34                    |                    3                     |
|            Concat            |                   177                    |                   113                    |
| …
```
> feat: add onnxslim

- optimum/exporters/onnx/__main__.py
- optimum/modeling_base.py
- optimum/onnxruntime/modeling_decoder.py
- optimum/onnxruntime/modeling_ort.py
- optimum/onnxruntime/modeling_seq2seq.py
In my last PR I must have changed some defaults by mistake (e.g. force_download for CausalLM)
maybe it makes sense to start using something like this for the hub kwargs to guarantee they are the same across the lib
https://github.com/huggingface/transformers/blob/46a4b7c909fab58355936e1c7109bb5e2e558267/src/transformers/models/glm4/modular_glm4.py#L63
> Fix and uniformize hub kwargs

- optimum/onnxruntime/utils.py
- optimum/utils/normalized_config.py
- tests/onnxruntime/test_optimization.py
Fixes #2177 where ModernBERT support for exporting to ONNX format was added but optimizations not fully enabled.  
Minor change that adds `modernbert` to necessary configuration management objects. In local tests, optimizations provided noticeable speedups with identical results to non-optimized model.
> Add ONNX export optimization support for ModernBERT

- optimum/gptq/constants.py
This PR fixes the issue encountered when using Qwen2VLForConditionalGeneration to load the GPTQ model:
```
ValueError                                Traceback (most recent call last)
[<ipython-input-1-1109427887>](https://localhost:8080/#) in <cell line: 0>()
4 
5 gptq_config = GPTQConfig(bits=4, use_exllama=False)
----> 6 model = Qwen2VLForConditionalGeneration.from_pretrained(
7     "Qwen/Qwen2-VL-2B-Instruct-GPTQ-Int4",
8     torch_dtype=torch.float16,
5 frames
[/usr/local/lib/python3.11/dist-packages/optimum/gptq/utils.py](https://localhost:8080/#) in get_block_name_with_pattern(model)
75         if any(name.startswith(pattern_candidate) for name in modules_names):
76             return pattern_candidate
---> 77     raise ValueError("Block pattern could not be match. Pass …
```
> Fix 'Block pattern could not be match. Pass `block_name_to_quantize` argument in `quantize_model`' while loading Qwen VL GPTQ model

- setup.py
Was added in https://github.com/huggingface/optimum/pull/403 but shouldn't be needed
> remove timm from exporters extra

- docs/README.md
Replaced the outdated and broken link to the Trainer documentation in the README with the correct, up-to-date URL pointing to the Hugging Face Transformers Trainer documentation. This ensures users can access the relevant Trainer docs without encountering a 404 error.
> Fix broken Trainer documentation link in README

- setup.py
Install with Optimum extra is not recommended for neuron for a while. Remove the extra to avoid confusion.
> Remove neuronx extra from setup.py
